### ISSUE TITLE
Depending on a tapped formula without the full path shouldn't be possible

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/legacy-homebrew#14089]
Currently, we allow a formula to `depends_on` a tapped formula without specifying the repo name. This has the potential to encourage taps to do some confusing stuff that's hard for end-users to debug.

For instance, php53 and php54 in josegonzalez/php used to depend on an unqualified `zlib` - which only worked for users with homebrew/dupes tapped, since neither mxcl/homebrew nor josegonzalez/php include a `zlib`. This was reported by a user in IRC when `brew upgrade` failed with confusing error messages.

Suggestion: `depends_on` should not allow unqualified names when called with a tapped formula, unless the formula being depended on comes from the same tap. While I'm -1 on the added complexity, inadvertently allowing third-party taps to do Bad Things seems like it's setting the stage for more confusion.

**Comment by MikeMcQuaid** [comment]
Now that every formula is in a tap: I think this no longer applies.
