### ISSUE TITLE
Cleanup subformulae downloads

### ISSUE THREAD

**Issue by wonbyte** [Homebrew/legacy-homebrew#17414]
I just updated to the latest version of git:

(gps ~)$ brew info git
git: stable 1.8.1.2, HEAD
http://git-scm.com
/usr/local/Cellar/git/1.8.1.2 (1267 files, 26M) *
https://github.com/mxcl/homebrew/commits/master/Library/Formula/git.rb
==> Options
--with-blk-sha1
	Compile with the block-optimized SHA1 implementation
--with-pcre
	Compile with the PCRE library
==> Caveats
The OS X keychain credential helper has been installed to:
  /usr/local/bin/git-credential-osxkeychain

The 'contrib' directory has been installed to:
  /usr/local/share/git-core/contrib

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

and noticed that running brew cleanup did not remove git-manpages-1.8.1.1.tar.gz. It removed the outdated formula and the htmldocs but left manpages. Is there a reason cleanup left  it?

**Comment by MikeMcQuaid** [comment]
We don't really use subformulae any more and this is broadly encompassed by https://github.com/Homebrew/brew/issues/568.
