### ISSUE TITLE
MacOS.(gcc|clang|llvm)_version can return nil

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/legacy-homebrew#18781]
If the requested compiler isn't installed, the various `MacOS` compiler version methods will return nil instead of an int.

While maybe not a bad thing, we test against the outputs of those with `<=>` fairly frequently and that's going to fail if the result is nil. Leads to some breakage in Tigerbrew, and I imagine it's going to cause problems for us when llvm-gcc is dropped.

We should probably be returning a `CompilerVersion` class of some kind instead of a bare int, a la `MacOS::Version`.

**Comment by MikeMcQuaid** [comment]
I think we can close this out at this point; it seems it's not being either addressed or causing major problems.
