### ISSUE TITLE
Should we be specifying -nostdinc and include paths in superenv?

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/legacy-homebrew#19642]
Even though we control other paths in superenv, we're not controlling header search paths. As a result, and because /usr/local/lib comes before /usr/lib in the search path, it's possible for gcc/clang to pick up brewed headers even when they're not specified as dependencies.

I ran into this when writing [this OpenSMTPD formula](https://gist.github.com/mistydemeo/5519261), which isn't compatible with our berkeley DB but is with the system's; the compiler would always pick up homebrew's version.

Wondering if maybe we should specify [`-nostdinc`](http://gcc.gnu.org/onlinedocs/cpp/Search-Path.html) and construct the search path in the same way we do with the PATH.

**Comment by mikemcquaid** [comment]
CC @mistydemeo on your own issues just because this may relate to your current work.

**Comment by MikeMcQuaid** [comment]
Maybe we should but: we didn't so closing this out.
