### ISSUE TITLE
Superenv should filter out -stdlib=

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/legacy-homebrew#26824]
Currently superenv doesn't filter out clang's `-stdlib=` arguments. This means that a makefile that tries to call `clang` with `-stdlib=` may instead get an FSF GCC, but still pass along the argument that it can't understand.

Do we want to filter these out only if the compiler isn't clang, or always? I'm leaning towards the latter.

**Comment by mikemcquaid** [comment]
CC @mistydemeo as this may relate to your current superenv work.

**Comment by MikeMcQuaid** [comment]
Maybe we did but: we didn't so closing this out.
