### ISSUE TITLE
Bug: `brew leaves` returns error if one of installed formulas has untapped optional dependencies

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/legacy-homebrew#28847]
I installed `homebrew/python/matplotlib`. And in this formula it has an optional dependency `homebrew/dupes/tcl-tk`. As I didn't tap the `homebrew/dupes`, if I run `brew leaves`, it will show the following error:

```
$ brew leaves
Error: No available formula for tcl-tk
Please tap it and then try again: brew tap homebrew/dupes
```

**Comment by mikemcquaid** [comment]
@xu-cheng Is this still an issue?

**Comment by ilovezfs** [comment]
Looks fixed https://gist.github.com/ilovezfs/7aed2aa8aed3ebb791cc9ad93355b847
