### ISSUE TITLE
revisions don't play nice with dependencies that were installed with "--devel"

### ISSUE THREAD

**Issue by MerelyAPseudonym** [Homebrew/legacy-homebrew#29207]
Basically, if formula B depends on formula A, and A has been installed with `--devel`, then B won't recognize A's installation *unless* A isn't marked with a `revision`.

This problem currently exists with GHC and cabal-install, but you can verify the problem with a much easier-to-use pair of formulae: `tomcat` and `tomcat-native`. If you `brew install --devel tomcat`, then `brew missing tomcat-native` will report that nothing is missing and `brew install tomcat-native` will even build successfully. *However*, if you edit the `tomcat` formula so that it has a revision, then `brew missing tomcat-native` will still report that nothing is missing **but** upon running `brew install tomcat-native` it will try to install `tomcat` as a dependency.

For example, running `brew install --devel tomcat` on the following formula will install Tomcat 8 to `/usr/local/Cellar/tomcat/8.0.5_2` (note the "_2" suffix)

```ruby
require 'formula'

class Tomcat < Formula
  homepage 'http://tomcat.apache.org/'
  url 'http://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-7/v7.0.53/bin/apache-tomcat-7.0.53.tar.gz'
  sha1 '269a01f03ed22e5ad7fa33dec300ef40cac96440'
  revision 2

  option "with-fulldocs", "Install full documentation locally"

  devel do
    url "http://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-8/v8.0.5/bin/apache-tomcat-8.0.5.tar.gz"
    sha1 "dc21157e8577132999f090859be2c4468e841c23"

    resource "fulldocs" do
      url "http://www.apache.org/dyn/closer.cgi?path=/tomcat/tomcat-8/v8.0.5/bin/apache-tomcat-8.0.5-fulldocs.tar.gz"
      version "8.0.5"
      sha1 "8d27a447e1d38d6491d47e15d66c4bc9b03ef55f"
    end
  end

  resource 'fulldocs' do
    url 'http://www.apache.org/dyn/closer.cgi?path=/tomcat/tomcat-7/v7.0.53/bin/apache-tomcat-7.0.53-fulldocs.tar.gz'
    version '7.0.53'
    sha1 '4a6585ee59d7fef1e144652227986f9e390b048c'
  end

  # Keep log folders
  skip_clean 'libexec'

  def install
    # Remove Windows scripts
    rm_rf Dir['bin/*.bat']

    # Install files
    prefix.install %w{ NOTICE LICENSE RELEASE-NOTES RUNNING.txt }
    libexec.install Dir['*']
    bin.install_symlink "#{libexec}/bin/catalina.sh" => "catalina"

    (share/'fulldocs').install resource('fulldocs') if build.with? 'fulldocs'
  end
end

```

It's plausible that the actual issue isn't with the dependency-resolution; perhaps revision-versions are being mistakenly propagated. *If that's the case*, what do you think about being able to put revisions into `{stable,devel,head} do` blocks?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
