### ISSUE TITLE
Have `deps --installed` account for used build options

### ISSUE THREAD

**Issue by int3h** [Homebrew/legacy-homebrew#29918]
Currently, `brew deps` assumes no build options are present, unless the user specifically passes them in when they run the command. For uninstalled formulae, this is the right thing to do.

However, when a user runs `brew deps --installed`, they most likely want to see the actual dependencies of the formulae they have installed. Because `deps` assumes no build options, if an installed formula has a dependency hidden by a build option the user passed during install, it won't be shown. In other words, the output of `deps` will be incorrect for the formula installed on disk.

That has implications for `brew graph` (since the graph won't show dependencies correctly, and will list some formulae as 'safe to remove', even when they're not,) and potentially `brew leaves`. The upshot is that the user will believe they can remove some formulae safely, when in reality, they will be breaking dependencies.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.
