### ISSUE TITLE
CompilerSelectionError recommends wrong package

### ISSUE THREAD

**Issue by rillian** [Homebrew/legacy-homebrew#31068]
homebrew-science/blast.rb has

```fails_with :clang```
```fails_with :gcc => "4.9"```

If gcc 4.9 is (or isn't) installed, it correctly says it cannot build, but CompilerSelectionError just prints the static string:

> To install this formula, you may need to:
>   brew install gcc

If one follows the directions and tries ```brew install gcc``` it installs 4.9, which is the current version. Trying to install blast again results exactly the same error and confusion.

The exception should propagate information about the best packaged option an recommend something like ```brew tap homebrew/versions && brew install gcc48```.

**Comment by MikeMcQuaid** [comment]
This should be improved. We'll accept PRs for this but we're not actively working on it at this time.
