### ISSUE TITLE
Tin issue with missing /etc/tin/tin.defaults

### ISSUE THREAD

**Issue by orbifx** [Homebrew/legacy-homebrew#31473]
If the file `/etc/tin/tin.defaults` does not exist, tin complains about invalid FQDM and posting to groups is not possible with the error `** Posting not allowed **`.

I created the file `/etc/tin/tin.defaults` with content:

```
disable_gnksa_domain_check=ON
domainname=<yourdomain>.com
disable_sender=ON
```

How can that file be created during installation yet include a valid domain? Not sure if it has to be the user's email domain or any valid domain?

**Comment by elmar-hinz** [comment]
The question is still open. Putting the above snippet into `/etc/tin/tin.defaults` helped me to get posting with tin at all.

**Comment by elmar-hinz** [comment]
After posting is possible I can delete ` /etc/tin/`again and posting still works. Strange!

**Comment by DomT4** [comment]
Does it have to be a valid domain or could we write a tiny defaults file with `example.com` written in or such?

```diff
diff --git a/Library/Formula/tin.rb b/Library/Formula/tin.rb
index adebcad..4e2554b 100644
--- a/Library/Formula/tin.rb
+++ b/Library/Formula/tin.rb
@@ -22,9 +22,19 @@ class Tin < Formula
     system "./configure", "--disable-debug",
                           "--disable-dependency-tracking",
                           "--prefix=#{prefix}",
-                          "--mandir=#{man}"
+                          "--mandir=#{man}",
+                          "--with-defaults-dir=#{etc}/tin",
+                          "--with-spooldir=#{var}/spool/news",
+                          "--with-libdir=#{lib}/news"
     system "make", "build"
     system "make", "install"
+
+    (buildpath/"tin.defaults").write <<-EOS.undent
+      disable_gnksa_domain_check=ON
+      domainname=example.com
+      disable_sender=ON
+    EOS
+    (etc/"tin").install buildpath/"tin.defaults"
   end
```

Any dice with that sort of diff?

**Comment by elmar-hinz** [comment]
For me it did work without a valid domain. Indeed it used `domainname=<yourdomain>.com`. To set `example.com` is fine.

> Example Domain

> This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission.

However, I can't tell if it is necessary at all. 

What are the real minimal requirements? What guided @orbifx to exactly this 3 lines of code?

**Comment by orbifx** [comment]
It's been a long while since I did that. Must have found it in some documentation at the time or a combination of errors and manuals.

**Comment by orbifx** [comment]
Check this: http://www.tin.org/bin/man.cgi?section=5&topic=tin
I probably got an error during run and based on the above I got to the conclusion those 3 lines were needed even if as dummies.

**Comment by mikemcquaid** [comment]
Is this still an issue?

**Comment by orbifx** [comment]
I think so, but demand for it seems to have been and gone.

**Comment by mikemcquaid** [comment]
@orbifx Ok, closing this out but we'd accept a pull request.
