### ISSUE TITLE
gcc 4.9.2 fails to produce debugging information

### ISSUE THREAD

**Issue by laurentbartholdi** [Homebrew/legacy-homebrew#34976]
I installed the latest gcc (4.9.2) from a bottle, and also compiled it from scratch using formula gcc49 --disable-multilib. Compilation / installation went fine, and the executable works well. However, the output of the compiler does not have correct debugging information. E.g.,
% echo 'main() {}' > test.c
% gcc-4.9 -g test.c
% gdb a.out
...
warning: `/var/folders/7t/vntm2r4j39q3qxj7vz5yrjfh0000gn/T//ccDthBIc.o': can't open to read symbols: No such file or directory.
(no debugging symbols found)...done.

The problem can be traced to this: 'dsymutil' is not invoked at the end of compilation:
% gcc-4.8 -v -g test.c # this one works
...
dsymutil a.out

% gcc-4.9 -v -g test.c # this one does not
...
/usr/bin/nm -n /var/folders/7t/vntm2r4j39q3qxj7vz5yrjfh0000gn/T//ccjh3x8V.o

**Comment by lgstarn** [comment]
I can get this testcase for me with the following sequence:

% echo 'main() {}' > test.c
% gcc-4.9 -g -c test.c
% gcc-4.9 -g test.o -o test.exe 
% gdb test.exe

Other than the warnings which I detail in #35734 , everything works fine.

**Comment by DomT4** [comment]
We no longer ship this version of GCC in the core. Please re-file at Homebrew/versions if this still persists.

**Comment by DomT4** [comment]
Misread. Potentially not a version exclusive issue. Let's look into this again.

**Comment by tclose** [comment]
I am running into what looks to be the same issue with gcc 5.3. Has there been any progress on this?

**Comment by mikemcquaid** [comment]
There has been no progress on this. It's an upstream issue so it'll need to be resolved with GNU rather than Homebrew work.

**Comment by tdsmith** [comment]
This doesn't seem actionable; please follow up with the gcc community and let us know if we can help.
