### ISSUE TITLE
--force-bottle doesn't propagate to dependencies

### ISSUE THREAD

**Issue by staticfloat** [Homebrew/legacy-homebrew#35100]
Hello all,

I've noticed that when installing a formula with `--force-bottle`, the forcing only occurs for the top-level dependency.  In my mind, if one is asking for a bottle to be force-installed, it's very likely that you'd want all dependencies to be installed as bottles as well.  Either way, this issue is not insurmountable, (I can loop over `brew deps $FORMULA` and `brew install --force-bottle` each one) but it seemed to me that the current behavior is opaque both in on the user-facing end, (If I passed `--force-bottle`, why is it compiling at all?) and in the code. (On [this line](https://github.com/Homebrew/homebrew/blob/ea507c6b3aae1c4687ef600d7ff175e91c70b179/Library/Homebrew/formula_installer.rb#L84), it's not immediately obvious that the values set by `ARGV` will be different for `pour_bottle?` and `dep.pour_bottle?`)

Is this behavior that should be changed, or should I just go ahead and manually loop through every dependency, forcing bottles every time?  (I'm forcing bottles because I am installing on computers that may not have a compiler, and often I can ignore the lack of `Cellar :any` by making use of environment variable overrides.  For instance, `OpenSSL` can act like it's `Cellar :any` if you define `OPENSSL_ENGINES` appropriately, overriding the baked-in paths that cause `brew bottle` to think it's non-relocatable.

**Comment by MikeMcQuaid** [comment]
It's worth noting here that `--force-bottle` is an option designed purely for development purposes. If it wasn't that @staticfloat had made a few contributions already I'd actively guard it behind `HOMEBREW_DEVELOPER`. Closing this as a WONTFIX.
