### ISSUE TITLE
Object files deleted during build of gcc needed by gdb

### ISSUE THREAD

**Issue by lgstarn** [Homebrew/legacy-homebrew#35734]
The temporary files that are created as gcc is built are put into a /tmp directory like so:

...
/private/tmp/gcc-VWmKFo/gcc-4.9.2/build/x86_64-apple-darwin14.0.0/libquadmath/.libs/ctanq.o
...

However, once the build is over, those temporary files are deleted.

Once gdb is installed, any program built with gcc and run with gdb gives the following warnings on start-up that it can't find those build files:

...
warning: `/tmp/gcc-VWmKFo/gcc-4.9.2/build/x86_64-apple-darwin14.0.0/libquadmath/.libs/ctanq.o': can't open to read symbols: No such file or directory.
...

Question: is there a way to keep the object build files from gcc so gdb will not give this long list of errors?

Steps to recreate issue (new install, brew doctor states ready to brew):

- brew install gcc
- brew install gdb
- (codesign gdb) 
- gfortran -c -g hello.f90
- gfortran -g hello.o -o hello.exe
- gdb hello.exe
- press "r" to run
- note the hundreds of warnings for files that were deleted during the build process

hello.f90:
program hello
    implicit none

    print *,'hello'
end program

**Comment by tdsmith** [comment]
This has similar symptomology to #34976; do you think it's the same issue?

**Comment by lgstarn** [comment]
Hi tdsmith, thanks for the response. I commented on 34976 that I am able to get gdb to work on that example by outputting to an intermediate .o file.

I'd like to understand if it is possible to get rid of the hundreds of "warning: `/private/tmp/gcc-rxyDVc/gcc-4.9.2/build/x86_64-apple-darwin14.0.0/libgcc/unwind-dw2-fde-darwin_s.o': can't open to read symbols: No such file or directory" that appear in both my test case and #34976.  I think a fix will be to save those temporary files that are built.  Is there a mechanism within homebrew to save the temporary files?  Or is this purely an upstream issue with gcc?

**Comment by gautamg795** [comment]
I'm having similar issues -- I suspect [this](http://stackoverflow.com/a/27942697/3776173) is related?

**Comment by mikemcquaid** [comment]
@gautamg795 Yeh, sounds like it.

**Comment by tdsmith** [comment]
Dunno what to do about this; please consult the gcc community and let us know if we can do something to resolve this.
