### ISSUE TITLE
--universal does not verify that all ancestors in the dependency tree are also --universal

### ISSUE THREAD

**Issue by danielweiv** [Homebrew/legacy-homebrew#35831]
checking for FcInit in -lfontconfig... yes
checking for jpeg_set_defaults in -ljpeg... yes
checking for LIBXPM... no
checking for vpx_codec_destroy in -lvpx... no
configure: error: vpx support requested, but not found

result generated by running "brew gist-logs gd" is as following: 
https://gist.github.com/4005c50e104a6320ab37

Any idea? Thank you

**Comment by jacknagel** [comment]
Are you installing gd with `--with-libvpx`, or have you done so in the past?

Building wine requires all dependencies be built as universal binaries, but libvpx doesn't have a universal option, so the universal gd cannot link to it.

We can probably add a universal option to libvpx, but I wanted to ask first.

**Comment by danielweiv** [comment]
yes, i installed libvpx before gd. And after uninstalling libvpx, i have wine installed successfully

**Comment by jacknagel** [comment]
I looked at adding a universal option to libvpx, but it's not straightforward.

In the short-to-medium term it's going to be easier to use gd without libvpx.

**Comment by iggyvolz** [comment]
Does adding a conflicts_with "libvpx" make sense on wine?  Although I assume that would cause some cases where gd was not installed with libvpx, therefore not causing a conflict, but wine would assume libvpx was installed with gd.

Is there any way to do conflicts_with "gd" => "with-libvpx", or something of the sort?  I added it and brew audit --strict found no problem with it (I don't dare attempt to modify the delicate wine binary I got with #32132).

**Comment by alexchandel** [comment]
This also happens with samba, which lacks a universal option too, and is an optional dependency of wine.

**Comment by mikemcquaid** [comment]
@alexchandel It'll happen with everything, yes.

**Comment by alexchandel** [comment]
Actually, it turns out x86 wine works perfectly with x86_64 samba, and it's possible that other x86-only or `--universal` formulae work with x64 dependencies, so this isn't necessarily a bug (or alternatively there is more complexity to this issue)

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
