### ISSUE TITLE
can't upgrade percona-toolkit when percona-server installed

### ISSUE THREAD

**Issue by nijikon** [Homebrew/legacy-homebrew#35995]
Hi guys,

I remember we did fix this once. But the issue came back. I can't upgrade percona-toolkit because dependency is unsatisfied. IMHO, this should work.

```
balrog:local n$ brew upgrade percona-toolkit
==> Upgrading 1 outdated package, with result:
percona-toolkit 2.2.12
==> Upgrading percona-toolkit
==> Installing percona-toolkit dependency: mysql
Error: Cannot install mysql because conflicting formulae are installed.

  percona-server: because mysql, mariadb, and percona install the same binaries.

Please `brew unlink percona-server` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

**Comment by xu-cheng** [comment]
It works for me. What's your `which mysql_config`?

**Comment by stephenreay** [comment]
I have the same error as above, and in answer to your question:

    $ which mysql_config
    /usr/local/bin/mysql_config

    $ readlink /usr/local/bin/mysql_config
    ../Cellar/percona-server/5.6.22-71.0/bin/mysql_config

**Comment by dvankley** [comment]
Ditto, same error here as well.

    $ which mysql_config
    /usr/local/bin/mysql_config
    
    $ readlink /usr/local/bin/mysql_config
    ../Cellar/percona-server/5.6.21-69.0/bin/mysql_config

**Comment by arvenil** [comment]
@nijikon Hi Tomek ;p Did you solved that problem? :)

**Comment by nijikon** [comment]
@arvenil Nope, I might find some time on sunday.

**Comment by arvenil** [comment]
As a workaround `brew unlink percona-server; brew link mysql`

**Comment by tdsmith** [comment]
cf #41595

**Comment by tdsmith** [comment]
@nijikon Is this reproducible, do you think, or should we close it for now?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
