### ISSUE TITLE
pypy may not build on xcode-only systems

### ISSUE THREAD

**Issue by ikorin** [Homebrew/legacy-homebrew#36709]
I was trying to upgrade pypy to the latest version:

➜ Downloads brew upgrade pypy
==> Upgrading 1 outdated package, with result:
pypy 2.5.0
==> Upgrading pypy
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/pypy-2.5.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/pypy-2.5.0.yosemite.bottle.tar.gz
Error: SHA1 mismatch
Expected: 54b80dd6f11ba20f01223473ec195d8a8b6afc6c
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/pypy-2.5.0.yosemite.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.0-src.tar.bz2
Already downloaded: /Library/Caches/Homebrew/pypy-2.5.0.tar.bz2
==> Downloading https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.0-osx64.tar.bz2
Already downloaded: /Library/Caches/Homebrew/pypy--bootstrap-64.tar.bz2
==> /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/bootstrap/bin/pypy /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/rpython/bin/rpython -Ojit --shared --cc clang --verbose --make-jobs 8 targe
  File "/private/tmp/pypy-MxMGsX/pypy-2.5.0-src/bootstrap/lib-python/2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "/private/tmp/pypy-MxMGsX/pypy-2.5.0-src/rpython/translator/tool/pdbplus.py", line 29, in preloop
    raise NoTTY("Cannot start the debugger when stdout is captured.")
NoTTY: Cannot start the debugger when stdout is captured.

READ THIS: http://git.io/brew-troubleshooting

**Comment by mistydemeo** [comment]
> READ THIS: http://git.io/brew-troubleshooting

Can you read this and provide the requested diagnostic output, please? Tanks!

**Comment by ikorin** [comment]
https://gist.github.com/99c391a6111ba9824133

**Comment by tdsmith** [comment]
The problem is that it's failing to find ffi.h in the Xcode sysroot.

The failing compiler invocation is:
```
clang called with: -c -arch x86_64 -O3 -fomit-frame-pointer -mmacosx-version-min=10.5 -mdynamic-no-pic -I/usr/include/ffi /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/usession-release-2.5.x-0/platcheck_31.c -o /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/usession-release-2.5.x-0/platcheck_31.o
superenv executed: clang -c -arch x86_64 -O3 -fomit-frame-pointer -mmacosx-version-min=10.5 -mdynamic-no-pic -I/usr/include/ffi /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/usession-release-2.5.x-0/platcheck_31.c -o /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/usession-release-2.5.x-0/platcheck_31.o -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -isystem/usr/local/include -isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/apache2 -isystem/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/openssl/include
```

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/local/ffi/ffi.h` exists.

A workaround is to install the Xcode Command Line Tools with `xcode-select --install`.

**Comment by ikorin** [comment]
> A workaround is to install the Xcode Command Line Tools with xcode-select --install

Thank you that fixed the issue.

**Comment by tdsmith** [comment]
Adding `-iwithsysroot /usr/include/ffi` to `CFLAGS` in the formula can probably work.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
