### ISSUE TITLE
"___ is not in your PATH" warnings do not always work

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/legacy-homebrew#37040]
I don't have `HOMEBREW_PREFIX/sbin` in my path. If I install something that places an executable in `sbin`, and `HOMEBREW_PREFIX/sbin` doesn't exist, I won't see the "sbin is not in your PATH warning".

This is because we check for the existence of the top level directory here:

https://github.com/Homebrew/homebrew/blob/74a7538cc63630bdf707a1e0b736dc940a10fa6e/Library/Homebrew/formula_cellar_checks.rb#L8

and this check runs before linking happens.

If I then install another package that places something in `sbin`, I *will* see the warning, since the top-level directory was created when linking the previous package.

**Comment by tdsmith** [comment]
Hm, is this check only printed as a caveat if HOMEBREW_DEVELOPER is set? https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_installer.rb#L374

**Comment by DomT4** [comment]
What's the argument against doing something like [this block](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_installer.rb#L558-L568) for ` sbin ` as well?

**Comment by apjanke** [comment]
Can we just roll this in to the #38778 discussion, since this probably only applies specifically to `sbin`, and the other issue is more topic-specific and easy to find via searching or browsing? One less issue in legacy-homebrew to deal with.

**Comment by mikemcquaid** [comment]
@apjanke Yes.
