### ISSUE TITLE
Cannot install stable version of formula when devel or HEAD is installed.

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/legacy-homebrew#37091]
After installing a formula (wine) with `--devel`, I want to unlink it and install the stable version, but this fails:
```sh
brew install wine
Warning: wine-1.7.37 already installed, it's just not linked
brew install wine --stable
Warning: wine-1.7.37 already installed, it's just not linked
```

It seems that it is (unjustifiably) impossible to install the stable version when the devel is already installed. Since this apparently isn't the default behavior, a flag `--stable` should be added to `brew install` to force it to consider the stable version.

**Comment by jacknagel** [comment]
`--stable` is the default, so adding a flag for that won't change the behavior here.

The specific check that you are encountering happens here: https://github.com/Homebrew/homebrew/blob/398c405eb6f41df236e69ca207cf3124648a3e8f/Library/Homebrew/cmd/install.rb#L73-79

It's possible that this could be relaxed, but as with any change to the CLI behavior, I am concerned about scripts that may rely on this behavior, intentional or otherwise.

**Comment by alexchandel** [comment]
We could ask around. But I'm looking for some possible mechanism to install a different version of a formula, despite having some other version installed.

**Comment by asparagui** [comment]
@alexchandel You can do

    brew unlink wine

and then install the primary version (without deleting your old files).  If you're looking for something more, it's probably outside of the scope of what we can help you with, sorry.

**Comment by alexchandel** [comment]
@asparagui actually, you can't do that and succeed. If you read my error, you'll see homebrew is complaining that wine is still installed even though it's unlinked.

**Comment by asparagui** [comment]
@alexchandel Fair enough.  Why do you need this use case?

**Comment by alexchandel** [comment]
@asparagui I had just built `wine --devel` from source (a slow process, no fun :P), but I realized I needed to switch to stable wine for a few things. I'd rather not delete my entire build and install a bottle, shortly thereafter to rebuild `wine --devel` all over again, but that's what I have to do currently.

And it's so perplexing because Homebrew even lets you have *multiple* versions of a package so long as only one is linked; you would think this naturally follows.

**Comment by alexchandel** [comment]
Anyone know how to do this?

**Comment by chdiza** [comment]
> I'd rather not delete my entire build

You don't have to *delete* your entire `wine --devel` build.  You can just move the keg out of the way temporarily, then put it back when you're done with the stable bottle.  This should at least allow you to limp along until the issue is fixed.

**Comment by staticfloat** [comment]
I've noticed that this also makes it so that you cannot install the `HEAD` version of a formula at the same time as stable; this is a change from the previous behavior in which you could `unlink` a stable formula, install the `HEAD` version, and then `brew switch` between the two to your hearts content.

Is there a way to force-bypass the check?  Something like `brew install --force` or similar?  We use this a fair bit with Julia (see [issue here](https://github.com/staticfloat/homebrew-julia/pull/165#issuecomment-130609824)) to have both the stable version of Julia (0.3.X) and the development version (0.4.X) within easy reach.

**Comment by rkalnins** [comment]
I agree with @staticfloat, the change where `HEAD` version cannot be installed along with the stable version makes `brew switch` pretty much obsolete. My use case is that I use `drush` stable (version `7.0.0`) for Drupal 7 development and `HEAD` version for Drupal 8 development, and switching between the two with `brew switch` was the best thing after ice cream. Trying to run `brew install drush --HEAD` now ends with the `Warning: homebrew/php/drush-7.0.0 already installed, it's just not linked` message.

**Comment by Gurpartap** [comment]
```sh
$ brew unlink postgresql 
Unlinking /usr/local/Cellar/postgresql/9.4.5_2... 365 symlinks removed

$ brew install postgresql --devel
Warning: postgresql-9.4.5_2 already installed, it's just not linked
```

##### Workaround:

###### Make sure currently installed version is unlinked.
```sh
$ psql --version
psql (PostgreSQL) 9.4.4

$ brew unlink postgresql 
Unlinking /usr/local/Cellar/postgresql/9.4.5_2... 365 symlinks removed
```

--

###### Move the keg out of the way, install the desired version and put the keg back in place. 
```sh
$ mv /usr/local/Cellar/postgresql/9.4.5_2 \
     /usr/local/Cellar/postgresql/9.4.5_2-Be-Right-Back # 🙈

$ brew install postgresql --devel
==> Downloading https://ftp.postgresql.org/pub/source/v9.5beta2/postgresql-9.5beta2.tar.bz2
...

$ mv /usr/local/Cellar/postgresql/9.4.5_2-Be-Right-Back \
     /usr/local/Cellar/postgresql/9.4.5_2
```

--

###### Switch between the versions:
```sh
$ brew switch postgresql 9.4.5_2
Cleaning /usr/local/Cellar/postgresql/9.4.5_2
Cleaning /usr/local/Cellar/postgresql/9.5beta2_2
364 links created for /usr/local/Cellar/postgresql/9.4.5_2

$ psql --version
psql (PostgreSQL) 9.4.5
```
```sh                                                                                                              
brew switch postgresql 9.5beta2_2
Cleaning /usr/local/Cellar/postgresql/9.4.5_2
Cleaning /usr/local/Cellar/postgresql/9.5beta2_2
372 links created for /usr/local/Cellar/postgresql/9.5beta2_2

$ psql --version
psql (PostgreSQL) 9.5beta2
```

Thank @chdiza for the tip!

**Comment by alexchandel** [comment]
@jacknagel Is the workaround scary enough to merit a `--stable`?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
