### ISSUE TITLE
build.head? and build.stable? are nil in post_install

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/legacy-homebrew#37120]
Installing https://gist.github.com/tdsmith/6874a904b8d7c2b0debd/raw --HEAD, the debug ohai in the xy method shows that `build.head?` and `build.stable?` are nil when post_install is run.

This looks like the sequel to #36335, which should have been fixed by c7a9d32c69b805b1ac5d8f2e3cf7479e3639b3d2.

**Comment by jacknagel** [comment]
Can you test something for me: instead of using `build.head?`/`build.stable?`, use `head?` and `stable?` and confirm that they give the expected result.

**Comment by tdsmith** [comment]
Yes, `head?` and `stable?` look right.

**Comment by jacknagel** [comment]
Thanks, I will look at it this evening.

**Comment by jacknagel** [comment]
I'm hoping that in the short to medium term we can shift towards using `head?`, `devel?` and `stable?` over their `build._?` counterparts. So while I can make `build.head?` and friends work correctly in `post_install`, I'm wondering if it's worth the trouble.

From an implementation standpoint, this is one of the last places where we are still passing around this information as strings. It doesn't make sense to keep doing this when the information is already implicit in the formula object itself. In other words, the formula object already _knows_ if it is a head build or not, so why are we asking some other object?

I also think it promotes a healthy distinction between what can be used in the class body (the declarative `stable`, `devel`, and `head` DSL methods) and at the instance level (`stable?` `devel?`, and `head?` methods). The latter will never be part of the DSL, so calling them will raise an exception. This is a luxury we do not have with `build.head?` &c., which make it appear that the same API is available in both contexts, when in reality we know that it's not, and that using it that way can produce incorrect results.

**Comment by tdsmith** [comment]
I didn't know it was kosher to use the other methods. This makes sense now. I think this distinction is probably not obvious to most formula authors but I'm happy with wontfix. I guess we should keep an eye out for `build.head?` in `install` then?

**Comment by jacknagel** [comment]
Yeah, I only added these methods recently, because implementation changes only recently made them possible. I had planned to start pushing for their use eventually.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
