### ISSUE TITLE
qscintilla2 doesn't support pyqt5 (only pyqt4?)

### ISSUE THREAD

**Issue by patrickkidd** [Homebrew/legacy-homebrew#37591]
I'm no homebrew expert, but is there a way to get qscintilla2 to build with pyqt5? As it stands it only builds with pyqt(4).

I tried changing the python version and pyqt version in the brew file, and it seems to install pyqt5 correctly (although forces a re-install) into python3 but then installs qscintilla2 into python2 and linking to Qt4.

Thoughts? Thanks!

**Comment by xavriley** [comment]
If you only need qscintilla 2.8.4 without all the Python deps then I managed to hack something together here

`brew install https://gist.githubusercontent.com/xavriley/988439eb2e9f438944c8/raw/cf0dec1078fb8aa09a4c2d599f792f4a4b6b4349/qscintilla284.rb`

Obviously anyone looking at that should check it over before installing. 

I'd like to fix the formula properly to allow newer versions of qscintilla with Python though, when I have more time

**Comment by ZemingLiu** [comment]
OS:fedora 21
PyQt5, qscintilla 2.8.4
when I run program designer-qt5 program exits with error:
````
designer-qt5: symbol lookup error: /usr/lib/qt5/plugins/designer/libqscintillaplugin.so: undefined symbol: _ZN13QsciScintillaC1EP7QWidget

**Comment by louis-web** [comment]
```
bogon:eric6-6.0.7 louis$ brew install QScintilla2 --with-python3
==> Installing qscintilla2 dependency: pyqt
==> Downloading https://downloads.sf.net/project/pyqt/PyQt4/PyQt-4.11.3/PyQt-mac
==> Downloading from http://nchc.dl.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11
######################################################################## 100.0%
==> python configure.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.11.3
==> python configure-ng.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.1
==> make
==> make install
==> make clean
==> python3 configure.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.11.
==> python3 configure-ng.py --confirm-license --bindir=/usr/local/Cellar/pyqt/4.
==> make
==> make install
==> make clean
==> Caveats
Phonon support is broken.

==> Summary
🍺  /usr/local/Cellar/pyqt/4.11.3: 617 files, 34M, built in 7.9 minutes
==> Installing qscintilla2
==> Downloading https://downloads.sf.net/project/pyqt/QScintilla2/QScintilla-2.8
######################################################################## 100.0%
==> qmake qscintilla.pro -config release -spec unsupported/macx-clang-libc++
==> make
==> make install
==> python configure.py -o /usr/local/Cellar/qscintilla2/2.8.4/lib -n /usr/local
==> make
/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers/qobject.h:290:44: note: passing argument to parameter 'signal' here
    virtual void connectNotify(const char *signal);
                                           ^
2 errors generated.
make: *** [sipQsciQsciLexerBatch.o] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
qscintilla2 doesn't support pyqt5 (only pyqt4?) https://github.com/Homebrew/homebrew/issues/37591
qscintilla2 fails to build on 10.11: sip files generating qt5 API, but only qt4 installed https://github.com/Homebrew/homebrew/issues/41464
bogon:eric6-6.0.7 louis$ brew list
cmake			openssl			ruby21
gdbm			pcre			saltstack
libffi			pkg-config		sip
libimobiledevice	pyqt			sqlite
libplist		pyqt5			swig304
libtasn1		python			usbmuxd
libusb			python3			xz
libxml2			qt			zeromq
libyaml			qt5
makedepend		readline
bogon:eric6-6.0.7 louis$ brew install QScintilla2 --with-python3
==> Downloading https://downloads.sf.net/project/pyqt/QScintilla2/QScintilla-2.8
Already downloaded: /Library/Caches/Homebrew/qscintilla2-2.8.4.tar.gz
==> qmake qscintilla.pro -config release -spec unsupported/macx-clang-libc++
==> make
==> make install
==> python configure.py -o /usr/local/Cellar/qscintilla2/2.8.4/lib -n /usr/local
==> make
                                           ^
2 errors generated.
2 errors generated.
make: *** [sipQsciQsciLexerBatch.o] Error 1
make: *** [sipQsciQsciLexerBash.o] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
qscintilla2 doesn't support pyqt5 (only pyqt4?) https://github.com/Homebrew/homebrew/issues/37591
qscintilla2 fails to build on 10.11: sip files generating qt5 API, but only qt4 installed https://github.com/Homebrew/homebrew/issues/41464
bogon:eric6-6.0.7 louis$ 
```

**Comment by dunn** [comment]
If anyone can get qscintilla2 to build with pyqt5, we'd love a pull request!

**Comment by inglesp** [comment]
Having installed PyQt5 via brew, I was able to install qscintilla2 by downloading and unpacking https://downloads.sf.net/project/pyqt/QScintilla2/QScintilla-2.8.4/QScintilla-gpl-2.8.4.tar.gz.

Then, in the `Qt4Qt5` directory, I ran:

    /usr/local/Cellar/qt5/5.5.1/bin/qmake qscintilla.pro
    make
    make install

Then, from the `Python` directory, I ran:

    python3 configure.py --verbose --pyqt=PyQt5 --qsci-incdir=/usr/local/Cellar/qt5/5.5.1/include --qsci-libdir=/usr/local/Cellar/qt5/5.5.1/lib --qmake /usr/local/Cellar/qt5/5.5.1/bin/qmake --sip-incdir /usr/local/Cellar/sip/4.16.9/include --pyqt-sipdir=/usr/local/Cellar/pyqt5/5.5.1/share/sip/Qt5
    make
    make install

Does this look like enough information to produce a brew formula?

**Comment by dunn** [comment]
Give it a try! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you run into any problems!

**Comment by inglesp** [comment]
I've had a crack at this, but am being held up by having to install pyqt5 every time I try to test the new formula, even though it's already installed.

I'm sure I'm doing something wrong, but I'm not sure what!

Having made some tweaks to `Library/Formula/qscintilla2.rb`, when I run `brew info qscintilla2`, it shows that pyqt5 is installed:

```
$ brew info qscintilla2
qscintilla2: stable 2.8.4 (bottled)
Port to Qt of the Scintilla editing component
https://www.riverbankcomputing.com/software/qscintilla/intro
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/qscintilla2.rb
==> Dependencies
Required: pyqt5 ✔
==> Options
--with-python3
	Build with python3 support
--without-plugin
	Skip building the Qt Designer plugin
--without-python
	Build without python support
```

But when I try to install qscintilla2 from the new formula, it begins by installing pyqt5, which takes twenty minutes:

```
$ brew install qscintilla2 --with-python3
==> Installing dependencies for qscintilla2: pyqt5
==> Installing qscintilla2 dependency: pyqt5
==> Downloading https://downloads.sourceforge.net/project/pyqt/PyQt5/PyQt-5.5.1/PyQt-gpl-5.5.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/pyqt5-5.5.1.tar.gz
==> python3 configure.py --confirm-license --bindir=/usr/local/Cellar/pyqt5/5.5.1/bin --destdir=/usr/local/Cellar/pyqt5/5.5.1/lib/python3.5/site-packages --sipdir=/usr/local/Cellar/pyqt5/5.5.1/share/sip/Q
==> make
==> make install
==> make clean
🍺  /usr/local/Cellar/pyqt5/5.5.1: 791 files, 24M, built in 17.3 minutes
...and now we start to install qscintilla2
```

Why does brew think that it needs to install pyqt5 again?

**Comment by dunn** [comment]
One guess is that the branch you're editing the formula on has fallen behind `master`, so the version of PyQt5 is newer than brew expects.

**Comment by inglesp** [comment]
@dunn, thanks for the suggestion.  I've made sure I'm up to date with `master`, but I'm still seeing the problem.

**Comment by dunn** [comment]
Oh, it's probably because your PyQt isn't built `--with-python3`:
```ruby
  if build.with? "python3"
    depends_on "pyqt" => "with-python3"
  else
    depends_on "pyqt"
  end

**Comment by inglesp** [comment]
That's helped to identify the problem.  The `pyqt5` formula doesn't have a `--with-python3` option (it has `--with-python` and `--without-python3` instead, which a bit weird...) so changing the `qscintilla2` formula to:

```
  if build.with? "python3"
    depends_on "pyqt5"
  else
    depends_on "pyqt5" => "without-python3"
  end
```

helps me make progress.  (I'll come back to whether this is the Right Thing to do once I've got *something* working!)

Thanks @dunn for your help!

**Comment by inglesp** [comment]
Given that there are separate brew formulae for qt4 and qt5, and that somebody might want to build qscintilla2 against both qt4 and qt5, I think I'm going to need to produce a new formula for building qscintilla2 against qt5, instead of modifying the existing qscintilla2 formula (which currently builds against qt4).

Two questions:
1) is that a correct assumption?
2) what should I call the new formula?  Is qscintilla2-qt5 acceptable?

**Comment by dunn** [comment]
I'd much rather have it stay in one formula.  What are the problems you came across that would be solved by a `qscintilla2-qt5` formula?

**Comment by inglesp** [comment]
I had thought (and maybe I'm wrong) that you can't install the same formula multiple times, which would prevent you from building qscintilla2 against qt4 and qt5.  Is that correct?

**Comment by mikemcquaid** [comment]
That's true. Why would you want to do that?

**Comment by inglesp** [comment]
You'd want to do it for the same reason that you'd want qt4 and qt5: some applications depend on qt4, and others depend on qt5.

**Comment by mikemcquaid** [comment]
Do you personally need it for both at once?

**Comment by inglesp** [comment]
No, I don't.

**Comment by mikemcquaid** [comment]
I think it's worth just leaving it in the same formula until there's a few folks that need that.

**Comment by inglesp** [comment]
I'm happy to go with whatever the maintainers decide, but I'd like to argue that we go beyond YAGNI in this particular case, for a handful of reasons:

 * A quick straw poll on IRC suggests it's not that unusual for people to be developing different projects with both qt4 and qt5, so even though I don't need qscintilla2 for both now, it's not unreasonable to imagine that I might in the future.  (Evidence against this comes in the form of this issue having been open for almost a year!)
 * Once we go down the route of supporting building qscintilla2 against both qt4 and qt5, I assume we'd have to continue supporting that forever.
 * The implementation of the two formulae are pretty different, so there's very little gain to be had (implementation-wise) from keeping them in the same formula.

How does a decision like this get made in the homebrew project?

**Comment by mikemcquaid** [comment]
> even though I don't need qscintilla2 for both now, it's not unreasonable to imagine that I might in the future

That's classic YAGNI, I'm afraid. Particularly when it's easy to change our minds in the future: let's not overengineer now.

> Once we go down the route of supporting building qscintilla2 against both qt4 and qt5, I assume we'd have to continue supporting that forever.

Nope, we could stop supporting one in future or switch defaults if we ever remove Qt4.

> The implementation of the two formulae are pretty different, so there's very little gain to be had (implementation-wise) from keeping them in the same formula.

However, they are the same upstream software source built with different options, right? That argues pretty strongly for a single formula, if it's true.

> How does a decision like this get made in the homebrew project?

Maintainers who care (e.g. me) express views on issues and we decide based on that. People who care (e.g. you) submit a pull request which gets discussed, edited and pulled.

**Comment by patrickkidd** [comment]
I am not familiar enough with brew to cast a vote in either direction of single or multiple formula. But as an experienced qt and pyqt developer at the professional level, I will suggest that it is indeed very common to use multiple installations of many versions of qt, and subsequently pyqt

I hope that helps. I’m looking forward to a pyqt5 formula that works with qscintilla2!

**Comment by xavriley** [comment]
+1 for common use case of mixing qt4 and qt5

**Comment by tdsmith** [comment]
FYI: Qt 4 is EOL and tends to break on OS X upgrade so it is possible-to-likely that we will not support Qt 4 on upcoming releases of OS X.

**Comment by patrickkidd** [comment]
Sorry if I'm having a little trouble following the thread exactly, but did any of you intelligent folks arrive at a way to install a python3/pyqt5/qscintilla2 stack, regardless of whether it also supports qt4? I've been out of the loop a while here...

Thank you so much!

**Comment by inglesp** [comment]
Hi @patrickkidd -- I'm afraid I haven't had the time to integrate this into the main homebrew repo, but I did manage to use [this formula](https://github.com/ntoll/mu/blob/master/package/extras/qscintilla2.rb) for getting python3/pyqt5/qscintilla2 to play nicely together.  I hope you find it useful!

**Comment by mikemcquaid** [comment]
I'm closing this out as it's a feature request and we'll need someone interested (i.e. not a current maintainer) to step in and submit a pull request to implement this.

**Comment by patrickkidd** [comment]
@ingelsp, Thanks for your formula. It looks like your formula coves all the important bases, but I haven't used a custom formula before. I'm having trouble finding out form the homebrew docs if there is a way to use a brew form a specific file. The instructions I've found seem a little complicated with git repos, etc. Is there an easy way to use and edit the custom formula? A doc, perhaps? Thanks!

**Comment by inglesp** [comment]
@patrickkidd You can download the file to somewhere on your system, and run `brew install /path/to/qscintilla2.rb`.  I'm not sure where this is documented though!

**Comment by patrickkidd** [comment]
@inglesp Thanks for the reply, I tried that but got an error. But at least I know where to look now. Thanks again for the formula! If I get familiar with this enough I'll put in a pull request.
