### ISSUE TITLE
emacs can be linked against XQuartz or Brew font-config

### ISSUE THREAD

**Issue by drizt** [Homebrew/legacy-homebrew#37803]
When I install emacs with `--with-x11` option. It links against brew fontconfig if installed. If no then against XQuartz fontconfig. The first case is not desirable for me. It make my font looks ugly. looks at screenshots.

1. XQuartz fontconfig. Default font.
http://i.snag.gy/aSX9T.jpg
2. Brew fontconfig. Default font.
http://i.snag.gy/GAolM.jpg
3. XQuartz fontconfig. My font.
http://i.snag.gy/RLC8g.jpg
4. Brew fontconfig. My font.
http://i.snag.gy/FlLCE.jpg

My font is 

    '(default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :family "urw-nimbus mono l"))))

I think emacs should always use XQuartz fontconfig. If not brew **must** explicy warns about this. Such behaviour is not obviously and not documented. I spend all day to find the problem. It's not good.

**Comment by adamv** [comment]
Thanks for the report; we try not to have "hidden" dependencies in a formula like this.

**Comment by DomT4** [comment]
Yup.

```
otool -L /usr/local/opt/emacs/bin/* | grep fontconfig:
	/usr/local/lib/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/local/lib/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/local/lib/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/local/lib/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/local/lib/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
```

Configure:
```
checking for fontconfig >= 2.2.0... yes CFLAGS='-I/opt/X11/include -I/opt/X11/include/freetype2 ' LIBS='-L/opt/X11/lib -lfontconfig -lfreetype '
```

But that isn't being passed to the ` make ` stage:

Make:
```
LDFLAGS='-lfreetype -lfontconfig ' MAKE='/Applications/Xcode.app/Contents/Developer/usr/bin/make'
```

But sadly, even *when* we pass it to ` make ` by tweaking the ` LDFLAG ` to read ` ENV.append "LDFLAGS", "-L#{MacOS::X11.lib} -lfreetype -lfontconfig" `... We get the same otool linkage to Homebrew's fontconfig.

Make:
```
LDFLAGS='-L/opt/X11/lib -lfreetype -lfontconfig ' MAKE='/Applications/Xcode.app/Contents/Developer/usr/bin/make'
```

Fun.

**Comment by DomT4** [comment]
Interestingly, if you do:

```ruby
      if build.with? "x11"
        system "make", "LDFLAGS='-L#{MacOS::X11.lib} -lfreetype -lfontconfig'"
        system "make", "install", "LDFLAGS='-L#{MacOS::X11.lib} -lfreetype -lfontconfig'"
      else
        system "make"
        system "make", "install"
      end
```

The number of ` otool ` links to ` HOMEBREW_PREFIX/lib/libfontconfig.1.dylib ` drops from 5 to 2. Very strange. Maybe we could just ` keg_only ` fontconfig... Not a huge amount uses it.

**Comment by DomT4** [comment]
Fix under discussion in #37829. May well change depending on feedback/practically, but feel free to keep tabs on the PR as desired.

**Comment by jacknagel** [comment]
As I noted in https://github.com/Homebrew/homebrew/pull/37829#issuecomment-83237715, we made a policy choice to always use Homebrew versions of libraries like fontconfig, even when XQuartz is installed.

Since emacs is not a library, we could relax that here, but the fix would need to be scoped to just this formula.

Alternatively, we can figure out why Homebrew's fontconfig produces a different result and fix it.

**Comment by mikemcquaid** [comment]
In the short-term I think it'd be worth just adding `:recommended` dependencies for these and, as @jacknagel says, work out what's going on with our `fontconfig`.

**Comment by DomT4** [comment]
> In the short-term I think it'd be worth just adding :recommended dependencies for these 

For the whole formula, or just when built with the ` x11 ` element?

**Comment by mikemcquaid** [comment]
Just with `x11`.

**Comment by DomT4** [comment]
Want a PR?

**Comment by mikemcquaid** [comment]
:+1:

**Comment by DomT4** [comment]
#37861

**Comment by DomT4** [comment]
Turns out I've ran into this ` fontconfig ` font-display problem before, but had forgotten about it. Fontforge ships with theme files, but despite using the same files and the same X11 GUI, Fontforge's OS X binary's font looks significantly different to the Brewed Fontforge font. This is the issue where it's discussed. Brewed Fontconfig looks like the suspect there as well: https://github.com/fontforge/fontforge/issues/2083

**Comment by tdsmith** [comment]
@DomT4 @dunn either of you still have feelings about this?

**Comment by dunn** [comment]
Not really.  At one point I thought about proposing to kill off the X11 option entirely, but that might be going too far.  (I did look into replacing it with the GTK+ option but that requires a GTK+3 built with the X11 so boo.)

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/issues/1616.
