### ISSUE TITLE
gist-logs gives 404 when token has no gist right

### ISSUE THREAD

**Issue by mantognini** [Homebrew/legacy-homebrew#39864]
Hi,

Having an issue building `llvm` I tried `$ brew gist-logs llvm` but the only thing I got was

> Error: HTTP 404 Not Found (expected 201)

It took me a while to realise that I needed to add write access to gists for my homebrew token.

This should be mentioned in the documentation, especially on [the troubleshooting page](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting).

Also, there's nothing about `gist-logs` command in the `man`.

**Comment by sjackman** [comment]
To fix this error, go to https://github.com/settings/tokens
Select `edit` for your `HOMEBREW_GITHUB_API_TOKEN`
Enable the checkbox for `gist`
Select `Update token`

See also https://github.com/Linuxbrew/linuxbrew/issues/673
and https://github.com/Homebrew/homebrew/issues/42100

**Comment by sjackman** [comment]
A `brew login` feature similar to `gist login` would be great, or Homebrew could use the `gist` gem.

**Comment by MikeMcQuaid** [comment]
The error message has been improved for this.
