### ISSUE TITLE
uninstall doesn't check full keg path

### ISSUE THREAD

**Issue by wolfd** [Homebrew/legacy-homebrew#39883]
It doesn't seem to matter what you put into the uninstall command, it just ignores everything but the unqualified keg name.

```
$ brew uninstall arbitrary/whatever/fortune
Uninstalling /opt/boxen/homebrew/Cellar/fortune/9708... (116 files, 3.6M)
```

I feel like uninstall should at least require users to use --force (or some other option) if homebrew has no recollection of the keg.

**Comment by jacknagel** [comment]
We'll be able to make improvements to the UX here pending the work in #39524.
