### ISSUE TITLE
Zpython formula is using outdated repository

### ISSUE THREAD

**Issue by ZyX-I** [Homebrew/legacy-homebrew#40318]
Zpython in https://bitbucket.org/ZyX_I/zsh is no longer maintained. Since zsh developers officially refused to ever merge zpython module into zsh because it brings heavy dependency (Python obviously) it will also never be maintained in the future ([there were plans to create a script that creates a patch](https://bitbucket.org/ZyX_I/zpython/issue/2/add-a-script-that-converts-this-repository)). Now zpython lives in https://bitbucket.org/ZyX_I/zpython and is installed separately (needs zsh headers, described in README).

Also note: zpython module supports Python 2.6 till 3.4 (basically every version powerline does support). I do not know how brew covers this, but it is good idea to make user able to select needed version (at least, 2.7 vs 3.4). There is also an option to specify different command in place of `zpython`, but I never actually tried to use `zpython` and `zpython3` at the same time.

**Comment by mikemcquaid** [comment]
I guess this should probably be moved to homebrew-boneyard.

**Comment by ZyX-I** [comment]
I can’t comment this: am not using brew and Mac OS. If boneyard is something for dead packages then I can say that zpython is not dead, it just now is a separate project.

**Comment by mikemcquaid** [comment]
Ah, I see, thanks.

**Comment by rspeed** [comment]
I made a small effort to build Zpython manually using the directions at the new repo and ran into a few problems, so this might take some doing.

1. The build process requires a pair of files from zsh that are left out by `make install`. So in order to build zpython, zsh must first be built.

1. A script that is run during the build process breaks in OS X because it uses a syntax for `sed` that doesn't work in BSDs. That's easy enough to either patch or fix upstream.

1. Even after all that I couldn't get it to build successfully, but I plan to look into it again.

**Comment by DomT4** [comment]
I'm not really sure this is worthwhile fixing. Looking through the upstream README you have to do an awful lot of dancing just to get it to build.

Neither our `zsh` or the system default ship the headers it wants, so presumably we'd have to build a whole other `zsh` and install it somewhere, and embedding a whole shell into another formula is a bit ick.

Happy to see what you come up with on this, but the upstream README doesn't fill me with hope.

**Comment by rspeed** [comment]
To be fair, you don't have to keep that extra `zsh` build around.

**Comment by DomT4** [comment]
> If the Homebrew zsh package could be modified to retain those files post-install it could be used as a build requirement, which seems fairly reasonable to me.

I'm probably :-1: on installing headers just for another package when nothing else really uses them; there's no way to retain the `zsh` headers post-install without actually installing them. As far as I know, Debian/Ubuntu don't install the headers either.

**Comment by ZyX-I** [comment]
@DomT4 Debian/Ubuntu have zsh-dev package. Though since zpython is nearly the only “external” module the zsh-dev package does not contain *all* needed headers and I do not know why this package exists in such useless state. Relevant issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776964.

Gentoo (now) installs all the required headers (https://bugs.gentoo.org/show_bug.cgi?id=538684).

> I'm probably ￼ on installing headers just for another package when nothing else really uses them

Of course, nothing does. Writing external zsh modules cannot be popular if headers are provided by almost no packages. Also zsh already has a lot of features, so most of things can be written in zsh, sometimes using its modules.

**Comment by rspeed** [comment]
At this point I think the package should just be removed.

**Comment by ZyX-I** [comment]
Note that debian now also installs required headers.

**Comment by rspeed** [comment]
I just had an idea, but I'm not entirely sure if it's possible.

1. Modify the `zsh` formula to add a new option (which I'll call `--with-dev-headers`) that installs the headers
1. Add `zsh --with-dev-headers` as a build dependency for `zpython`

If so, it seems like that would take care of all of the issues. There's no extra cruft and zpython stops being broken.

**Comment by DomT4** [comment]
If Debian now installs a full set of headers _and_ the `zsh` headers are nested in a sensible way that aren't likely to cause linking issues I'll take a PR to include them.

**Comment by ZyX-I** [comment]
@DomT4 Both debian package and my ebuild do some preprocessing in order to make them nested in a sensible way. Formula will have to do the same thing.

**Comment by DomT4** [comment]
How much of a dance are we talking about? Do you have an example?

**Comment by ZyX-I** [comment]
@DomT4 It is in the debian bug report and also in my project README. Using sed since build scripts are using bash (Gentoo) or dash (debian).

**Comment by ZyX-I** [comment]
Two sed commands, applied to some of the installed headers:

```Shell
	for file in Src/{zsh.mdh,*.h} ; do
		sed -i 's@\.\./config\.h@config.h@' "$file"
		sed -i 's@#\(\s*\)include "\([^"]\+\)"@#\1include <zsh/\2>@' "$file"
	done
```

**Comment by ZyX-I** [comment]
Plus it is necessary to install `/Src/*.epro` and `/config.h` to the same location (`/usr/include/zsh`).

**Comment by rspeed** [comment]
The behavior of BSD and GNU `sed` differs in a way that breaks this on OS X. I got it working a few months ago, but I ended up tossing out the build. I *think* that script needs to be changed to this:

    for file in Src/{zsh.mdh,*.h} ; do
        sed -e 's@\.\./config\.h@config.h@' -i "$file"
        sed -e 's@#\(\s*\)include "\([^"]\+\)"@#\1include <zsh/\2>@' -i "$file"
    done

Though I imagine Ruby could do it without having to call `sed` at all.

**Comment by DomT4** [comment]
> Plus it is necessary to install /Src/*.epro and /config.h to the same location (/usr/include/zsh), untouched.

You can't install to `/usr/*` anything. You can install to `HOMEBREW_CELLAR/zsh/version/include/zsh` which will be linked into `/usr/local/include/zsh`. This is what the project would already be doing if the headers installed automatically.

> The behavior of BSD and GNU sed differs in a way that breaks this on OS X. 

If we have to use `gnu-sed` as a `:build` dependency it's not the end of the world. It would be nice to use Ruby rather than an external tool if possible though!

**Comment by ZyX-I** [comment]
> You can't install to /usr/* anything. You can install to HOMEBREW_CELLAR/zsh/version/include/zsh which will be linked into /usr/local/include/zsh. This is what the project would already be doing if the headers installed automatically.

This is not significant. Scripts assume that files will be installed to where compiler searches for “system” headers (`#include <…>`), disregarding the exact location.

> If we have to use gnu-sed as a :build dependency it's not the end of the world. It would be nice to use Ruby rather than an external tool if possible though!

Ruby has proper regex and file opening support, but I bet running sed instead will need less code. Though I am basing this on my Python and Perl experience.

**Comment by DomT4** [comment]
> Scripts assume that files will be installed to where compiler searches for “system” headers

Indeed. Just wanted to check given you specified `/usr/include` which isn't a place Homebrew operates.

> Ruby has proper regex and file opening support, but I bet running sed instead will need less code. 

Feel free to file a PR for review. It'll probably be easier to discuss reality than theory at this point.

**Comment by rspeed** [comment]
I suspect this use of `sed` could be easily replaced with Homebrew's [inreplace](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#inreplace) function.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
