### ISSUE TITLE
aspcud failed to build on 10.10

### ISSUE THREAD

**Issue by cp526** [Homebrew/legacy-homebrew#40401]
Trying to build aspcud on Yosemite fails with the error listed in the link below.

https://gist.github.com/anonymous/eb537877b15cd1e95067

I'm unsure about the CMAKE_OSX_SYSROOT variable it complains about: is that one of the things
configure should have come up with or something that should globally be set on my system but wasn't?

The CMakeOutput.log file mentioned in the error message didn't exist whenever I tried.

**Comment by DomT4** [comment]
I can't reproduce this with an `Xcode` installation. That's the only appropriate variable I can see here between us.

**Comment by cp526** [comment]
That's too bad :-) I guess the error message is not very helpful considering the logfile is empty, but that's all I have.

**Comment by mistydemeo** [comment]
I can repro on a CLT-only system.

**Comment by DomT4** [comment]
Probably wants a `depends_on :xcode => :build` dep then?

**Comment by mistydemeo** [comment]
Setting `CMAKE_OSX_SYSROOT` to `/` fixes it - judging from the callstack, this might be an issue with cmake rather than aspcud.

**Comment by jacknagel** [comment]
See https://github.com/Homebrew/homebrew/issues/29101

Why is stdenv being used here?

**Comment by leafac** [comment]
I can confirm the existence of this issue. I had only Command Line Tools (CLT) installed and tried to install opam (which depends on aspcud), which it failed. I then installed XCode from the App Store and tried again. This time it worked.

**Comment by mistydemeo** [comment]
> Why is stdenv being used here?

formula_installer chooses stdenv [if scons is located anywhere in the recursive dependency list](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_installer.rb#L442), and [gringo uses scons](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gringo.rb#L18).

**Comment by mistydemeo** [comment]
Scons has been forcing stdenv since pretty early on; this was introduced in 74bdd0472965c1af7f9da42ea7e2844f3caf850f, in 2012. Possibly this is no longer required.

**Comment by mistydemeo** [comment]
Testing just now, gringo definitely does not build under superenv. We can solve the immediate issue by only forcing stdenv if scons is an immediate dependency and not a recursive dependency, but in the long term we probably need to customize scons in order to get it playing nicely with superenv.

**Comment by mistydemeo** [comment]
While scons includes no builtin option to retain the outer environment, it's not too hard to do, and this does fix it under superenv:

```patch
diff --git a/engine/SCons/Platform/posix.py b/engine/SCons/Platform/posix.py
index 86c08b9..e439687 100644
--- a/engine/SCons/Platform/posix.py
+++ b/engine/SCons/Platform/posix.py
@@ -86,8 +86,9 @@ def generate(env):
     # Note that this means that 'escape' is no longer used
 
     if 'ENV' not in env:
-        env['ENV']        = {}
-    env['ENV']['PATH']    = '/usr/local/bin:/opt/bin:/bin:/usr/bin'
+        env['ENV']        = os.environ.copy()
+    else:
+        env['ENV'].update(os.environ)
     env['OBJPREFIX']      = ''
     env['OBJSUFFIX']      = '.o'
     env['SHOBJPREFIX']    = '$OBJPREFIX'
```

This obviously affects scons's behaviour in the general case, so we can't just ship this patch. I'm uncertain if they're interested in supporting out usecase, but I'll ask on their mailing list about making something akin to this an option.

**Comment by jacknagel** [comment]
I looked for a rationale for why we look at recursive dependencies rather than immediate dependencies but I couldn't find one. It's been this way since https://github.com/Homebrew/homebrew/commit/74bdd0472965c1af7f9da42ea7e2844f3caf850f

But it seems like we could relax that.

I do agree that ultimately we need to fix scons here. There are a number of other places where superenv would otherwise resolve issues.

I experimented with this patch: https://gist.github.com/jacknagel/dc23e31d2d37d533d6ac a while back but I wasn't motivated enough to go anywhere with it.

**Comment by ilovezfs** [comment]
This is reproducible on OS X El Capitan 10.11.3 with CLT && no Xcode.app:
https://gist.github.com/9f486603c9920a9e1158

**Comment by DomT4** [comment]
Does passing:
```ruby
"-DCMAKE_OSX_SYSROOT=#{MacOS.sdk_path}"
```
To cmake as part of the arguments resolve the issue for this formula in that configuration? We've had to set that in a couple places (discovered so far) now, although stdenv wasn't an issue for those.

It's a bit of a workaround but we haven't picked up and ran with the Scons issue further yet. Don't know if Misty heard back from them in the end.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
