### ISSUE TITLE
apple-gcc42 takes priority over modern gcc

### ISSUE THREAD

**Issue by yesimon** [Homebrew/legacy-homebrew#41055]
When installing a formula that has a `needs :openmp` section, my compiler selection falls back to gcc-4.2 leading to various errors. 

Normal brew config:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: e0db473dee9a2b42bc96b8b7dddbc4655d596483
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit sandybridge
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
GCC-4.2: build 5666
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Users/simon/.pyenv/shims/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
Java: 1.8.0_31
```

But when running: 
`simon@nitrogen /u/l/L/Formula> brew gist-logs fftw --with-openmp -v`
https://gist.github.com/e6514d6f5aa7a0d2e826

Whereas installing without openmp works fine, even when building from source. This also occurs with other `needs :openmp` formula.

**Comment by tdsmith** [comment]
If you install a current gcc (with e.g. `brew install gcc`), Homebrew should prefer it to gcc-4.2. The `needs :openmp` directive blacklists compilers without openmp support; Homebrew slides down a priority list until it finds a matching compiler.

**Comment by yesimon** [comment]
I have gcc-5.1.0 installed from bottle, which should support it right?

**Comment by tdsmith** [comment]
Hmm, it should; that may be a bug. Adding `--cc=gcc-5` will force the issue.

**Comment by yesimon** [comment]
Yes adding `--cc` fixes it.

**Comment by jacknagel** [comment]
All Apple compilers are ahead of GNU gcc in the list: https://github.com/Homebrew/homebrew/blob/a7a1cb25c32e2b0661347d0c20eaa42198c20e92/Library/Homebrew/compilers.rb#L84

At the time this was done because Apple compilers have some advantages (e.g. they can produce universal binaries) over GNU compilers.

Maybe we should blacklist gcc-4.2 for openmp. I don't really see a reason for anyone to have it installed on 10.8+, though, clang is a superior choice in most cases.

**Comment by yesimon** [comment]
Yes I have a `/usr/local/opt/apple-gcc42/` directory, probably from this computer upgrading all the way from Lion OS X 10.7. Is this a homebrew directory and should I delete it?

**Comment by tdsmith** [comment]
There is a homebrew/dupes/apple-gcc42 formula you might have installed; you can remove it with `brew rm apple-gcc42`.

**Comment by tdsmith** [comment]
Thanks for the explanation, Jack. I think the current behavior seems reasonable.

**Comment by jacknagel** [comment]
Maybe we should be recommending that people uninstall apple-gcc42, via a doctor check or some other means?

I see it a lot in `brew --config` output, and I suspect it is usually left over from the 10.6/10.7 transition when the compiler situation was still in flux, rather than a conscious choice on the user's part.

**Comment by mikemcquaid** [comment]
Seems like a good idea. I wonder at what point we want to basically get (Homebrew) compiler selection down to just GCC5 and Clang? At this point it seems everything compiles with one of those two and I'm under the impression that it's the same on Tigerbrew too. It'd certainly make 10.8 compilation more reliable once we drop CI if we just defaulted to GCC there.

**Comment by yesimon** [comment]
Things work as expected after uninstalling apple-gcc42. I don't ever remember manually installing it though. With openmp support coming to clang, this might be a nonissue in the future. I still think it's a good idea to recommend removing apple-gcc42.  I didn't even realize it was installed, especially since it's prefixed with apple.

**Comment by mistydemeo** [comment]
> I'm under the impression that it's the same on Tigerbrew too

The only real use for it in Tigerbrew is bootstrapping newer compilers on Tiger, where gcc-4.0 is too old. It's easy for me to scope some special handling to Tiger only.

The main uses I see for gcc-4.2 at this point are:

* Users on the slim number of platforms where the only available clang has issues, and gcc-4.2 isn't shipped with Xcode; not many people there anymore.
* Users building Mac software that uses ObjC-GC, which is not supported in recent clang and was never supported in FSF GCC.

There is some software that can't be built with GCC 5 and can be with older FSF GCCs from homebrew/versions; I think there's an argument for retaining compatibility for using those compilers. That software is not generally in Homebrew but users may be distributing it in taps.

**Comment by mikemcquaid** [comment]
@mistydemeo I'm :+1: on allowing stuff to fall back to any/all of those compilers I guess I'm just wondering about changing the default prioritisation so GCC (5) is the default on 10.8 (and perhaps below to whatever version you think makes sense)?

**Comment by VSsmall** [comment]
How to solve this problem?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
