### ISSUE TITLE
orfeo fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/legacy-homebrew#41275]
I installed *all* formulae from the core, this is one of the issues I ran into. I’m at work, will check tonight.

```
$ brew install orfeo
==> Installing orfeo dependency: fltk
…
==> Installing orfeo
==> Downloading https://downloads.sourceforge.net/project/orfeo-toolbox/OTB/OTB-3.20/OTB-3.20.0.tgz
==> Downloading from http://garr.dl.sourceforge.net/project/orfeo-toolbox/OTB/OTB-3.20/OTB-3.20.0.tg
######################################################################## 100,0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/C


-- Configuring incomplete, errors occurred!
See also "/tmp/orfeo20150702-90834-kirmxa/OTB-3.20.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/orfeo20150702-90834-kirmxa/OTB-3.20.0/build/CMakeFiles/CMakeError.log".

READ THIS: https://git.io/brew-troubleshooting
```

Logs: https://gist.github.com/ae22be1a75f621cfc46d

**Comment by rduca** [comment]
I am new on Orfeo toolbox and I am having the same problem on building the installation in my MacOs Maveric. Could you explain which is the solution?

**Comment by bfontaine** [comment]
@rduca I don’t know. I have a beginning of a fix in #41363 but I’m not done.

**Comment by grizonnetm** [comment]
I am not familiar with homebrew but I don't get why the formula try to download OTB 3.20. I was thinking that there were formulae available for OTB 4.X and also perhaps for 5.0.

By the way, there is no more dependency to fltk in OTB 4.x or 5.x

**Comment by rduca** [comment]
Do you know how to modify the formula and making it fetching the right packages?

**Comment by bfontaine** [comment]
#41363 updates it to 5.0 but it doesn’t build.

**Comment by MikeMcQuaid** [comment]
This formula was removed.
