### ISSUE TITLE
Add integration tests for all commands

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/legacy-homebrew#41326]
Currently `brew-test-bot` will run tests for formulae that have changed and `brew tests` but it won't check for e.g. the `brew audit` command being broken. We should have it (or `brew tests`) run integration tests on known good/test formulae to verify that every command in `Library/Homebrew/cmd` works with the changes in the pull-request.

**Comment by bfontaine** [comment]
:+1: Do we have a doc somewhere on how to write core tests for Homebrew? I’ll look at the existing tests if not.

**Comment by mikemcquaid** [comment]
@bfontaine No doc I'm afraid.

**Comment by MikeMcQuaid** [comment]
@eirinikos is working on this as part of Outreachy but closing this out for now as it's on the legacy repo.
