### ISSUE TITLE
Add DSL element for option aliases

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/legacy-homebrew#41515]
e.g. for `depends_on "gettext" => :optional` we might want to alias that so users can use `--with-gettext` or `--with-nls`.

CC @chdiza who mentioned something similar.

**Comment by xu-cheng** [comment]
I wonder this may be already supported somehow by `deprecated_option`.

**Comment by mikemcquaid** [comment]
Pretty sure it isn't but it won't require extending the code much beyond what was added for that.

**Comment by chdiza** [comment]
I like this idea.

**Comment by tdsmith** [comment]
I agree that "with-gettext" isn't very clear but I think it will be confusing to have synonyms unless we signpost it clearly. I think better `option` text is a better solution.

**Comment by MikeMcQuaid** [comment]
Migrated to https://github.com/Homebrew/brew/issues/289.
