### ISSUE TITLE
Explore Epochs [Packaging]

### ISSUE THREAD

**Issue by DomT4** [Homebrew/legacy-homebrew#41563]
We need a better way of handling things like #41535, i.e. even if the version seems lesser than the new version we could force a bump and assume the new versioning regardless.

Debian and we do something similar in versioning. Upstream version + Debian/Homebrew revision. But Debian also has a feature called "Epoch" which permits `apt-get` seeing the new package as an update even if the version number otherwise *seems* lesser than the current version number.

This particularly bites us when developers switch from using dates in their tarballs to using something like Semver.

[Debian's Epoch explanation/documentation](https://www.debian.org/doc/debian-policy/ch-controlfields.html), in the `5.6.12 Version` section.

We should consider attempting to mimic this feature in Homebrew to give us complete control over deciding which versions are newer or older, regardless of how upstream tag them. The end user experience is a little nicer with Epochs than it is us having to continue supporting the old versioning scheme ourselves indefinitely.

**Comment by mikemcquaid** [comment]
Another option would be tweaking our version parsing so that internally we consider everything as a semver and e.g. `20141010` becomes `0.0.20141010` or something.

**Comment by dunn** [comment]
There's probably a whole set of problems with this, but the first idea that springs to mind is having Homebrew force a bump when the version number changes in any way.  That would also allow for downgrades, when serious bugs require that a version be recalled.

**Comment by DomT4** [comment]
Don't close this one out just yet. I'll file an evolution PR over the next few days and close it then.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.

**Comment by vladshablinsky** [comment]
@MikeMcQuaid actually, I'm working on this feature and I'm planning to implement it within next two weeks.

**Comment by MikeMcQuaid** [comment]
@vladshablinsky Nice!

**Comment by DomT4** [comment]
@vladshablinsky 😻 🍰

**Comment by UniqMartin** [comment]
@vladshablinsky This is great! I'm excited to see this work of yours. 👍

**Comment by MikeMcQuaid** [comment]
This was implemented in https://github.com/Homebrew/brew/pull/719.
