### ISSUE TITLE
Sorting order inconsistent between `leaves` and `deps`

### ISSUE THREAD

**Issue by beeftornado** [Homebrew/legacy-homebrew#41618]
If you have formula installed from a tap, `brew leaves` sorts the output by formula name, while `brew deps` sorts the output by fullpath to the formula (ie. the first letter of output including tap name). This is related to a recently uncovered issue in brew-rmtree, an external command (https://github.com/beeftornado/homebrew-rmtree/issues/6). While brew-rmtree can easily workaround the issue, I would consider this to be unexpected behavior.

**Comment by bfontaine** [comment]
Could you try a pull-request? Thanks!

**Comment by beeftornado** [comment]
I would, but I don't know what the intended behavior is. For consistency, could one of the maintainers dictate how it *should* be sorted.

**Comment by bfontaine** [comment]
cc @Homebrew/owners for an opinion on this.

**Comment by tdsmith** [comment]
I think the current output is reasonable. How do you propose to change it?

**Comment by beeftornado** [comment]
I just think it should be consistent. I'll give you an example from my environment. Notice the location of 'homebrew/headonly/arcanist' in each list and other similar keg names. Having a different sorting order breaks the functionality of `join` (shell command) for anyone scripting.

`join <(brew leaves) <(brew deps mpv)` won't work at all because join assumes the lists are sorted, which one might presume by looking at each list individually. To get the desired effect you must add an extra `sort` command to each list, which seems unnecessary given that homebrew already kind of sorted the lists, just not the same way.

```
# brew leaves
homebrew/headonly/arcanist
caskroom/cask/brew-cask
beeftornado/rmtree/brew-rmtree
byobu
casperjs
class-dump
cloog
homebrew/versions/cloog-ppl015
ctags
dnstop
exiftool
exiv2
faac
freetds
gcc
homebrew/versions/gcc49
git
git-extras
gtk+
imagemagick
jasper
jenv
libass
libev
libksba
libvorbis
libyaml
maven
mongodb
mpv-player/mpv/mpv
mysql
nasm
node
homebrew/science/opencv
phantomjs
pngcrush
pngquant
postgresql
pyenv-virtualenv
pyenv-virtualenvwrapper
pyside
python
reattach-to-user-namespace
homebrew/dupes/rsync
sbt
sdl_image
sdl_mixer
sdl_ttf
sip
ssh-copy-id
tree
watch
wget
wxmac
zbackup
zsh
```

```
# brew deps --installed mpv
autoconf
automake
cairo
cmake
faac
ffmpeg
fontconfig
freetype
fribidi
gettext
git
glib
gobject-introspection
harfbuzz
icu4c
jpeg
lame
libffi
libgpg-error
libogg
libpng
libtiff
libtool
libvo-aacenc
libvorbis
libvpx
little-cms2
lua
mpg123
mpv-player/mpv/libass-ct
openssl
pixman
pkg-config
texi2html
webp
x264
x265
xvid
xz
yasm
```

**Comment by tdsmith** [comment]
It sounds like you would prefer that both lists were sorted on their full name, to avoid confusing shell utilities that expect sorted input. I think that would also be reasonable.

**Comment by beeftornado** [comment]
I can see reasons for both ways honestly. Sorting on the short name makes it more intuitive to locate items in the list via human and sorting on the full name makes it easier for automation and scripting tasks. Honestly, I kind of like sorting on the short name better. And I think `join` would accept it as long as it is applied to both lists.

**Comment by mikemcquaid** [comment]
We'd review a PR to make them more consistent. I'd lean towards sorting on the full-name (perhaps with those from taps always displayed last).

**Comment by tdsmith** [comment]
We'll look forward to a pull request, if we haven't already. Thanks!
