### ISSUE TITLE
Broken opt link will cause build failed under sandbox

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/legacy-homebrew#42312]
To reproduce it:
```bash
$ brew install autoconf
$ rm $(brew --prefix)/opt/autoconf
$ brew install automake --sandbox
==> Using the sandbox
Error: /Users/xucheng/Coding/Github/homebrew/opt/autoconf not present or broken
Please reinstall autoconf. Sorry :(
```

The problem is caused by [`fixopt`](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/build.rb#L75-L77) is called inside sandbox. To fix it, we should move these codes outside of `build.rb` into `formula_installer.rb`.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
