### ISSUE TITLE
falcon failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#42487]
https://gist.github.com/bbacbc12e332d7444d04

```
CMake Error at modules/native/dbi/mysql/CMakeLists.txt:38 (MESSAGE):
  MySQL client library was not found
```

Installing `mysql` makes the build succeed. Even though it looks like a simple missing dependency, it still seems 10.11-specific: `brew install falcon` succeeds on my 10.9 box that does not have `mysql` installed.

Perhaps there were mysql headers included in earlier versions of OS X or Xcode?

**Comment by bfontaine** [comment]
I was able to install it even if `mysql` is not installed:
```
=> Downloading http://falconpl.org/project_dl/_official_rel/Falcon-0.9.6.8.tgz
######################################################################## 100,0%
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/falcon/0.9.6.8 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAM
==> make
==> make install
🍺  /usr/local/Cellar/falcon/0.9.6.8: 414 files, 7.8M, built in 1 minute 56 seconds
```

**Comment by MikeMcQuaid** [comment]
This has a 10.11 bottle now.
