### ISSUE TITLE
ee failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#42482]
https://gist.github.com/49364f8c3a0d93209e8b

On OS X 10.11 PB4, no CLT.

```
Neither termio.h or sgtty.h are on this system!  
Don't know where to find curses, you'll need to modify 
source code to be able to build!
```

**Comment by apjanke** [comment]
Looks like this isn't 10.11-specific, but is due to no CLT. Same error on 10.9.5 without CLT installed.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
