### ISSUE TITLE
Handling DEVEL versions

### ISSUE THREAD

**Issue by smarek** [Homebrew/legacy-homebrew#42603]
I don't know if this is dupe of #29207, but seems to me like it isn't

Initial State:
```
> brew outdated
winetricks (20150416 < 20150706)
> brew info winetricks
winetricks: stable 20150706, HEAD
https://github.com/Winetricks/winetricks
/usr/local/Cellar/winetricks/20150416 (4 files, 660K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/winetricks.rb
==> Dependencies
Required: cabextract ✔, p7zip ✔, unrar ✔, wine ✘
> brew info wine
wine: stable 1.6.2 (bottled), devel 1.7.48, HEAD
/usr/local/Cellar/wine/1.7.44 (2380 files, 240M)
  Built from source with: --with-libgsm
/usr/local/Cellar/wine/1.7.45 (2384 files, 241M) *
  Built from source with: --with-libgsm
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/wine.rb
```

Winetricks update is available, Wine is installed with `--devel` and upgrading Winetricks will trigger Wine update to **Stable**

```
> brew upgrade winetricks
==> Upgrading 1 outdated package, with result:
winetricks 20150706
==> Upgrading winetricks
==> Installing winetricks dependency: wine
==> Downloading https://downloads.sourceforge.net/project/wine/Source/wine-1.6.2.tar.bz2
```

Also upgrade of wine, does nothing at all

```
> brew upgrade wine
Error: wine 1.7.45 already installed
```

So
  - DEVEL should be imho considered as normal versions
  - When upgrading package depending on another DEVEL package, it should check the DEVEL version not the stable one

Is that correct? Thank you!

**Comment by smarek** [comment]
Also `brew upgrade winetricks --ignore-dependencies` doesn't work in such case and have to be done like `brew unlink winetricks && brew install winetricks --ignore-dependencies`

**Comment by DomT4** [comment]
There have been comments on this before from other maintainers, but I understand this is intentional behaviour. The idea is that people don't want to remain on development versions forever, but rather tend to switch to them for a new feature or bug fix or some other short-term reason.

**Comment by angelXwind** [comment]
@DomT4 While there are users who would do what you describe in your comment, there are also others who would want to remain on the development branch forever — like me :P

**Comment by DomT4** [comment]
@angelXwind I have sympathy. I haven't ran a stable version of Tor locally for about 2 years now. It's something I wouldn't object to seeing changed, but it's a significant enough change that it has the potential to "surprise" existing users which is something we try very hard not to do.

I've left a comment on the team chat about whether or not we intend this behaviour; I'm open to seeing it changed but I am just one of 9 maintainers :smile:.

**Comment by smarek** [comment]
For example **wine** is in devel version light years ahead of **stable** version, and that's the one I keep up-to-date in `devel` state like forever.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.
