### ISSUE TITLE
libre fails if CLT not installed

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#42687]
https://gist.github.com/c0a0b27af5885ef796f2

Fails on 10.9.5 or 10.11 PB4 w/o CLT installed; succeeds on 10.9.5 with CLT installed. Error is a link failure to what look like its own symbols.

```
Undefined symbols for architecture x86_64:
  "__mod_close", referenced from:
      _mod_destructor in mod.o
  "__mod_open", referenced from:
      _mod_load in mod.o
  "__mod_sym", referenced from:
      _mod_load in mod.o
  "_lock_alloc", referenced from:
      _rtcp_sess_alloc in sess.o
  "_lock_read_get", referenced from:
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
  "_lock_rel", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
      _timeout in sess.o
  "_lock_write_get", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _timeout in sess.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Don't know why CLT would cause this. I looked at the build logs and it seems to just not be including some of its own `.o` files in the linker call. Maybe a difference in a `make` tool? Or maybe CLT is a red herring, and my machine with CLT installed happens to have other relevant differences?

**Comment by ilovezfs** [comment]
I cannot reproduce this issue.
