### ISSUE TITLE
le fails if CLT not installed

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#42681]
`brew install --build-from-source le` fails on 10.9 and 10.11 boxes if the CLT are not installed. Fails to find curses during configure.

```
checking for Curses... no
configure: error: No curses found - aborting
```

Additionally, on 10.11, but not on 10.9, `configure` spews a bunch of error messages that look like the result of a recursive directory creation process gone awry. No idea if that part is Homebrew-related.

10.11 logs: https://gist.github.com/29ffea78f05bf5d5e2ca

10.9 logs: https://gist.github.com/apjanke/f916fd1cdca6c657a054

**Comment by ilovezfs** [comment]
https://discussions.apple.com/thread/7281393?start=0&tstart=0

This was a rather nasty upstream issue.

Duplicates
https://github.com/Homebrew/legacy-homebrew/pull/46709
https://github.com/Homebrew/legacy-homebrew/issues/45273
