### ISSUE TITLE
jsvc fails if CLT not installed

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#42680]
On 10.9 and 10.11 w/o CLT, `jsvc` fails, unable to find `JavaVM.framework` headers.

```
*** Host support ***
checking C flags dependant on host system type... ok
./configure: line 2757: dev/null: No such file or directory
./configure: line 2769: cd: /System/Library/Frameworks/JavaVM.framework/Headers: No such file or directory
*** Java compilation tools ***
checking JAVA_HOME... /System/Library/Frameworks/JavaVM.framework
configure: error: Not a directory: /System/Library/Frameworks/JavaVM.framework/Headers
```

https://gist.github.com/36c37e0e1277b45462d1

**Comment by mistydemeo** [comment]
Looks like this is missing a Java dependency.

**Comment by Acubed** [comment]
... Well which dependency is it? The error message being returned isn't very helpful, shouldn't Brew be checking for the required dependencies first?

**Comment by apjanke** [comment]
She meant the `depends_on :java`` in the formula, which has been added.

Looks like that wasn't sufficient. I'm still getting the same error when trying to install on a 10.9.5 box with no CLT and which only has Java 1.6 installed. This program needs the JNI headers as well as Java compilation stuff. There's a patch in the formula to make it support Java 1.7. But the part that's failing is in `configure`, which the patch doesn't affect.

In `configure`, line 2764.
```
  if test -n "$JAVA_HOME" -a -d "$JAVA_HOME/include"; then
    cd "$JAVA_HOME/include"
  elif test -n "$JAVA_HOME" -a -d "$JAVA_HOME/../Headers"; then
    cd "$JAVA_HOME/../Headers"
  else
    cd /System/Library/Frameworks/JavaVM.framework/Headers
  fi
```

I think that will work with the Oracle 1.7 JDKs, or the Apple 1.6 if CLT are installed, just not 1.6 if CLT are absent. I don't know if we have a way of expressing "needs either Java >=1.7 or Java 1.6 with CLT installed". Maybe we should just make it require Java 1.7+. I wouldn't be inclined to devote much work to this formula, since the upstream project seems moribund at this point; no update since March 2013.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
