### ISSUE TITLE
`brew install` should warn/notice users when they use the old name of a renamed formula

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/legacy-homebrew#42895]
Right now it’s confusing, e.g.:

```
$ brew install libcppa
==> Downloading https://homebrew.bintray.com/bottles/caf-0.14.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/caf-0.14.0.yosemite.bottle.tar.gz
==> Pouring caf-0.14.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/caf/0.14.0: 212 files, 5,7M
```

Other commands that use `ARGV.formulae` should be affected as well.

cc @vladshablinsky

**Comment by vladshablinsky** [comment]
@bfontaine what about `resolved_formulae` (i.e. `reinstall)?

**Comment by vladshablinsky** [comment]
What about aliases? They also doesn't warn about anything. Before `libcppa` had been renamed to `caf` there was an alias `caf` so `brew install libcppa` and `brew install caf` behaved the same.

**Comment by mikemcquaid** [comment]
> What about aliases? They also doesn't warn about anything. Before libcppa had been renamed to caf there was an alias caf so brew install libcppa and brew install caf behaved the same.

This is a good point. I think it can be left as-is until we talk about it a bit more.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.
