### ISSUE TITLE
Dependencies not installed

### ISSUE THREAD

**Issue by dlh** [Homebrew/legacy-homebrew#42915]
If a formula depends on another formula with an option, then not all dependencies are installed. This results in an error when using `brew install`.

See [this gist for a basic example](https://gist.github.com/dlh/090cd7fcaa18667bc9e7).

## Steps to reproduce:

    $ brew tap dlh/deps-bug https://gist.github.com/090cd7fcaa18667bc9e7.git
    $ brew install a
    ==> Installing a from dlh/homebrew-deps-bug
    ==> Installing dlh/deps-bug/a dependency: b
    Error: /usr/local/opt/c not present or broken
    Please reinstall dlh/deps-bug/c. Sorry :(

## Expected results:

`c` should be installed, as it is a dependency of `b --with-c`.

## Related bugs/pull requests

#42817, #34554, #34576

**Comment by mikemcquaid** [comment]
Known bug but thanks for the great minimal reproduction instructions. The solution to this is moving away from `if` statements in the Formula DSL unless they will always evaluate identically on the same machine. We really need a new `option do` DSL block which you can put `depends_on` inside and will be evaluated properly.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
