### ISSUE TITLE
-L#{MacOS.sdk_path}/usr/lib breaks xcode builds on 10.11

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/legacy-homebrew#43333]
-L/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib is showing up in our compiler invocations when building postgres which is bad because it somehow interferes with xcode 7's .tbd magic and leads to failures to find system libraries.

This logic in the postgres formula:
```
      if File.exist?("#{MacOS.sdk_path}/usr/lib/tclConfig.sh")
        args << "--with-tclconfig=#{MacOS.sdk_path}/usr/lib"
      end
```
looks suspect to me but I haven't tested.

**Comment by tdsmith** [comment]
Someone Misty and I have been working with on IRC says removing --with-tclconfig from the formula didn't help his build (but xcode-selecting the CLT did).

**Comment by tdsmith** [comment]
Example failure: https://gist.github.com/anonymous/15378d63c3d82b70eb4c

Successful configure outside Homebrew: https://gist.github.com/mariusk/644912d9380090df7860

**Comment by tdsmith** [comment]
Something is setting LDFLAGS somewhere but I'm not sure where it's coming from: https://gist.github.com/anonymous/15378d63c3d82b70eb4c#file-config-log-L2136

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
