### ISSUE TITLE
Homebrew has no facility for retrieving the dependency tree actually constructed at build time

### ISSUE THREAD

**Issue by the-real-tokai** [Homebrew/legacy-homebrew#43956]
When using `brew deps --installed <formula>` it lists also dependencies that were not used at the time of the installation of the formula, but introduced later (by different formulas). This makes it somewhat hard to  judge if the formula was build or not build with the respective dependencies.

e.g.:
```
$ brew deps --installed --1 imagemagick
fontconfig
freetype
jpeg
libpng
libtool
little-cms2
pango
pkg-config
xz
xz
```

Various dependencies are listed for this that I introduced **after** I installed ImageMagick. In this case "fontconfig", "little-cms2" and "pango" are definitely not used/ linked to ImageMagick. This somewhat can be verified by looking at the installation receipt:

```
$ cat /usr/local/homebrew/Cellar/imagemagick/6.9.1-10/INSTALL_RECEIPT.json 
{"used_options":[],"unused_options":["--with-fftw","--with-hdri","--with-jp2","--with-openmp","--with-perl","--with-quantum-depth-8","--with-quantum-depth-16","--with-quantum-depth-32","--without-opencl","--without-magick-plus-plus","--without-jpeg","--without-libpng","--without-libtiff","--without-freetype","--with-x11","--with-fontconfig","--with-little-cms","--with-little-cms2","--with-libwmf","--with-librsvg","--with-liblqr","--with-openexr","--with-ghostscript","--with-webp","--with-pango"],"built_as_bottle":false,"poured_from_bottle":false,"time":1437996984,"HEAD":"0c79ae32dca71890623b9dee0ced96a770744e65","stdlib":"libcxx","compiler":"clang","source":{"path":"/usr/local/homebrew/Library/Formula/imagemagick.rb","tap":"Homebrew/homebrew"}}
```

Maybe INSTALL_RECEIPT could record the actually used deps too? And `deps --installed` could use this information then, when available, in the future?

*(feature request)*

**Comment by tdsmith** [comment]
Why do you want this?

**Comment by tdsmith** [comment]
`--installed` is a noun representing the set of installed packages; `brew deps --installed --1 imagemagick` is showing you the union of the first-order dependencies of imagemagick and the first-order dependencies of all installed packages, so the output you're receiving is the design behavior and should not change.

**Comment by the-real-tokai** [comment]
*Why do you want this?*

I want to know what is used/ linked into the respective formula (*imagemagick* in the given example). And dependencies that were installed afterwards are not actually used as the output of the brew command suggests.

E.g. whatever *ImageMagick* does with *pango* (I have no idea :smile: ) … the version of ImageMagick I have installed can't do it. But looking at the brew output it suggests it should be possible. Might lead to confusion.

Currently the only way to be really sure is to scan all the ImageMagick binaries with otool, I guess. :)

**Comment by tdsmith** [comment]
> And dependencies that were installed afterwards are not actually used as the output of the brew command suggests.

To be clear, the output of `brew deps` does not suggest this.

Apps with optional dependencies hopefully provide a way to query their capabilities. You might find [brew-linkage](https://github.com/Homebrew/homebrew-dev-tools/blob/master/cmd/brew-linkage.rb) helpful; you can install it with `brew tap homebrew/homebrew-dev-tools`.

**Comment by tdsmith** [comment]
I don't think this is on our roadmap. Thanks for submitting the issue.
