### ISSUE TITLE
failed to install brew install cdo --with-grib2 on OS X Yosemite 10.10.5

### ISSUE THREAD

**Issue by jlnelias** [Homebrew/legacy-homebrew#44383]
hi
I think every soft is up to date to the last version. I have made brew update and brew doctor....
i have done brew gist-logs cdo --with-grib2 and i get this https://gist.github.com/559a2705e26a579cec42

```
Error: SIGTERM
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:7:in `close'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:545:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:212:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:189:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:133:in `<main>'
/usr/local/Library/Homebrew/build.rb:179:in `close': Broken pipe (Errno::EPIPE)
	from /usr/local/Library/Homebrew/build.rb:179:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
```

i hope you can help me
best regards

**Comment by DomT4** [comment]
> Error: SIGTERM
Please report this bug:

What command are you running when you see this? The `gist-logs` one?

**Comment by jlnelias** [comment]
Hi
i try the command brew -v install cdo --with-grib2 1>build.log 2>&1  to get a log but after 10 mn all the computer freeze. 2 hours later it still in the same situation most of the time freezing and nothing seem to move in the terminal windows. I have to use ctrl+Z to stop the process and be able to use the computer again.
Jean-Luc

Jean-Luc Nelias/Eurl Nelias
11 rue du coteau du Frugy
29000 Quimper France
jl.nelias@gmail.com
+33 680 859 424
Skype:jlnelias

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
