### ISSUE TITLE
open-scene-graph failed to build on 10.11: cmake index out of range

### ISSUE THREAD

**Issue by valentin0** [Homebrew/legacy-homebrew#44524]
After a clean installation of OS X 10.11 I cannot build open-scene-graph anymore. Thanks for any help!

https://gist.github.com/anonymous/02278d59540cfc46587f

Edit: gist-logs updated. CLT were not available, but fixing this didn't solve the problem.

**Comment by mkrapp** [comment]
Hi, line 183 in `CmakeLists.txt` evaluates the the Mac OS X version (major, minor, and patch) via `/usr/bin/sw_vers -productVersion`, which is not available under El Capitan (`= 10.11`).

**Comment by valentin0** [comment]
Thanks for your reply. I've just discovered that problem, too. Uncommenting this line and setting the OS X version to 10.10 seems to work for me.

**Comment by DomT4** [comment]
Just to check the above: Are you saying the build code can only handle OS X releases which are `10.10.1` or `10.11.2` for example, rather than just `10.11`?

**Comment by valentin0** [comment]
Yes! But according to my vague understanding of the CmakeLists.txt something like 10.11.1 could still cause problems, since the if-else-statement starting at line 1110 checks only for OS X versions between 10.4 and 10.10. But treating 10.11 like 10.10 should fix the problem, at least, for me it works.

**Comment by apjanke** [comment]
The error from the logs.
```
CMake Error at CMakeLists.txt:183 (LIST):
  list index: 2 out of range (-2, 1)
```

This looks like upstream issue openscenegraph/osg#29, which is reported to be fixed in master at this point.

**Comment by luzpaz** [comment]
@apjanke thanks for working on this. Have you tested this against OpenSceneGraph-3.5.1.zip ?

**Comment by MikeMcQuaid** [comment]
Closing this out as it's an upstream issue that needs fixed there rather than here.
