### ISSUE TITLE
cntlm daemon doesn't start

### ISSUE THREAD

**Issue by lifeisfoo** [Homebrew/legacy-homebrew#44741]
I've installed the latest version of [cntlm](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cntlm.rb) but, after the reboot, the daemon doesn't start. 

If I run it manually the output is: `/Library/LaunchDaemons/homebrew.mxcl.cntlm.plist: Operation already in progress`

on Yosemite 10.10.4

**Comment by DomT4** [comment]
> Operation already in progress

This usually means that the `plist` is already loaded and running. You can manually kick it with:

```bash
sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.cntlm.plist && sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.cntlm.plist
```

**Comment by lifeisfoo** [comment]
Yes, the LaunchDaemon is running, but cntlm doesn't.
If I `unload` && `load` it nothing change.

But if I unload the daemon and start cntlm manually simply typing `cntlm` from the terminal, it works.

**Comment by DomT4** [comment]
What are you expecting to see when `launchctl` loads it in? How are you testing whether it has launched compared to from the CLI?

**Comment by lifeisfoo** [comment]
When I run it manually (cntlm command) it works because I can browse the internet.

When it is executed from the launchd daemon I can't browse the internet. Also I've checked if it's running with `ps aux | grep cntlm`, but no entry is present.

**Comment by lifeisfoo** [comment]
Now, after the computer start, ps says:

    root    126   0,0  0,0  2460788    788   ??  Ss   10:10am   0:00.39 /usr/local/opt/cntlm/bin/cntlm

But it doesn't works: any idea?

**Comment by LeAlesk** [comment]
Try changing `<string>/usr/local/opt/cntlm/bin/cntlm</string>` to `<string>/usr/local/bin/cntlm</string>`
in `/Library/LaunchDaemons/homebrew.mxcl.cntlm.plist`

According to Apple's [Daemons and Services Programming Guide](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html) DTD description seems incorrect
Try changing `<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">` to `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`

**Comment by mikemcquaid** [comment]
The DTD and the binary location string are not the problems. Can you try to build this from source and see if you have the same issues?

**Comment by bfontaine** [comment]
Ping re Mike’s comment?

**Comment by LeAlesk** [comment]
cntlm is building and working fine.
the issue is that the daemon does not always start at boot.
I thought it was related to SIP protection in El Capitan or rights, but it's not.
Haven't found a solution yet. Just starting cntlm when daemon fails to start.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
