### ISSUE TITLE
Errors installing packages dependent on python when pyenv installed

### ISSUE THREAD

**Issue by ndevenish** [Homebrew/legacy-homebrew#44747]
I've got pyenv installed and activated, through homebrew. I had activated a python3 environment, when I ran homebrew to install some things - crucially, this means that the `python` executable in the `PATH` works, but just shows an error (with non-zero return value). Firstly, when it attempts to get the python user packages in `python.rb`:
```python
def self.user_site_packages(python)
    Pathname.new(`#{python} -c "import site; print(site.getusersitepackages())"`.chomp)
end
```
It appears to run python without checking the success of the return - which failed, which leads to messages like these (from e.g. [caveats.rb:87@b33f0](https://github.com/Homebrew/homebrew/blob/b33f04a1d034e0258352dbd8ad3d53783b7f4585/Library/Homebrew/caveats.rb#L87-L91)):
```
If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
  mkdir -p 
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> homebrew.pth
```
e.g. spurious and incorrect commands.

Worse, I seem to have gotten several of the "python not available" messages during installation of packages, meaning I now have no idea if the package installation worked or not, because homebrew threw no errors.

I'd probably suggest checking the return value of `python` calls, or at least checking something works on startup - `brew doctor` won't even pick up this issue, but ideally installing new packages would fail also.

**Comment by MikeMcQuaid** [comment]
We don't support using `pyenv`. We'll accept PRs for this but we're not actively working on it at this time.
