### ISSUE TITLE
brew doctor should detect missing command-line tools

### ISSUE THREAD

**Issue by markjreed** [Homebrew/legacy-homebrew#44754]
I upgraded to El Capitan and "brew doctor" said I was good to go, but I wasn't, because I hadn't yet installed the new version of the command-line dev tools.  "brew install php56" failed because it couldn't find libz.  Seems like something "brew doctor" should catch..

**Comment by majorsl** [comment]
Heh, that got me too. And last time I upgraded. This is a good idea.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.
