### ISSUE TITLE
`brew search avr` fails: stack level too deep

### ISSUE THREAD

**Issue by numist** [Homebrew/legacy-homebrew#44837]
```
% brew search avr
Error: stack level too deep
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21
command failed with status: 1
```

Other commands seem to work though:

```
% brew search avrdude
avrdude (installed)
```

`/usr/local` HEAD is e0d480afe671b4ff1a23407ab2e7e9092e788591

**Comment by DomT4** [comment]
`brew search avr` will look for every formula which contains that word in it somewhere, and it's likely one of those formulae has changes which when read cause Ruby to panic. Do you have any taps tapped that have `avr`-named formula available?

**Comment by xu-cheng** [comment]
It looks like one of formula in your system is broken. You can check it with `brew readall`.

**Comment by numist** [comment]
Sure enough, looks like a broken formula:

```
% brew readall
Error: problem in /usr/local/Library/Taps/weareleka/homebrew-avr/avr-gcc48.rb
stack level too deep
Error: problem in /usr/local/Library/Taps/weareleka/homebrew-avr/avr-libc48.rb
stack level too deep
command failed with status: 1
```

**Comment by mralexgray** [comment]
+1 I have the same issue.

**Comment by bfontaine** [comment]
Please run `brew update`; it should be fixed now that https://github.com/WeAreLeka/homebrew-avr/pull/10 has been merged.

**Comment by UniqMartin** [comment]
Issue seems to have been resolved, thus closing.
