### ISSUE TITLE
secret-tool in libsecret not functional

### ISSUE THREAD

**Issue by arloherrine** [Homebrew/legacy-homebrew#44994]
first off, I installed libsecret and the included secret-tools won't run because it seems to require dbus. So I think dbus needs to be added as a dependency
```
$ brew install libsecret                                                                                                                       9:41:24
==> Installing dependencies for libsecret: gobject-introspection
==> Installing libsecret dependency: gobject-introspection
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.46.0.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gobject-introspection-1.46.0.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.46.0: 198 files, 10M
==> Installing libsecret
==> Downloading https://homebrew.bintray.com/bottles/libsecret-0.18.3.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libsecret-0.18.3.mavericks.bottle.tar.gz
==> Pouring libsecret-0.18.3.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libsecret/0.18.3: 132 files, 2.6M


 $ secret-tool store --label='test password' key1 value1                                                                                            9:41:38

(secret-tool:2523): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
secret-tool: Failed to execute child process "dbus-launch" ()
```

Then I installed dbus manually, but it still doesn't work.
```
$ brew install d-bus                                                                                                                           9:41:54
==> Downloading https://homebrew.bintray.com/bottles/d-bus-1.10.0.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/d-bus-1.10.0.mavericks.bottle.tar.gz
==> Pouring d-bus-1.10.0.mavericks.bottle.tar.gz
==> /usr/local/Cellar/d-bus/1.10.0/bin/dbus-uuidgen --ensure=/usr/local/var/lib/dbus/machine-id
==> Caveats
To load d-bus:
  launchctl load ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
==> Summary
🍺  /usr/local/Cellar/d-bus/1.10.0: 46 files, 1.6M
 $ secret-tool store --label='test password' key1 value1                                                                                            9:42:28

(secret-tool:2917): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
secret-tool: Error spawning command line 'dbus-launch --autolaunch=5c4e905124858d2f94420504561e8e9f --binary-syntax --close-stderr': Child process exited with code 1
```
Running the given dbus-launch command manually indicates that autolaunch requires X11 to be compiled in.
```
$ dbus-launch --autolaunch=5c4e905124858d2f94420504561e8e9f --binary-syntax --close-stderr                                                         9:42:40
Autolaunch requested, but X11 support not compiled in.
Cannot continue.
```

So I tried modifying the dbus formula to compile X11 in, but when I tried building it, I was missing the X11 library. This tells me that maybe a new dbus-x11 formula needs to be put into https://github.com/Homebrew/homebrew-x11, and libsecret should be moved there as well, with a dbus-x11 dependency added.

**Comment by arloherrine** [comment]
It turns out that running `brew install Caskroom/cask/xquartz` didn't make compilation of d-bus with X11 work, so I don't know what can be done here

**Comment by apjanke** [comment]
Was this the build failure you got when trying to build it with X support?

```
dbus-launch-x11.c:37:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^
1 error generated.
```

That `Xlib.h` is supplied by Tcl/Tk, not X11 itself. It'll be pulled in if you define an `:x11` dependency in the formula. [Here's](https://github.com/apjanke/homebrew/commit/b774223247f2fbba514440892581c7276ed64006) an example of how you could do it. That got `d-bus` to build with X11, but `secret-tool` still errored out. Might need additional changes to the `libsecret` formula to make it actually work.

**Comment by arloherrine** [comment]
Yes that is the error I was seeing. Applying your patch did get d-bus to compile with x11, thanks. But, as you say, secret-tool still errors out. 

Perhaps there's no need for secret-tool to actually use dbus-lauch with the autoload option (which is why x11 is required now). If I knew how dbus worked maybe I would have a more complete suggestion, but as there's no gui involved here x11 doesn't seem like it should be necessary

**Comment by apjanke** [comment]
Same here.

```
[~]
$ brew info d-bus | grep Built
  Built from source with: --with-x11
[~]
$ secret-tool store --label='test password' key1 value1

(secret-tool:7303): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
secret-tool: Error spawning command line 'dbus-launch --autolaunch=9e5d0f8ea30614a498eaf09755b4993a --binary-syntax --close-stderr': Child process exited with code 1
[✘ ~]
$ dbus-launch --autolaunch=9e5d0f8ea30614a498eaf09755b4993a --binary-syntax --close-stderr
EOF in dbus-launch reading address from bus daemon
[✘ ~]
$
```

Have you used `secret-tool` and gotten it to work before? I wonder if this is an issue with the formulae, or just our use of the program.

**Comment by arloherrine** [comment]
I have not gotten it to work. it could certainly be a problem with the program. we can probably just close the issue

**Comment by apjanke** [comment]
Mmm, let's leave it open for now. I think you're right that we at least need to add the `libsecret` -> `d-bus` dependency. I'll see if a quick read through their tutorials comes up with an answer.

**Comment by apjanke** [comment]
So, it looks like there are more parts needed to make this actually work. `libsecret` is [just the client library](https://lwn.net/Articles/490518/) for the Freedesktop/Gnome [Secret Service API](http://standards.freedesktop.org/secret-service/). And D-Bus is the message bus it communicates over. But to store the secrets or do work with them, you need a "server" back-end that actually provides the service. That's `gnome-keyring-daemon` or `ksecretservice` on GNOME or KDE. I don't know what, if anything, provides the service on OS X.

I asked on #31499; maybe the original formula submitter will know.

**Comment by tdsmith** [comment]
We should probably not install secret-tool.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
