### ISSUE TITLE
Fish completion supporting is broken

### ISSUE THREAD

**Issue by xyb** [Homebrew/legacy-homebrew#45124]
`fish_completion.install` could install script successfully, but the completion function doesn't work. I think brew installed script into `/usr/local/share/fish/vendor_completions.d/` but fish only using `/usr/share/fish/vendor-completions.d`, and `pkg-config --variable completionsdir fish` which is `/usr/local/Cellar/fish/2.2.0/share/fish/vendor_completions.d` (see fish-shell/fish-shell#1485), both of two directories not exist to cause homebrew's fish completion supporting broken.

**Comment by xyb** [comment]
See also  fish-shell/fish-shell@ab5b229

**Comment by MerelyAPseudonym** [comment]
You might also want to be aware of https://github.com/fish-shell/fish-shell/issues/2113.

**Comment by MerelyAPseudonym** [comment]
Perhaps the solution would be to make sure that `(brew --prefix fish)/share/pkgconfig/fish.pc`’s `completionsdir` points to `(brew --prefix)/share/fish/vendor_completions.d` instead of `${datadir}/fish/vendor_completions.d`.

**Comment by xyb** [comment]
@MerelyAPseudonym try to fix it on #45262

**Comment by zanchey** [comment]
I have a PR for fish to allow Homebrew to set the completion (and other) directories via a configure flag: https://github.com/fish-shell/fish-shell/pull/2896. Comments welcome.

**Comment by gyakovlev** [comment]
Hey,
I've submitted PR for fish. 
https://github.com/Homebrew/homebrew-core/pull/2813/files

**Comment by MikeMcQuaid** [comment]
Sounds like this was fixed. If not: we'll accept PRs for this but we're not actively working on it at this time.
