### ISSUE TITLE
gcc causes false alarms in C++ stdlib check

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/legacy-homebrew#45218]
Stuff with :fortran dependencies leads to C++ stdlib check warnings like `Warning: homebrew/science/opencv dependency gcc was built with a different C++ standard library (libstdc++ from clang). This may cause problems at runtime.`. I think this is always a false alarm for gcc and we should skip it.

**Comment by mikemcquaid** [comment]
If `gfortran` links against a different C++ standard library I can't see how it's definitely a false alarm?

**Comment by UniqMartin** [comment]
I think the warning is indeed misleading, as `gfortran` most certainly doesn't link against `libstdc++` and also doesn't cause programs compiled with it to be linked against it. Furthermore, there are only three libraries linking to `libstdc++` (not the one from Apple/Clang, but from the `gcc` formula): `libasan` (address sanitizer helper), `libubsan` (undefined behavior sanitizer helper), `libcilkrts` (Cilk language runtime). These are all libraries “normal” programs will never link against. And of course there is `libstdc++` itself, but that will only be used if programs are compiled with `g++` from the `gcc` formula.

Here's the output from my `dylibcheck` tool that helped me to come to this conclusion. It shows Mach-O binaries that have an `LC_*_DYLIB` load command with the string `stdc++` in it:

```
$ brew dylibcheck --linkage --compact $(brew --cellar gcc) | fgrep stdc++
@cellar@/gcc/5.2.0/lib/gcc/5/libasan.2.dylib:LC_LOAD_DYLIB=@cellar@/gcc/5.2.0/lib/gcc/5/libstdc++.6.dylib
@cellar@/gcc/5.2.0/lib/gcc/5/libcilkrts.5.dylib:LC_LOAD_DYLIB=@cellar@/gcc/5.2.0/lib/gcc/5/libstdc++.6.dylib
@cellar@/gcc/5.2.0/lib/gcc/5/libstdc++.6.dylib:LC_ID_DYLIB=@prefix@/opt/gcc/lib/gcc/5/libstdc++.6.dylib
@cellar@/gcc/5.2.0/lib/gcc/5/libstdc++.6.dylib:LC_LOAD_DYLIB=/usr/lib/libSystem.B.dylib
@cellar@/gcc/5.2.0/lib/gcc/5/libstdc++.6.dylib:LC_LOAD_DYLIB=@prefix@/lib/gcc/5/libgcc_s.1.dylib
@cellar@/gcc/5.2.0/lib/gcc/5/libubsan.0.dylib:LC_LOAD_DYLIB=@cellar@/gcc/5.2.0/lib/gcc/5/libstdc++.6.dylib
```

(The format is `<file>:<load_command>=<load_command_data>`.)

**Comment by tdsmith** [comment]
The object files which are produced by gfortran do not link to a C++ stdlib.

**Comment by UniqMartin** [comment]
The check for the C++ stdlib is rather simple: [keg_relocate.rb#L81-L97](https://github.com/Homebrew/homebrew/blob/55a85152ec38ee6bb6b69a35a78448605c16ae9e/Library/Homebrew/keg_relocate.rb#L81-L97). That's what gets recorded in the `INSTALL_RECEIPT.json` and what now causes this warning for every formula that links against *anything* that uses a library from the `gcc` formula (including `libgfortran`). At least this is how I understand this.

**Comment by mikemcquaid** [comment]
Ah, sorry, I misread here about it being `gcc` output rather than `gcc` itself. In that case: :+1: to ignore.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
