### ISSUE TITLE
Deprecate old compiler support?

### ISSUE THREAD

**Issue by DomT4** [Homebrew/legacy-homebrew#45363]
More specifically, as discussed elsewhere, should we mandate installing *everything* with either a modern Clang or modern GCC, rather than attempting to debug issues for compilers that no maintainer (I believe) uses on a daily basis?

Potential upsides:
* Would provide a consistent experience.
* Could reduce maintainer burden on edge cases and old compilers breaking formulae without us knowing because we don't test those compilers any more, which in turn might be nicer for end users as they should discover less of those breakages.
* Could make it easier to support older versions of OS X as one of the primarily breakage points would be reduced.

Potential downsides:
* Slightly clashes with Homebrew's nigh-adamant usage of system utilities unless they are insecure, lacking required features or very broken in other ways.
* Mandates everyone on old OS X versions installing a modern GCC prior to being able to build anything not bottled. Compiling GCC on a modern machine is a fairly long build, could be a lot worse on old Macs.

**Comment by chdiza** [comment]
> Compiling GCC on a modern machine is a fairly long build, could be a lot worse on old Macs.

In Tigerbrew land, it's utterly unbearable.  A multi-day process.  There are lots of prerequisites that take forever too.  My point is just this: I hope that whatever changes take place, they don't put a big merge-conflict burden on @mistydemeo.

But enough about Tigerbrew.

I see in the upsides column a lot of "could".  The downside column items amount to "would".  The second thing in the downside column strikes me as a truly gigantic negative.  It should take a lot more than a couple of "coulds" to outweigh a gigantic "would".

Also, I thought the main point of having a test bot armed with older versions of OS X is that it will catch these complications before they ever get to the user.

**Comment by mikemcquaid** [comment]
> In Tigerbrew land, it's utterly unbearable. A multi-day process. There are lots of prerequisites that take forever too. My point is just this: I hope that whatever changes take place, they don't put a big merge-conflict burden on @mistydemeo.

Agreed. I think if nothing else we should basically stop `llvm-gcc` and possibly older `clang` versions from being ever used. They just don't work reliably.

Something we could consider is just ensuring that @mistydemeo or other Tigerbrew people have access to infrastructure to build GCC binaries. Currently we have working VMs for 10.5 and above. If anyone could create some 10.4 VMs somehow then that would make it a bit easier.

**Comment by MikeMcQuaid** [comment]
> Agreed. I think if nothing else we should basically stop llvm-gcc and possibly older clang versions from being ever used. They just don't work reliabl

We stopped `llvm-gcc` being used but other compilers are still needed/useful on older versions as they may be the only ones that e.g. support Objective C properly.
