### ISSUE TITLE
leafnode - no plist file

### ISSUE THREAD

**Issue by deKay01** [Homebrew/legacy-homebrew#45402]
Thanks to @DomT4 for the fix letting leafnode run. However, I can't get it to run as a service. I've run

 ```brew tap homebrew services```

and then tried

```brew services start leafnode```

but just get the error:

Error: Formula `leafnode` not installed, #startup_plist not implemented or no plist file found.

So I think I need a .plist.

**Comment by deKay01** [comment]
Hmm. I think I can modify my old macports plist for leafnode:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
        <dict>
                <key>OnDemand</key>                     <true/>
                <key>Label</key>                        <string>org.brew.leafnode</string>
                <key>WorkingDirectory</key>             <string>/usr/local/var/spool/news</string>
                <key>Program</key>                      <string>/usr/bin/sudo</string>
                <key>ProgramArguments</key>
                <array>
                        <string>/usr/bin/sudo</string>
                        <string>-u</string>
                        <string>**[put username here]**</string>
                        <string>/usr/local/sbin/leafnode</string>
                </array>
                <key>Sockets</key>
                <dict>
                        <key>Listeners</key>
                        <dict>
                                <key>SockServiceName</key>      <string>nntp</string>
                        </dict>
                </dict>
                <key>inetdCompatibility</key>
                <dict>
                        <key>Wait</key> <false/>
                </dict>
        </dict>
</plist>
```

Put that in /Library/LaunchDaemons and run

```sudo launchctl load /Library/LaunchDaemons/org.brew.leafnode.plist ```

And that seems to work.

I know nothing about how to actually do pulls and commits and so on, but is this worth including in the package somehow?

Now to figure out how to make cron work...

**Comment by mikemcquaid** [comment]
> I know nothing about how to actually do pulls and commits and so on, but is this worth including in the package somehow?

I think so! Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by deKay01** [comment]
OK... this is scary.

I'm at the brew edit stage. Where do I put my plist, and is there something I can do to make it insert the username in the "**[put username here]**" bit?

Thanks!

**Comment by mikemcquaid** [comment]
@deKay01 I'm not sure what you mean, can you elaborate a bit more? Thanks for trying!

**Comment by rakkesh** [comment]
@deKay01 as `leafnode` is built with `user` during compile time in the formula, I don't see why `sudo` is required here; instead the following xml can be put in the formula.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>OnDemand</key>
    <true/>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>WorkingDirectory</key>
    <string>/usr/local/var/spool/news</string>
    <key>Program</key>
    <string>#{sbin}/leafnode</string>
    <key>Sockets</key>  
    <dict>              
      <key>Listeners</key>
      <dict>              
        <key>SockServiceName</key>
        <string>nntp</string>
      </dict>
    </dict>
    <key>inetdCompatibility</key>
    <dict>
      <key>Wait</key>
      <false/>
    </dict>
  </dict>
</plist>
```

If am incorrect, and `sudo` is required in `plist`, then replace **"[put username here]"** with 
`#{ENV["USER"]}`

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by MikeMcQuaid** [comment]
Actually, looks like it was fixed in https://github.com/Homebrew/homebrew-core/issues/2432
