### ISSUE TITLE
[boost] mpi-related issues in formula

### ISSUE THREAD

**Issue by davydden** [Homebrew/legacy-homebrew#45606]
The [current code](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb#L28-L34) in boost ~~is wrong~~ could be better:
```
  if build.cxx11?
    depends_on "icu4c" => [:optional, "c++11"]
    depends_on "open-mpi" => "c++11" if build.with? "mpi"
  else
    depends_on "icu4c" => :optional
    depends_on :mpi => [:cc, :cxx, :optional]
  end
```
~~~One should at least have 
`depends_on :mpi => [:cc, :cxx, :optional] if build.with? "mpi"`~~~

Better yet would be 
```
  if build.cxx11?
    depends_on "icu4c" => [:optional, "c++11"]
  else
    depends_on "icu4c" => :optional
  end
  depends_on :mpi => [:cc, :cxx, :optional]
```
as I do not see why would one ignore `:mpi` requirement by hardcoding `open-mpi` dependency. What about [mpich](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mpich.rb), for example?

**Comment by davydden** [comment]
mpi was introduced here https://github.com/Homebrew/homebrew/commit/3ba5aa62347dde6c7b3a456e70c9c72c889488a0

**Comment by bfontaine** [comment]
The `:optional` modifier should be equivalent to `if build.with? "mpi"` here.

**Comment by davydden** [comment]
how about using `:mpi` throughout?

**Comment by davydden** [comment]
p.s. agree on `depends_on :mpi => [:cc, :cxx] if build.with? "mpi"`

**Comment by bfontaine** [comment]
According to the body of 3ba5aa62347dde6c7b3a456e70c9c72c889488a0 `:mpi` is broken when built with C++. Or at least it was at the time; it might work now.

**Comment by davydden** [comment]
`:mpi` just checks for available MPI compilers, which in case of homebrew by default come from `open-mpi` and `mpich`. If it can't find any, it builds `open-mpi`.

Perhaps the issue was that `requirement` class can't accept any extra options to the default formula (in that case `open-mpi`), so the author wanted to make sure the default is built with `cxx11`. 
If that is indeed the case, i would rather propose to make `cxx11` default in `open-mpi` and use `:mpi` only in boost to be consistent with the requirement and allow different mpi implementation (openmpi/mpich).

**Comment by davydden** [comment]
@manphiz  ?

**Comment by manphiz** [comment]
Hi @davydden , not sure why I didn't get your ping at the time. I believe the reason was that only open-mpi support building with C++11 and (maybe) I tested mpich and it failed at the time. I'm not sure whether other mpi implementations have caught up now. Any one willing to test this is welcome.
