### ISSUE TITLE
gdal HEAD does not compile (missing gdal_utils.h)

### ISSUE THREAD

**Issue by cbertelli** [Homebrew/legacy-homebrew#45864]
This is the log. Brew doctor says my installation is well and I don't feel so badly. The error is in bold.

brew reinstall gdal --HEAD
==> Reinstalling gdal
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://svn.osgeo.org/gdal/trunk/gdal
==> ./configure --prefix=/usr/local/Cellar/gdal/HEAD --mandir=/usr/local/Cellar/gdal/HEAD/share/man --with-local=/usr/local/Cellar/gdal/HEAD --with-threads --with-libtool --with-pcr
==> make
==> make install
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.9.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/gdal--numpy-1.9.3.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/gdal20151110-89792-69f9x8/homebrew-numpy --single-version-externally-managed --record=installed.txt
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/gdal/HEAD --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/carlo/Library/Logs/Homebrew/gdal/05.python:
copying osgeo/gdalconst.py -> build/lib.macosx-10.9-x86_64-2.7/osgeo
copying osgeo/gdalnumeric.py -> build/lib.macosx-10.9-x86_64-2.7/osgeo
copying osgeo/gnm.py -> build/lib.macosx-10.9-x86_64-2.7/osgeo
copying osgeo/ogr.py -> build/lib.macosx-10.9-x86_64-2.7/osgeo
copying osgeo/osr.py -> build/lib.macosx-10.9-x86_64-2.7/osgeo
running build_ext
building 'osgeo._gdal' extension
creating build/temp.macosx-10.9-x86_64-2.7
creating build/temp.macosx-10.9-x86_64-2.7/extensions
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/sqlite/include -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/private/tmp/gdal20151110-89792-69f9x8/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-10.9-x86_64-2.7/extensions/gdal_wrap.o
**extensions/gdal_wrap.cpp:5877:10: fatal error: 'gdal_utils.h' file not found**
#include "gdal_utils.h"   
         ^
1 error generated.
error: command 'clang' failed with exit status 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
gdal 2.0.0 https://github.com/Homebrew/homebrew/pull/42845
bottled postgis 2.2.0 still looking for gdal 1.x when gdal 2.0 installed https://github.com/Homebrew/homebrew/issues/45780
Latest update to poppler, 0.34.0 breaks gdal --with-complete https://github.com/Homebrew/homebrew/issues/42031

It seems that this error has nothing to do with poppler, but I think it's not due to an upstream error.

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do.

**Comment by cbertelli** [comment]
This is the gist: https://gist.github.com/9446b39bf5287e880406

**Comment by springmeyer** [comment]
I also hit this and was able to workaround by building without python: `brew install gdal --HEAD --without-python`

**Comment by cbertelli** [comment]
Thanks, but this is not an option for me, I need python as gdal is used inside QGIS. Some weeks ago I built gdal HEAD without any issue. There is already another issue with python, #44117: https://github.com/Homebrew/homebrew/issues/44117
May it be something upstream? I saw some discussions about python plugins in the comments of the formula.

**Comment by mzinboy** [comment]
I had a similar problem that used --with-swig-java option. Do you use with --with-java option? My solution was it.

**Comment by cbertelli** [comment]
I think the issue is about numpy. This formula wants to install an outdated numpy (numpy has a formula by itself with an up-to-date version). Maybe it would be better to put numpy in the requirements. A possible course of action could be uninstalling the newer version, updating gdal and than update numpy. It doesn't sound like a good idea, but...

**Comment by jj0hns0n** [comment]
Anyone have any recent luck getting around this issue?

**Comment by Spaxe** [comment]
Ran into this issue also.

**Comment by tdsmith** [comment]
The released version seems to build fine. Sorry, but it's difficult for Homebrew maintainers to assist with --HEAD builds, which are moving targets. You might be able to get some help from the gdal team.
