### ISSUE TITLE
Chipmunk2D is development version

### ISSUE THREAD

**Issue by vidcon** [Homebrew/legacy-homebrew#46052]
When compiling an application that uses the chipmunk library installed by brew, the application prints:

```
Initializing cpSpace - Chipmunk v7.0.1 (Debug Enabled)
Compile with -DNDEBUG defined to disable debug mode and runtime assertion checks
```

It would be nice to have a flag to tell brew to compile the release version of the library. Or better yet, default to release.

**Comment by mikemcquaid** [comment]
> Or better yet, default to release.

:+1: Should just be a matter of adding this as an argument. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by vidcon** [comment]
I'm not familiar enough with CMake to know what arguments need to be passed to it to generate a release build. From what I can tell, Chipmunk's CMakeLists.txt will never generate a Makefile that has the `-DNDEBUG` option enabled. Unless CMake automatically adds that option when you request a release build? But I doubt that's the case since I think a build type of 'none' is the same as 'release'.

This is probably a bug with Chipmunk - I think I saw the author mention somewhere that someone just sent him a CMakeLists.txt to use instead of writing one himself. (Don't quote me on that)

So, is this something that should be fixed with Chipmunk first, or is there a way to add that cflag when brew calls make as a temporary fix? *Or* am I wrong and just not aware the proper flags for CMake?

**Comment by vidcon** [comment]
@mikemcquaid Can you point me in the right direction? I'd be glad to open a pull request once I know how to proceed.

**Comment by mikemcquaid** [comment]
@vidcon Will look a bit like this:
https://github.com/Homebrew/homebrew/blob/c07e70aeaa9c15314687c416ac763c0800343647/Library/Formula/mysql.rb#L107

but in this case `args << "DNDEBUG" will be sufficient.

**Comment by tdsmith** [comment]
We'll look forward to a pull request if you have a chance.
