### ISSUE TITLE
libpng failed to build on 10.8.5

### ISSUE THREAD

**Issue by alevkon** [Homebrew/legacy-homebrew#46263]
https://gist.github.com/6ee8d7e1d2bf448b7c36
Failure occurs during "make test".
Last lines from: Library/Logs/Homebrew/libpng/03.make:

/usr/bin/make  check-TESTS
PASS: tests/pngtest
PASS: tests/pngvalid-gamma-16-to-8
PASS: tests/pngvalid-gamma-background
PASS: tests/pngvalid-gamma-expand16-background
PASS: tests/pngvalid-gamma-expand16-transform
PASS: tests/pngvalid-gamma-threshold
PASS: tests/pngvalid-gamma-alpha-mode
PASS: tests/pngvalid-gamma-expand16-alpha-mode
PASS: tests/pngvalid-gamma-transform
PASS: tests/pngvalid-progressive-interlace-standard
FAIL: tests/pngvalid-transform
PASS: tests/pngvalid-gamma-sbit
PASS: tests/pngstest-1.8
PASS: tests/pngvalid-progressive-size
PASS: tests/pngvalid-progressive-standard
PASS: tests/pngstest-1.8-alpha
PASS: tests/pngstest-linear
PASS: tests/pngstest-linear-alpha
PASS: tests/pngstest-none
PASS: tests/pngstest-none-alpha
PASS: tests/pngstest-sRGB
PASS: tests/pngstest-sRGB-alpha
PASS: tests/pngunknown-IDAT
PASS: tests/pngunknown-discard
PASS: tests/pngunknown-if-safe
PASS: tests/pngunknown-sAPI
PASS: tests/pngunknown-sTER
PASS: tests/pngunknown-save
PASS: tests/pngunknown-vpAg
PASS: tests/pngimage-quick
PASS: tests/pngvalid-standard
PASS: tests/pngimage-full

Testsuite summary for libpng 1.6.19

TOTAL: 32
PASS:  31
SKIP:  0
XFAIL: 0
FAIL:  1
XPASS: 0
ERROR: 0

See ./test-suite.log
Please report to png-mng-implement@lists.sourceforge.net

make[2]: *** [test-suite.log] Error 1
make[1]: *** [check-TESTS] Error 2
make: *** [check-am] Error 2

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 1eec1361eb8ff216e41ae3ba6da12f2b5ec80d98
Last commit: 32 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.8.5-x86_64
Xcode: 5.0.2
CLT: 4.4.0.0.1.1249367152
GCC-4.2: build 5666
LLVM-GCC: build 2336
Clang: 4.0 build 421
X11: N/A
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65-b14-462

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/xz/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.8
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/xz/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by glennrp** [comment]
Did anything helpful appear in your test-suite.log ?

**Comment by alevkon** [comment]
Looks strange, but I haven't got any test-suite.log file nor in current directory, nor in the Cellar.

**Comment by glennrp** [comment]
That's odd.  You should find pngvalid (executable) in your build directory.  If so, what does running

    ./pngvalid --strict --transform

in that directory say (sorry I don't have access to homebrew to try this myself)

**Comment by DomT4** [comment]
@alevkon Presuming it keeps the log in the buildpath, you'll need to do:

```
brew install libpng --debug
```
And then it won't just die when the build fails, but should give you options to drop into the shell, raise, etc. You can then navigate to `/tmp`, find the build folder and get the log from there, I expect.

**Comment by alevkon** [comment]
Oh yeah.
After `brew install libpng --debug`
I managed to found test-suite.log in the build directory:

    =====================================
    libpng 1.6.19: ./test-suite.log
    =====================================
    
    # TOTAL: 32
    # PASS:  31
    # SKIP:  0
    # XFAIL: 0
    # FAIL:  1
    # XPASS: 0
    # ERROR: 0
    
    .. contents:: :depth: 2
    
    FAIL: tests/pngvalid-transform
    ==============================
    
    pngvalid: read: truecolour 8 bit: transform: +rgb_to_gray(R(0.7165,0.2587,0.0000),G(0.1010,0.7247,0.0512),B(0.1468,0.0166,0.7739))^0.45471: red/gray output value error: rgba(0,29,29,255): 21 expected: 25 (22.118..28.500)
    pngvalid: 1 errors, 0 warnings
                          FAIL: pngvalid --strict --transform (floating point arithmetic)
    FAIL tests/pngvalid-transform (exit status: 1)

**Comment by glennrp** [comment]
Thanks, we will have a look.

**Comment by glennrp** [comment]
I've been discussing this with the author of pngvalid.  He says "There are only two possibilities:
1) The double precision math and rounding to (int) on their version of clang is broken.
2) They have an old pngvalid.c in their source tree."

From your logs, I doubt that "2)" is the case.  Can you try with a different version of clang?

**Comment by mikemcquaid** [comment]
@glennrp It could be the version of Clang on 10.8 is old enough to have bugs.

@alevkon You can use the `--cc=` argument to `brew install` to select a version of GCC. That's probably worth a try instead.

**Comment by alevkon** [comment]
Thank you guys!
The problem was in Clang.

**Comment by UniqMartin** [comment]
Closing as the issue seems to have been resolved. But just in case I missed something: 10.8 is fairly old and no longer officially supported by Homebrew  (as indicated by the output that `brew doctor` provides). We'll happily accept PRs that improve the situation for older OS X releases, but resolving this ourselves is not a priority for us. Thanks for understanding!
