### ISSUE TITLE
Cannot install winetricks while rar formula linked

### ISSUE THREAD

**Issue by xdqi** [Homebrew/legacy-homebrew#46572]
Winetricks formula depends on unrar formula which provides unrar compiled from source. However, rar formula provides unrar compiled by RARLAB too. From documentation there only exists conflicts statement now.
Is there any way to get rar package **conflicts** and also **provides** unrar so that Winetricks can be installed without any pain?

**Comment by apjanke** [comment]
You're referring to the `rar` formula [from homebrew/binary](https://github.com/Homebrew/homebrew-binary/blob/master/rar.rb), right?

Adding the `conflicts` is easy. But I don't think we have a mechanism for saying that a formula provides another formula (only for satisfying special requirements like `:fortran`).

It looks like winetricks will fall back to using 7zip if `unrar` is not found on the system. Maybe we could just change its `unrar` dependency to `:recommended`, so you could `brew install winetricks --without-unrar` and have it live alongside `rar`.

**Comment by DomT4** [comment]
The conflict in this case would be one sided, though. The binary formula could be assumed to know the core `winetricks` exists, but the core `winetricks` cannot be assumed to know about the existence of the binary formula.

**Comment by apjanke** [comment]
I think I've seen `depends_on` references in core formulae referring to dupes or versions. e.g.:

```
$ grep depends * | grep 'dupe\|versions'
apr-util.rb:  depends_on "homebrew/dupes/openldap" => :optional
arp-scan.rb:  depends_on "homebrew/dupes/libpcap" => :optional
crosstool-ng.rb:  depends_on "homebrew/dupes/grep" => :optional
crosstool-ng.rb:  depends_on "homebrew/dupes/make" => :optional
dcmtk.rb:  depends_on "homebrew/dupes/libiconv" => :optional
dex.rb:  depends_on "homebrew/dupes/ncurses" => :optional
imagemagick.rb:  depends_on "homebrew/versions/openjpeg21" if build.with? "jp2"
```

Seems like a `conflicts` would be the same sort of reference. Is that not something we should be doing, even for other repos under the Homebrew organization? Or are dupes/versions special and binary isn't?

(The conflict is between `unrar` and `rar`; not with `winetricks`. `winetricks` just requires the `unrar` binary provided by one of `unrar` or `rar`.)

**Comment by DomT4** [comment]
`optional` works because we're not telling `brew` to go look for it. We only go looking for `=> :optional` and `if build.with?` stuff if those options are invoked. `conflicts_with` are invoked unconditionally on formula load.

**Comment by DomT4** [comment]
(I don't think it actually breaks these days, although it used to *badly*, thanks to changes Xu has made since, but it's not something particularly want to encourage).

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
