### ISSUE TITLE
`etc.install` on dirs can drop stuff inside prior installed dir

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#46788]
The `etc.install` function can end up installing duplicate files in the wrong place when it's used on a directory instead of plain files. On the second `etc.install` call, the directory may be copied under the previously-installed directory, instead of being recognized as a re-install.

Here's an example [from the `kafka` formula](https://github.com/Homebrew/homebrew/blob/68bb46817b99f3f1b6610300b1bab641a3d7e6e1/Library/Formula/kafka.rb#L56-L57). It keeps its config files in a directory called `config`, which we turn in to `kafka` and install at `$(brew --prefix)/etc/kafka`.

```
    mv "config", "kafka"
    etc.install "kafka"
```

If you `brew rm kafka`, that `$(brew --prefix)/etc/kafka` directory is left. On subsequent `brew install kafka`, the config directory gets copied again, to `$(brew --prefix)/etc/kafka/kafka`, with duplicates of all the config files.

On a third `brew install kafka`, it will fail at the installation stage with `Error: File exists - /usr/local/etc/kafka`.

Using `etc`'s "don't clobber" logic, it should either be copying the dir to `$(brew --prefix)/etc/kafka.default`, or it should be using the no-clobber "xxx.default" logic on each of the individual config files inside that directory (probably doing a recursive search to find all files inside the directory structure).

**Comment by mikemcquaid** [comment]
Thanks for the great report :+1:

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
