### ISSUE TITLE
Impossible to install mapserver with PHP

### ISSUE THREAD

**Issue by Namrod21** [Homebrew/legacy-homebrew#46966]
Hi !

I would like to install Mapserver with tht PHP option in order to get the php_mapscript.so file. I do ```brew install mapserver --with-php''', but I get an error :

```==> Patching
patching file mapscript/python/setup.py
Hunk #1 FAILED at 32.
Hunk #2 FAILED at 149.
2 out of 3 hunks FAILED -- saving rejects to file mapscript/python/setup.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1```

I I don't want to install Mapserver from osgeo4mac, with which I had problems with the mapscript PHP and Python modules. I am working with Mac OS W 10.9.5.

**Comment by dunn** [comment]
I see the same thing even without `--with-php`.  Looks like the patches are out-of-date.

If you're up for taking a look upstream as to whether they've been merged or if there are new patches, that'd be great!

**Comment by Namrod21** [comment]
Thanks for your answer. That works fine for me without ```--with-php``` . Where can I see if there are new patches ?

**Comment by dunn** [comment]
Oh, our version of Mapserver is out of date too.  I'm reluctant to spend too much time upgrading it (and switching the build over to CMake), since we're working with the osgeo4mac people to officially take over these formulae: #42151

**Comment by Namrod21** [comment]
Thanks for your answer, but I had problems with the MapServer provided by OSGeo4Mac. For example, the PHP and Python Mapscript extensions does'nt work, whereas the Python Mapscript module works with the classic Mapserver installed with Homebrew...
