### ISSUE TITLE
Audit shouldn't include tap name in description length

### ISSUE THREAD

**Issue by jawshooah** [Homebrew/legacy-homebrew#47033]
Currently, `brew audit --strict` includes the name of the tap when calculating the length of a formula's description. This makes it difficult to pass the audit for formulas in head-only or devel-only taps (e.g. [jawshooah/nodenv-head-only](https://github.com/jawshooah/homebrew-nodenv-head-only)), since the tap name alone takes up much of the 80 character limit.

I understand the reasoning—keep the actual output of `brew desc` within 80 characters. But in the case of the tap linked above, only 52 characters are left to actually describe the formula.

Is there a compelling reason to even include the tap name in the output of `brew desc`?

**Comment by bfontaine** [comment]
> Is there a compelling reason to even include the tap name in the output of `brew desc`?

This prevents the confusion when there are two formulae with the same name in different taps and/or the core.

**Comment by DomT4** [comment]
Yeah, I appreciate the extra tap name is a pain but I'm more with Baptiste here. Maybe we could exclude the tap name from the calculation but still print it, although in some cases that will lead to fairly wide `desc` outputs.

**Comment by jawshooah** [comment]
> This prevents the confusion when there are two formulae with the same name in different taps and/or the core.

I can see how this would be a problem in theory, but when would these descriptions be displayed concurrently? Wouldn't you have to explicitly pass both formulas to `brew desc`, in which case the order would tell you which is which?

**Comment by bfontaine** [comment]
Yeah but it’s probably easier to parse the output if you have the formulae names in it rather than remember the order in which you passed the arguments. You can e.g. pipe the output of `brew desc` to some program that extract each description; something you couldn’t do if the output didn’t include each name.

**Comment by jawshooah** [comment]
Fair enough. I'd settle for just not counting the length of the tap name when auditing the length of the description. It seems awfully constraining.

**Comment by UniqMartin** [comment]
I'm am bit with @jawshooah on this one. It would be nice to exclude the tap name from the count, but still keep a restriction to keep the text on one line for most users, e.g. in the `brew info` output where it isn't prefixed. To keep the listing of `brew desc` nice (one formula per line) when printed to a terminal, we could auto-truncate the descriptions to the terminal width as we already do with other outputs.

**Comment by bfontaine** [comment]
We auto-truncate commands but not text targeted to the users (e.g. the caveats). Truncating the descriptions might give strange results.
I understand your pain as I’ve written descriptions for formulae like `homebrew/completions/boot2docker-completion` (leaving only 35 chars for the description) thought.

**Comment by mikemcquaid** [comment]
I can see an argument for not requiring the 80 character limit and only showing it if the output formulae include multiple with the same short name.

**Comment by crd** [comment]
I submitted a patch to audit.rb to facilitate the conversation -- regardless of what we decide to do with the output of `brew desc` I figured it was safe to loosen restrictions being applied by audit. My apologies if that was premature, I'm new to contributing to homebrew.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
