### ISSUE TITLE
fbida broken again on 10.11 El Capitan

### ISSUE THREAD

**Issue by torenware** [Homebrew/legacy-homebrew#47121]
The problem described in #42489 appears to be happening again using XCode 7.2 (7C68):

While trying to build geeqie, 

````
==> Installing homebrew/x11/geeqie dependency: fbida
==> Downloading http://dl.bytesex.org/releases/fbida/fbida-2.10.tar.gz
Already downloaded: /Library/Caches/Homebrew/fbida-2.10.tar.gz
==> Patching
patching file GNUmakefile
==> make
Last 15 lines from /Users/my_mac/Library/Logs/Homebrew/fbida/01.make:
genthumbnail.c:9:10: fatal error: 'transupp.h' file not found
#include "transupp.h"           /* Support routines for jpegtran */
         ^
exiftran.c:17:10: fatal error: 'transupp.h' file not found
#include "transupp.h"           /* Support routines for jpegtran */
         ^
jpegtools.c:36:10: fatal error: 'transupp.h' file not found
#include "transupp.h"           /* Support routines for jpegtran */
         ^
1 error generated.
make: *** [exiftran.o] Error 1
````
Since the suggested action (install XCode 7 GM) no longer fixes this, the issue needs to be reopened.

**Comment by DomT4** [comment]
Can't reproduce this locally or on our CI; Is this still an issue?

Apologies for the delay. Sometimes we get an influx of Issues and things get shoved off the front page and lost from easy view :cry:.

**Comment by UniqMartin** [comment]
Closing for a lack of response; happy to reopen once there's some activity here. (And I'm equally sorry this went for so long without any feedback from our side!)
