### ISSUE TITLE
Reorganize documentation with ToC and Paths

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#47164]
I'd like to reorganize the documentation in [the `share/doc/homebrew` folder](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew) to make it easier to read as a whole, and easier to find certain topics in it. Spruce up the formatting a bit.

Right now it's a little hard to consume as a whole, because the only list of all the topics is the list of filenames in that directory. The main README links to a few of them, but doesn't cover everything, so it's hard to get an overview or determine a path to read through the whole documentation set, like you would with a book.

Items:
- Add a Table of Contents that includes all the doco pages
 - Grouped by subject area, arranged in something like a sensible front-to-back reading order, with more advanced topics later and prerequisites first
 - Traverse the current links and see if all the pages are actually reachable through the current structure, without resorting to the file listing
- Add a couple "Paths" that list pages under a certain topic or use case
- Review all the pages and restructure them if needed for clarity or to remove redundancy
- Change backtick `\`\`` markup for example code to `<code>...</code>` to allow nesting bold and italic formatting inside the monospace-font code blocks (to indicate placeholders and other syntactic elements)
- Maybe generate an HTML or other directly-consumable version of it so you can read the docs offline instead of having to go through GitHub's repo viewer or an editor for the Markdown rendering? Could be a nicer reading experience overall. Markdown is a developer format, not a great format for readers.
- Move subordinate content like inline images to a `resources` or `images` subdirectory, so only human-facing topic pages remain in the main directory.

Thoughts?

A couple questions:

Do we need to preserve the URLs for the `doc` pages as they're currently presented on GitHub? That is, is the URL `https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/C%2B%2B-Standard-Libraries.md` an official public point of access to this doco that we need to keep working even if we reorganize the doco? Or can we treat this as just part of the repo, and as long as the pages are navigable from wherever users find that `doc/README.md` then we're okay?

(I hope the answer to that is "no"; having the GitHub web view of your main repo be a main public documentation site feels a little wonky to me. At the least we should be pushing it to GitHub Pages or something.)

**Comment by mikemcquaid** [comment]
> Add a Table of Contents that includes all the doco pages

:+1:; should be in `README.md` (or at least symlinked to it) so it displays nicely on GitHub.

> inside the monospace-font code blocks (to indicate placeholders and other syntactic elements)

Would probably rather we relied on the triple-backticks for this to do the syntax highlighting.

> Maybe generate an HTML or other directly-consumable version of it so you can read the docs offline instead of having to go through GitHub's repo viewer or an editor for the Markdown rendering?

I'd probably rather not check these into the repo and instead perhaps add an external command that allows their generation.

> Move subordinate content like inline images to a resources or images subdirectory, so only human-facing topic pages remain in the main directory.

:+1: 

> Do we need to preserve the URLs for the doc pages as they're currently presented on GitHub? That is, is the URL https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/C%2B%2B-Standard-Libraries.md an official public point of access to this doco that we need to keep working even if we reorganize the doco?

Yes.

Also, on this topic, there's 3rd-party sites that can combine end-user and API documentation e.g. http://readthedocs.org and we could/should consider that move perhaps as part of this.

**Comment by zmwangx** [comment]
May I suggest that TOC also be added to individual pages, especially Formula Cookbook, which is a hell of a long document? With [`doctoc`](https://github.com/thlorenz/doctoc) it's just one single command away (be it initial generation or updates).

**Comment by UniqMartin** [comment]
It would be awesome if we can get our documentation to a point where it can be handled by <http://www.mkdocs.org/> and/or <http://readthedocs.org/>. This will then automatically take care of the table of contents.

> Move subordinate content like inline images to a `resources` or `images` subdirectory, so only human-facing topic pages remain in the main directory.

:+1: I'm in favor of `resources` as this leaves us with more flexibility for the future. Maybe you want to tackle this bullet point first? It's relatively easy and will instantly improve the listing. The other stuff sounds a bit more long term to me.

> Do we need to preserve the URLs for the doc pages as they're currently presented on GitHub?

I think we do, unless we absolutely cannot avoid changing them. Those URLs are used in the man page and various other places and it would be quite painful to change that.

> May I suggest that TOC also be added to individual pages, especially Formula Cookbook, which is a hell of a long document? With [`doctoc`](https://github.com/thlorenz/doctoc) it's just one single command away (be it initial generation or updates).

:+1: This sounds like an excellent idea and could bring another almost instant improvement until we move away from reading the files directly on GitHub (if we do). The only problem I see is that it depends on `node` (?) which seems like a too big dependency to force it on everyone who wants to regenerate the TOCs. Is there maybe a pure-Ruby implementation that does the same?

**Comment by zmwangx** [comment]
> The only problem I see is that it depends on node (?) which seems like a too big dependency to force it on everyone who wants to regenerate the TOCs.

Node is a big dependency, but Homebrew makes it a breeze to install :wink: Anyway, it should be easy to manually manipulate the generated TOC, as long as changes are incremental and relatively localized.

> Is there maybe a pure-Ruby implementation that does the same?

I Googled for a few minutes and hardly found anything. I did find out that GitHub's own Markdown implementation [repcarpet](https://github.com/vmg/redcarpet) does seem to have the ability to generate a TOC in the HTML output (`Redcarpet::Render::HTML_TOC`); they just don't use it in production :confused:

**Comment by apjanke** [comment]
@zmwangx:
> May I suggest that TOC also be added to individual pages, especially Formula Cookbook, which is a hell of a long document? With `doctoc` it's just one single command away (be it initial generation or updates).

I like this idea too. Both the per-page TOC and `doctoc` – if I understand it correctly, it just inserts a TOC into the local Markdown document, so it'll degrade gracefully for editors that don't have it, and will be usable for offline viewers as well.

> Node is a big dependency

Well, at least it ain't TeX. ;)

<img width="379" alt="screen shot 2016-01-10 at 2 39 40 am" src="https://cloud.githubusercontent.com/assets/2618447/12220517/73181c9e-b743-11e5-9137-349880b72d96.png">

Using GitHub's `redcarpet` is appealing to me, because we're pretty GitHub-based, and personally I like automatic ToC support, and the more use of it we see in the wild, maybe the more likely GitHub will start supporting live ToC in production Markdown views. And also because if GitHub ever does enable per-page ToC in GitHub-Flavored Markdown, I bet that will become the de facto standard for it in short order, and we'll save a migration.

Whatever tool we use, I would like to see ToCs rendered in static form, certainly in the HTML output, and maybe in the Markdown files themselves. (Or dynamically using widely-available local tools that basic users would be comfortable with, but AFAICT that's not feasible.) So in the worst case, future editors could manually fix up the ToCs using plain old markup. We're talking about mkdocs.org and readthedocs.org (and I have some research to do on those), but I'm a little leery of tying our documentation to a service like that. I'd prefer to have a set of documents which can be used (and authored, preferably) entirely locally, with open tools.

Anyway, take this with a grain of salt. I'm an oldster and accustomed to my local doco installs; I dunno about these newfangled online doco systems with your excessive whitespace and page load latencies.

###  Two Asides   ###

1) I wish Markdown had included a native per-page TOC facility. I see a lot of 60% solutions for it out there.

2) Markdown is an authoring format, not a consumer presentation or distribution format. So we're in a bit of a weird place b/c we only provide the doco in Markdown, to be viewed through GitHub. But, since we're so tied to GitHub in the first place, and pretty focused on developers and power users, maybe that's not a real concern.

Maybe Homebrew's main userbase is a younger audience that would just prefer reading things on GitHub, instead of local `.html` files or the like? Would sticking with GitHub's renderings as the primary presentation serve our users better?

**Comment by zmwangx** [comment]
> Well, at least it ain't TeX. ;)

Actually you may choose to install a basic distribution with a limited set of packages, whose installer http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg is only 112605547 bytes long. I always recommend the full distribution, though.

> I would like to see ToCs rendered in static form, certainly in the HTML output, and maybe in the Markdown files themselves.

+1. I always find local, static documentation nice to have; online documentation is a plus when you have a good connection and know where it is, or need to link to it for someone else.

> I wish Markdown had included a native per-page TOC facility.

There are so many things that I wish Markdown had included...

> Markdown is an authoring format, not a consumer presentation or distribution format.

Actually, Markdown was designed to be readable as plain text in the first place, so a non power user without any Markdown-related skills or tools should be able to open it in TextEdit and read it without problem. (Actually, .md opens in Xcode by default, which even provides some nice syntax highlighting.)

**Comment by apjanke** [comment]
> may choose to install a basic distribution 

I've done BasicTeX before, and it seems like a fine product, but all of the particular TeX use cases I have always seem to need something that's not in it.

And for the record, I'm not really dissing TeX here. TeX is awesome and I'll give 5 GB for what it gives me. That doesn't go for the rest of you software developers out there, though!

> Actually, Markdown was designed to be readable as plain text in the first place...

No disagreement as such. As far as authoring formats go, it is very readable when viewing the source, and that's why it's so popular. (And it's why I use it: all my personal notes are in Markdown now.) But it's still a lousy presentation format, just like plain text is. A normal user can open and make sense of a Markdown document, but it's not an ideal, or even good, reading experience. It's a graceful fallback. I think we can do better than that.

A presentation format like HTML (when opened in a "viewer") gives you proportional fonts, typesetting like bold and italics, nicer spacing between lines and paragraphs. I appreciate that, and think other users would too, especially for longer text pieces. Even as a developer myself, I would not want to read through any of the Homebrew docs in their Markdown source form in a text editor. Even the 
live rendered view through GitHub is kind of a crappy reading experience. Which was a good part of my motivation for bringing this all up in the first place: I wanted to sit down and read through all the documentation on Homebrew, and the available ways of doing that were not great, imho.

**Comment by zmwangx** [comment]
> I've done BasicTeX before, and it seems like a fine product, but all of the particular TeX use cases I have always seem to need something that's not in it.

Anecdote: Many years ago when I was still using Windows and just started learning TeX, I installed a MikTeX *basic* distribution, and the outcome was horrible... Never dared a basic distribution again.

> But it's still a lousy presentation format, just like plain text is.

Yep, no argument here. But Homebrew's always up-to-date nature makes it hard to distribute compiled documentation. Including both source and build product in the repo is no-no. You can add logic to `brew update` to auto compile/fetch updated docs, but (1a) if compile: you need to ship a (fully GFM-compatible) Markdown parser; (1b) if fetch: a separate branch could be created for generated HTML docs, but that's extra work on the bot; alternatively HTML docs could be hosted somewhere, say GH Pages, or RTD, but that would be one extra connection and sort of wasted bandwidth; (2) more importantly, is it really worth it? Do most (or a considerable portion of) users really read from `/usr/local/share/doc/homebrew`?

> Even the live rendered view through GitHub is kind of a crappy reading experience.

Do you dislike GitHub's stylesheet, or do you just find it hard to navigate? Personally I'm okay with GitHub's stylesheet. Actually, except when I take the trouble to precompile with a template, I almost always view my Markdown documents with [`grip`](https://github.com/joeyespo/grip), which renders exactly as GitHub does. I can `cmark foo.md | browser` too, but IMO user agent default stylesheet is even crappier.

**Comment by UniqMartin** [comment]
FYI, see PR #48057 and [ekalinin/github-markdown-toc](https://github.com/ekalinin/github-markdown-toc) for generating the table of contents.

**Comment by mikemcquaid** [comment]
Another option is AsciiDoc which is pretty similar to Markdown, supported on GitHub, has decent HTML (and PDF) output and may support the Table of Contents (I haven't tried, though).

**Comment by zmwangx** [comment]
> Another option is AsciiDoc which is pretty similar to Markdown, supported on GitHub, has decent HTML (and PDF) output and may support the Table of Contents (I haven't tried, though).

AsciiDoc is a nice markup language that is richer than Markdown and has builtin support for TOC (try `asciidoc -a toc input.adoc` or `asciidoc -a toc2 input.adoc`), just that GitHub doesn't generate TOC for AsciiDoc. See for example how https://github.com/asciidoc/asciidoc/blob/master/README.asciidoc is rendered.

P.S. I personally use AsciiDoc to write man pages. So much easier than groff.

**Comment by mikemcquaid** [comment]
> I personally use AsciiDoc to write man pages. So much easier than groff.

Yeh, it could be better for our manpage, at least.

**Comment by MikeMcQuaid** [comment]
Closing in this in favour of a PR at a later point.
