### ISSUE TITLE
Better handle invalid flags

### ISSUE THREAD

**Issue by Amorymeltzer** [Homebrew/legacy-homebrew#47208]
Not the best title, but what I'm talking about is this:

````bash
> brew list --verbose
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
````

I wouldn't call that expected behavior; a user might reasonably be confused what `ls` is doing in there.[1]  The flag is being passed directly to `ls`, which also gives some odd results should someone pass `-latr` for example.  These are probably edge cases but it would be good to fail better, or at least confirm that maintainers actually want `brew list -a` to show `.` and `..` in output.  `brew cat -n`, for example, fails with `No such file or directory`, a proper, `brew`ish response, while `brew info` shows nothing (afaict), which is also fine.

As another case take the difference between `brew list --versions` and `brew list --version`.  I imagine there are other cases as well.

---
1: Not best example since I would expect `--verbose` output for everything, not a failure.
2: Edge case, I know

**Comment by bfontaine** [comment]
Yeah options checking is something we want to do in the future but we need to refactor our whole commands handling before that.

**Comment by UniqMartin** [comment]
Thanks for the input! We're aware of the shortcomings in our option handling and we're slowly working on improving this, thus closing the issue. However, any help with this endeavor is greatly appreciated. :smile_cat:
