### ISSUE TITLE
cabal-install failed to build on 10.6.8

### ISSUE THREAD

**Issue by imrook** [Homebrew/legacy-homebrew#47244]
https://gist.github.com/c9bfd5f41cede866461d

**Comment by imrook** [comment]
I should have noted that a previous build had failed as well with issues reported by `brew doctor`. I corrected the issues, did a `brew rm ghc` and rebuilt, then got the above failure. I found https://github.com/Homebrew/homebrew/issues/12155 and 2bits's suggestion to do the following:
```
brew rm -f ghc cabal-install
brew prune
rm -rf ~/.cabal
brew install ghc
brew install cabal-install
```

After running all of the above commands ghc built successfully. I'm therefore closing this issue.

**Comment by imrook** [comment]
Doh! While ghc did build and install successfully, cabal-install didn't. I'm still having the same problem as reported, reopening.

**Comment by imrook** [comment]
I attempted to bypass the doc building by passing the `--no-doc` switch to bootstrap.sh using the following patch:
```
diff --git a/Library/Formula/cabal-install.rb b/Library/Formula/cabal-install.rb
index 4ea99d8..61b8be3 100644
--- a/Library/Formula/cabal-install.rb
+++ b/Library/Formula/cabal-install.rb
@@ -16,7 +16,7 @@ class CabalInstall < Formula
   fails_with :clang if MacOS.version < :lion # Same as ghc.rb

   def install
-    system "sh", "bootstrap.sh", "--sandbox"
+    system "sh", "bootstrap.sh", "--sandbox", "--no-doc"
     bin.install ".cabal-sandbox/bin/cabal"
     bash_completion.install "bash-completion/cabal"
   end
```
The build gets further, but fails due to a segfault building network:
https://gist.github.com/8eae1cd16c6f6f716616

**Comment by frickler01** [comment]
Can reproduce.
For some reason an ancient version of haddock is installed with ghc.
```
Running Haddock for mtl-2.2.1...
Setup: The program 'haddock' version >=2.0 is required but the version found
at /usr/local/opt/ghc/bin/haddock is version 0.16.1
```

With `--no-doc`:
```
config.status: creating network.buildinfo
config.status: creating include/HsNetworkConfig.h
config.status: include/HsNetworkConfig.h is unchanged
configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg, --with-gcc
Building network-2.6.0.2...
Preprocessing library network-2.6.0.2...
bootstrap.sh: line 288: 13021 Segmentation fault      ./Setup build ${EXTRA_BUILD_OPTS} ${VERBOSE}
```

The only thing I can currently do to survive is use builds from backups back when it still worked.

I'll try patching in a more up-to-date haddock source as a first step.

**Comment by UniqMartin** [comment]
Sorry, but 10.6 is fairly old and not officially supported by Homebrew (as indicated by the output that `brew doctor` provides). If you can come up with a solution, feel free to submit as a PR and we'll happily accept, but currently there's nothing we can help you with directly.
