### ISSUE TITLE
depends_on "opam" breaks superenv path

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/legacy-homebrew#47260]
This is with a different version of llvm.rb that should be going into a PR sometime soonish. You can find the diff [here](https://github.com/aw1621107/homebrew/commit/dbc21a69a8ad4f499d68c9031665c12a56ed04cb)

Running `brew install llvm --HEAD --debug`, dropping into a shell once the CMake config has started, and running `echo $PATH` gives me this:
```
bash-4.3$ echo $PATH
/usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Doing the same but adding `--with-ocaml` produces this result:
```
bash-4.3$ echo $PATH
/Users/awang/.opam/4.02.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Library/ENV/scm:/opt/X11/bin
```

My regular PATH is:
```
/Users/awang/.opam/4.02.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
```

What am I doing wrong that results in an altered PATH at install time? This doesn't happen if I use the formula on master.

Unfortunately, this can have visible effects on the build. At the very least, `--with-compiler-rt` doesn't build a lot of the runtime libraries if `--with-ocaml` is also present.

**Comment by mikemcquaid** [comment]
I'm not sure what's going on here, sorry.

**Comment by aw1621107** [comment]
Never mind the first post, I didn't research this thoroughly enough.

The actual problem looks like `depends_on "opam"` breaks the superenv path.

This is all with unaltered master branch formulas.

Running `brew install llvm --interactive`, then running `echo $PATH` in the resulting shell gets me this:
```
/usr/local/Library/ENV/4.3:/usr/local/opt/xz/bin:/usr/local/opt/cmake/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
Standard superenv path, right?

Now if I add `depends_on "opam"` to line 140 of the `llvm` formula and run `brew install llvm --interactive` followed by `echo $PATH`, I get:
```
/Users/awang/.opam/4.02.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Library/ENV/scm:/opt/X11/bin
```
Which definitely isn't a valid superenv path.

**Comment by aw1621107** [comment]
Ping?

**Comment by mikemcquaid** [comment]
As said: I'm not sure what's going on here.

**Comment by aw1621107** [comment]
:( Wasn't sure if you meant my question was unclear... Time for some debugging

**Comment by aw1621107** [comment]
Alright, it looks like this would happen if `opam` is installed `--with-aspcud`, which is the norm because `aspcud` is recommended. `aspcud` `depends_on "gringo"`, which `depends_on "scons"`.

I found this at line 509 of `formula_installer.rb`:
```
if ARGV.env
  args << "--env=#{ARGV.env}"
elsif formula.env.std? || formula.recursive_dependencies.any? { |d| d.name == "scons" }
  args << "--env=std"
end
```
I saw the warning in `cmd/sh.rb`; does that still apply? Is there any way around this, or will I have to figure out building LLVM in the standard environment?

**Comment by aw1621107** [comment]
Looks similar to #40401, as `scons` would force stdenv

**Comment by mikemcquaid** [comment]
Yeh, the `scons` is the issue then, thanks for digging in. We could see if it's been updated sufficiently to allow it to be used with superenv again.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
