### ISSUE TITLE
More Options for LLVM's Homebrew Formula to Match Its CMake Options?

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/legacy-homebrew#47269]
Should we add more options to LLVM's Homebrew formula than it currently has in order to allow Homebrew end-users to pass more CMake options to the compiler's build system?  In particular, should we update the LLVM formula to account for those options listed on the LLVM website's ['Building LLVM with CMake' page](http://llvm.org/docs/CMake.html) that Homebrew does not currently interface with?

**Comment by RandomDSdevel** [comment]
Whoops, forgot to make a summary of what the current status is where Homebrew and CMake options for LLVM are concerned.  Anyway, here it is:  

Unmapped Homebrew Options We Already Have:  

* For controlling if Homebrew downloads and/or builds certain additional LLVM tools:  
  * `--with-clang`
  * `--with-clang-extra-tools`
  * `--with-compiler-rt`
  * `--with-libcxx`
  * `--with-lld`
  * `--with-lldb`
* For controlling building and linkage:  
  * `--with-python` (makes Homebrew build/link LLVM's Python bindings with its own Python executable.)  

Unmapped Homebrew Options We Might Want:  
* For controlling if Homebrew downloads and/or builds certain additional LLVM tools:  
  * `--with-libcxx-abi` (This may not come into play until LLVM v3.8 comes out, though; I can't remember for sure just now…)  

Mappings We Already Have:  
* Homebrew's `--with-rtti` maps inversely to LLVM's `LLVM_ENABLE_RTTI` CMake build variable.  
* Homebrew's `--without-assertions` option maps inversely to LLVM's `LLVM_ENABLE_ASSERTIONS` CMake build variable.  

LLVM-Internal CMake Build Options/Variables Without Homebrew Equivalents:  
* `LLVM_TARGETS_TO_BUILD`
* `LLVM_BUILD_TOOLS`
* `LLVM_INCLUDE_TOOLS`
* `LLVM_BUILD_EXAMPLES`
* `LLVM_INCLUDE_EXAMPLES`
* `LLVM_BUILD_TESTS`
* `LLVM_INCLUDE_TESTS`
* `LLVM_APPEND_VC_REV`
* `LLVM_ENABLE_THREADS`
* `LLVM_ENABLE_CXX1Y`
* `LLVM_ENABLE_EH` (to control exception support)
* `LLVM_ENABLE_PIC` (This doesn't work from within the Xcode GUI, but should work from the command line; see [LLVM Bugzilla issue #16739](https://llvm.org/bugs/show_bug.cgi?id=16738).)  
* `LLVM_ENABLE_WARNINGS`
* `LLVM_ENABLE_PEDANTIC`
* `LLVM_ENABLE_WERROR`
* `LLVM_ABI_BREAKING_CHECKS`
* `LLVM_BUILD_32_BITS`
* `LLVM_TARGET_ARCH`
* `LLVM_TAGLEGEN`
* `LLVM_LIT_ARGS`
* `LLVM_LIT_TOOLS_PATH`
* `LLVM_ENABLE_FFI`
* `LLVM_EXTERNAL_CLANG_SOURCE_DIR`
* `LLVM_EXTERNAL_LLD_SOURCE_DIR`
* `LLVM_EXTERNAL_POLLY_SOURCE_DIR`
* `LLVM_USE_OPROFILE`
* `LLVM_PROFDATA_FILE`
* `LLVM_USE_INTEL_JITEVENTS`
* `LLVM_ENABLE_ZLIB`
* `LLVM_USE_SANITIZER`
* `LLVM_PARALLEL_COMPILE_JOBS`
* `LLVM_PARALLEL_LINK_JOBS`
* `LLVM_BUILD_DOCS`
* `LLVM_ENABLE_DOXYGEN`
* `LLVM_ENABLE_DOXYGEN_QT_HELP`
* `LLVM_DOXYGEN_QCH_FILENAME`
* `LLVM_DOXYGEN_QHP_NAMESPACE`
* `LLVM_DOXYGEN_QHP_CUST_FILTER_NAME`
* `LLVM_DOXYGEN_QHELPGENERATOR_PATH`
* `LLVM_DOXYGEN_SVG`
* `LLVM_ENABLE_SPHINX`
* `SPHINX_EXECUTABLE`
* `SPHINX_OUTPUT_HTML`
* `SPHINX_OUTPUT_MAN`
* `SPHINX_WARNINGS_AS_ERRORS`
* `LLVM_CREATE_XCODE_TOOLCHAIN`

Homebrew Mappings We Might Want:  
* A set of `--with-docs` options that collectively map to LLVM's `LLVM_BUILD_DOCS`, `LLVM_DOXYGEN_*`, `LLVM_ENABLE_SPHINX`, and `SPHINX_*` options.  
* A `--with-ffi` option mapping to LLVM's `LLVM_ENABLE_FFI` option.  
* A `--with-zlib` option mapping to LLVM's `LLVM_ENABLE_ZLIB` option if a dependency on ZLib isn't already required by Homebrew to build LLVM in the first place.  

Also, please note that these are just my first impressions and that I'm only posting them here to start a discussion as to how Homebrew should map its LLVM formula options to more of the compiler's internal build system's options and variables.  I doubt that Homebrew should expose _all_ of LLVM's internal build options and variables to Homebrew end-users, so we should also consider which ones would be practical to present to them as formula options.  I also think that it would probably be a good idea to turn this issue into a tracking bug once we figure out what we want with respect to the results of the discussion that it starts.

**Comment by aw1621107** [comment]
libc++abi is actually included with libc++ right now; I'm planning on separating the two, though.

I *think* the LLVM_*_TOOLS option refers to the tools folder in the LLVM source tree. Based on what's in there (interpreter, code generator, clang/lld/lldb if applicable), I think that should be left to its default.

And there's a PR to remove `--without-assertions` at #47145, because assertions aren't that useful for release builds, which the formula is currently configured to install.

I tried adding `--with-tests` some time ago, but at the time it prevented the formula from finishing, and now I'm not sure how useful it'd be. With stable releases, the test results aren't going to change, and with `--HEAD` builds, whether the formula completes is almost completely up to chance, depending on whether the latest commit(s) broke something.

I agree that looking into the options you listed at the bottom could be useful. It'd be *really* nice to somehow get profile-guided optimization, too, but that may be more trouble than it's worth...

**Comment by DomT4** [comment]
The LLVM formula is kind of delicate as-is, and bearing in mind we _never_ CI test non-mandatory or recommended options breakage sneaks through.

If people are actually going to use some of the additional options we'll consider the merit of each, but please do bear in mind options included should pass the "Is the maintenance & complication burden worth how many people will use xyz feature" test. Too much of the time, in our experience, the answer to that question is "nope".

**Comment by mikemcquaid** [comment]
> If people are actually going to use some of the additional options we'll consider the merit of each, but please do bear in mind options included should pass the "Is the maintenance & complication burden worth how many people will use xyz feature" test. Too much of the time, in our experience, the answer to that question is "nope".

:+1:

**Comment by RandomDSdevel** [comment]
@aw1621107:  
> libc++abi is actually included with libc++ right now; I'm planning on separating the two, though.

OK, cool.  

> I think the LLVM_*_TOOLS option refers to the tools folder in the LLVM source tree. Based on what's in there (interpreter, code generator, clang/lld/lldb if applicable), I think that should be left to its default.

Sounds good to me.  

> And there's a PR to remove --without-assertions at #47145, because assertions aren't that useful for release builds, which the formula is currently configured to install.  

That's fine for `Release` builds, but what about for `Debug` builds if Homebrew ends up supporting those?  And there might also be `RelWithDebInfo` to consider as well if we decide 'yes' on the latter point…  

> I tried adding --with-tests some time ago, but at the time it prevented the formula from finishing, and now I'm not sure how useful it'd be. With stable releases, the test results aren't going to change, and with --HEAD builds, whether the formula completes is almost completely up to chance, depending on whether the latest commit(s) broke something.  

Ah, I see; that sounds messy!  

> I agree that looking into the options you listed at the bottom could be useful.  …

I _thought_ those options might be good to have!  

> …It'd be really nice to somehow get profile-guided optimization, too, but that may be more trouble than it's worth...

Oh?  How so?  
<hr />
@DomT4:  
> The LLVM formula is kind of delicate as-is, and bearing in mind we never CI test non-mandatory or recommended options breakage sneaks through.  

Perhaps I should leave this to you professionals, then…

> If people are actually going to use some of the additional options we'll consider the merit of each, but please do bear in mind options included should pass the "Is the maintenance & complication burden worth how many people will use xyz feature" test. Too much of the time, in our experience, the answer to that question is "nope".

That's perfectly fine:  the reason I created this issue was initially just to get discussion going.

**Comment by UniqMartin** [comment]
> Perhaps I should leave this to you professionals, then…

I don't think this is the right conclusion to draw. We might be professionals at maintaining Homebrew as a whole, but we are not experts on every single formula we have in Homebrew, especially not on such complex formulae like `llvm`. We need contributors like you who care about a specific piece of software and want to improve the experience for other Homebrew users. Thanks for the work you and others have already put into improving it! :heart:

Our priority in Homebrew core is to have a stable `llvm` formula with reasonable defaults and not too many esoteric options. But here's a suggestion: Create a dedicated tap for an `llvm` formula with a more complete set of options, invite other interested users to work with you on it, experiment with what works and what doesn't, and once an option proves to be useful for a broader audience and has seen some testing, contribute it back to the formula in Homebrew core. How does that sound?

**Comment by RandomDSdevel** [comment]
@UniqMartin:  The reason I said what I did is because I'm not just a novice when it comes to hacking Homebrew, but also when it comes to programming in general.  I know enough about certain pieces of software to use them properly, but not when it comes to dealing with all of the nitty-gritty internal details.  That being the case, what you recommended sounds like it might actually prove to be a relatively simple task to contribute to since it only deals with build configurations, so I might give it a shot anyway and learn something in the process.  Anyway, I'll try looking into the direction you suggested and report back to you guys with any results.

**Comment by gaming-hacker** [comment]
what about this polly option?  is this stable or not?

**Comment by RandomDSdevel** [comment]
@gaming-hacker:  Are you referring to Homebrew's LLVM formula's `--with-polly` option LLVM's `LLVM_EXTERNAL_POLLY_SOURCE_DIR` build variable?  I believe that the former only works with `--HEAD` builds, and I'm not sure how often the latter is used.

**Comment by gaming-hacker** [comment]
the --with-polly option, i've already built from head without it and seem ok...  well so far

**Comment by RandomDSdevel** [comment]
I'll add the `--with-polly` option to my list of LLVM formula options to evaluate when I start my tap, then.

**Comment by UniqMartin** [comment]
@RandomDSdevel Just to save you from wasting time and getting frustrated, you might want to target the recently released LLVM 3.7.1 in your tap and keep an eye on the evolution of the [`llvm` formula in core](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/llvm.rb) (e.g., the recently opened PR #47824) and the formulae in the [`homebrew/versions` tap](https://github.com/Homebrew/homebrew-versions/) (e.g., [`llvm37`](https://github.com/Homebrew/homebrew-versions/blob/master/llvm37.rb)).

**Comment by gaming-hacker** [comment]
good you pushed the new changes and chopped up the formula a bit

i didn't see where in the llvm formula where it passes these args to polly
--enable-polly-gpu-codegen
--with-llvmsrc
--with-llvmobj
--with-cuda

**Comment by aw1621107** [comment]
@gaming-hacker 
>as i didn't see where in the llvm formula where it passes these args to polly configure, or relying on the ENV to pick them up
--enable-polly-gpu-codegen
--with-llvmsrc
--with-llvmobj
--with-cuda

Are `--with-llvmsrc` and `--with-llvmobj` needed? LLVM seems to build just fine without them, and at least at first glance those look like autoconf flags and I believe the LLVM devs are phasing autoconf out in favor of CMake.

I'm not familiar with the other two; the only place they showed up in a quick Google search was in the autoconf script. It could be possible that CMake configures those automatically, or that there are different options that need to be passed to the CMake command

**Comment by aw1621107** [comment]
@RandomDSdevel 

>>And there's a PR to remove --without-assertions at #47145, because assertions aren't that useful for release builds, which the formula is currently configured to install.

>That's fine for Release builds, but what about for Debug builds if Homebrew ends up supporting those? And there might also be RelWithDebInfo to consider as well if we decide 'yes' on the latter point…

I would imagine Homebrew wouldn't add any of the Debug-related builds. To me, Debug builds are primarily for developer use, and if a dev is hacking on LLVM/other parts then I would expect that they would work from a local copy of the LLVM sources.

>>…It'd be really nice to somehow get profile-guided optimization, too, but that may be more trouble than it's worth...

>Oh? How so?

I'm not very sure on the details myself, but it's something like building LLVM once with profiling instrumentation, running it on some stuff to get data, then building LLVM again with the data from the first run. I don't know how useful it'll be because I don't know how critical LLVM compilation speed is...

**Comment by gaming-hacker** [comment]
the performance speed is not critical for a compiler but stability, once it's running, you lock it down. gcc-53 still has some link time optimization problems.   i would never trust a build once lib/bin that works, even a broken clock is right at least once a day.

not to get off on a rant... well ok a small rant
i've had to seriously use debug mode because builds have been to me substandard, i know it's free so i shouldn't bitch too much but i will anyway :-) 

i feel like a brew developer, there are defintely some shoddy builds that easily break or if they installed they're not fully functional.  unless it's a simple binary, the libs just can't be trusted.   

i look the formulas and my own bash configs and there's quite a difference between someone writing a formula to just get a binary/lib built and one that is robust.  i ended up completely wiping my brew and started from scratch.  everything i've built now is robust, everything can be at least buillt from source with a few heads because i dev those.  

 there needs to be some serious regression testing, the tests inside the formuals  are really useless, just to give someone a warm fuzzy feeling.  some binaries shouldn't be released until a few make checks on different systems with different configurations.  maybe someone could set up a build bot somewhere. this is what ffmpeg does.  **http://fate.ffmpeg.org**

  i've damn near spent 2 solid days on imagemagick. and finally got a 16-bit version to build and all tests pass make check.

**Comment by mikemcquaid** [comment]
Can you take this conversation to the mailing list or IRC channel, thanks.

**Comment by mikemcquaid** [comment]
> i've had to seriously use debug mode because builds have been to me substandard, i know it's free so i shouldn't bitch too much but i will anyway :-)

Please don't bitch here, thanks. If there's issues: submit pull-requests to fix them. If you want to just talk about Homebrew: do so on a mailing list. If you want to complain without helping us fix the problems: please don't.

**Comment by gaming-hacker** [comment]
are you insane, i just told you how to fix the problems.  get off your high horse if you can't take criticism.  who made you dictator? 
1. regression testing
2. build bot

**Comment by mikemcquaid** [comment]
@gaming-hacker Please read our Code of Conduct (https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md) before commenting on  Homebrew issues again in future. You're being temporarily blocked from the Homebrew organisation for 24h. If your behaviour continues after that period you'll be blocked permanently.

**Comment by RandomDSdevel** [comment]
@UniqMartin:  
> @RandomDSdevel[:]  Just to save you from wasting time and getting frustrated, you might want to target the recently released LLVM 3.7.1 in your tap and keep an eye on the evolution of the [`llvm` formula in core](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/llvm.rb) (e.g., the recently opened PR #47824) and the formulae in the [`homebrew/versions` tap](https://github.com/Homebrew/homebrew-versions/) (e.g., [`llvm37`](https://github.com/Homebrew/homebrew-versions/blob/master/llvm37.rb)).  

Sound like a good idea to me!  
<hr />
@gaming-hacker:  
> good you pushed the new changes and i saw that formula was old and built everything from head
> 
> as i didn't see where in the llvm formula where it passes these args to polly configure, or relying on the ENV to pick them up
> `--enable-polly-gpu-codegen`
> `--with-llvmsrc`
> `--with-llvmobj`
> `--with-cuda`

Given what @aw1621107 said on the subject, …:  
> Are `--with-llvmsrc` and `--with-llvmobj` needed? LLVM seems to build just fine without them, and at least at first glance those look like autoconf flags and I believe the LLVM devs are phasing autoconf out in favor of CMake.
> 
> I'm not familiar with the other two; the only place they showed up in a quick Google search was in the autoconf script. It could be possible that CMake configures those automatically, or that there are different options that need to be passed to the CMake command

…I'm inclined to agree with him on this at first glance.  If it's really that important to you, please open either a new issue concerning these flags, a new issue at my LLVM tap once I get that set up, or both.  I might look into it anyway since it has to do with build configuration flags, which is what I'm experimenting with, even if you _don't_ need us to pursue this further.  
<hr />
@aw1621107:  
> I would imagine Homebrew wouldn't add any of the Debug-related builds.  To me, Debug builds are primarily for developer use, and[,] if a dev is hacking on LLVM/other parts[,] then I would expect that they would work from a local copy of the LLVM sources.  

That seems logical, so I suppose that my tap shouldn't  support any `CMAKE_BUILD_TYPE`s other than 'Release' (though I _might_ still look into supporting the other options in a non-`master` branch…)  

> I'm not very sure on the details myself, but it's something like building LLVM once with profiling instrumentation, running it on some stuff to get data, then building LLVM again with the data from the first run.  I don't know how useful it'll be because I don't know how critical LLVM compilation speed is...

I'll look into seeing if this is worth supporting in my tap after I've got the basic build options set up.  Any implementation will probably include some kind of test to measure whatever difference in speed there might be to see how much it really matters.  
<hr />
On the discussion that started up between @gaming-hacker and @mikemcquaid:  
First response by @mikemcquaid:  
> Can you take this conversation to the mailing list or IRC channel, thanks.  

Second response by @mikemcquaid:  
> Please don't bitch here, thanks.  If there's issues: submit pull-requests to fix them.  If you want to just talk about Homebrew: do so on a mailing list.  If you want to complain without helping us fix the problems: please don't.  

I definitely agree on both of the points he made, so please take discussion irrelevant to this issue elsewhere, @gaming-hacker.

**Comment by apjanke** [comment]
Maybe options that aren't too obscure should become mandatory, or `:recommended`. I'm thinking specifically of `--with-clang`. About half the core formulae which `depends_on llvm` include the `--with-clang` dependency.

```
$ grep llvm * | grep depends_on
cctools.rb:    depends_on "llvm" => :optional
creduce.rb:  depends_on "llvm" => "with-clang"
crystal-lang.rb:  depends_on "llvm" => :build
doxygen.rb:  depends_on "llvm" => "with-clang" if build.with? "libclang"
emacs-clang-complete-async.rb:  depends_on "llvm" => "with-clang"
ldc.rb:  depends_on "llvm" => :build
ponyc.rb:  depends_on "llvm" => "with-rtti"
rtags.rb:  depends_on "llvm" => "with-clang"
rust.rb:  depends_on "llvm" => :optional
```

It's a bummer to have to build LLVM from source. It's a long build, which is inconvenient for users, and it'll cause CI and Jenkins to time out, as in #48412. For a heavy formula like LLVM, it might behoove us to try hard to not have any non-default options show up as dependencies in core formulae.

Conversely, this may be another reason to avoid adding new options: other formulae might end up picking those options in their dependency, causing a build from source.

**Comment by mikemcquaid** [comment]
@apjanke Yep, I agree with `with-rtti` and `with-clang`.

**Comment by RandomDSdevel** [comment]
@apjanke:  
> Maybe options that aren't too obscure should become mandatory, or `:recommended`.  

OK.  

> …I'm thinking specifically of `--with-clang`.  About half the core formulae which `depends_on llvm` include the `--with-clang` dependency.  
> ```
> $ grep llvm * | grep depends_on
> cctools.rb:    depends_on "llvm" => :optional
> creduce.rb:  depends_on "llvm" => "with-clang"
> crystal-lang.rb:  depends_on "llvm" => :build
> doxygen.rb:  depends_on "llvm" => "with-clang" if build.with? "libclang"
> emacs-clang-complete-async.rb:  depends_on "llvm" => "with-clang"
> ldc.rb:  depends_on "llvm" => :build
> ponyc.rb:  depends_on "llvm" => "with-rtti"
> rtags.rb:  depends_on "llvm" => "with-clang"
> rust.rb:  depends_on "llvm" => :optional
> ```
> …

Right.  


> It's a bummer to have to build LLVM from source.  …

Agreed, but at least it's not as bad as GCC!  (Ugh, three-stage bootstrap by default…)  

> …It's a long build, which is inconvenient for users, and it'll cause CI and Jenkins to time out, as in [#48412](https://github.com/Homebrew/homebrew/pull/48412).  …

That's annoying!  

> …For a heavy formula like LLVM, it might behoove us to try hard to not have any non-default options show up as dependencies in core formulae.  …

OK.  

> …
> Conversely, this may be another reason to avoid adding new options:  other formulae might end up picking those options in their dependency, causing a build from source.  

Yikes!

**Comment by RandomDSdevel** [comment]
@mikemcquaid:  
> @apjanke Yep, I agree with `with-rtti` and `with-clang`.  

OK, then those should probably end up being mandatory or `:recommended` options in my tap's main branch as soon as get started on it (sorry it's taking so long here; my life is a bit more of a mess than I'd like it to be at the moment…)

**Comment by mikemcquaid** [comment]
@RandomDSdevel I think I'd be OK with these living in core rather than a tap.

**Comment by apjanke** [comment]
Yeah. Sorry if I wasn't clear before; I was suggesting making `rtti` and `clang` recommended or mandatory in the core `llvm` formula right away, and not waiting for bubble-up from the other tap. Otherwise, we wouldn't be able to remove the `llvm`-with-build-options dependencies in those other core formulae, which would be the major advantage for core.

If other maintainers are cool with it too, I'll make a separate PR to make those two `:recommended` in the core `llvm` and simplify the deps in those other formulae, and see how it works out. @DomT4, Martin?

**Comment by DomT4** [comment]
I have no objection. The `clang` bit is a slight pain because it'll very likely shove the LLVM builds above our standard 1hr timeout, but we'll can handle PRs for it in the same way we do Rust, Qt5, etc already.

**Comment by apjanke** [comment]
Here we go: #48462

**Comment by apjanke** [comment]
The test borked hard with clang & rtti on by default, failing to compile a C++ "Hello World". Mind chiming in on #48462? Maybe `--with-libcxx` should be on by default, too? I'd think so, since people and I think formulae assume that `clang` can build `C++`, and `--with-clang` produces a `clang++` command.

**Comment by RandomDSdevel** [comment]
@mikemcquaid:  
> @RandomDSdevel I think I'd be OK with these living in core rather than a tap.  
Great!  
<hr />
@apjanke:  
> Yeah.  Sorry if I wasn't clear before; I was suggesting making `roti` and `clang` recommended or mandatory in the core `llvm` formula right away, and not waiting for bubble-up from the other tap.  Otherwise, we wouldn't be able to remove the `llvm`-with-build-options dependencies in those other core formulae, which would be the major advantage for core.  
> 
> If other maintainers are cool with it too, I'll make a separate PR to make those two `:recommended` in the core `llvm` and simplify the deps in those other formulae, and see how it works out.  
That sounds like a good plan going forward to me; that way, I can base my tap off of your guys's work when I finally get around to creating it.  
<hr />
@DomT4:  
> I have no objection.  The `clang` bit is a slight pain because it'll very likely shove the LLVM builds above our standard 1[-]hr[.] timeout, but [we] can handle PRs for it in the same way we do Rust, Qt5, etc[.], already.  
Ah, well; I guess you can't have everything, can you?  (Sigh…)  
<hr />
@apjanke:  
> Here we go:  [#48462](https://github.com/Homebrew/homebrew/pull/48462)
Great!  
<hr />
@apjanke:  
> The test borked hard with clang & rtti on by default, failing to compile a C++ "Hello World".  Mind chiming in on [#48462](https://github.com/Homebrew/homebrew/pull/48462)?  Maybe `--with-libcxx` should be on by default, too?  I'd think so, since people and I think formulae assume that `clang` can build C++, and `--with-clang` produces a `clang++` command.  
That's…weird, to be frank.  You may be on to something there.  I'd have to consult the documentation first to make sure of that, though.  In any case, I've already started following along at the other issue and will chime in there if I have any insight on the problem.

**Comment by apjanke** [comment]
> If other maintainers are cool with it too, I'll make a separate PR to make those two :recommended in the core llvm and simplify the deps in those other formulae, and see how it works out. 

#48462 basically does this. The `:recommended`/`:optional` only applies to the dependency overall, not the the options under it. So the `llvm` dependency stays mandatory inside the `ponyc` formula, just with different options. If you could help me figure that borkage out, or if you can find an alternate change that works, that'd be great (and you can just slap a "Closes #48462" on it if you put in an alternate PR).

Turning on `--with-libcxx` by default seems to break things even worse (per #47149) so I dunno if that's the way to go. I'm at the point of doing reading on LLVM and C++ stdlib selection because I don't know what to try next.

**Comment by RandomDSdevel** [comment]
@apjanke:  How about whoever gets started on this first links to the related PR from here, and then we can both just work on it as time allows?

**Comment by apjanke** [comment]
Sounds good.

**Comment by MikeMcQuaid** [comment]
We don't want to add more options here than we have already.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  I'll do it in my own tap, then, when I (_finally_) get around to it.

**Comment by MikeMcQuaid** [comment]
Thanks!

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  You're welcome!
