### ISSUE TITLE
Current Emscripten formula installs a development version, not a stable one

### ISSUE THREAD

**Issue by statico** [Homebrew/legacy-homebrew#47544]
CC'ing recent contributors @jiegec @stuwil @DomT4 @xu-cheng

The [current homebrew formula for emscripten](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/emscripten.rb) installs 1.35.9. However, 1.35.9 is a development release -- the latest stable is 1.35.0 from the `master` branch, and the latest development release is 1.35.14 in the `incoming` [branch](https://github.com/kripken/emscripten/branches). This is important because the latest development version has some changes that cause compiler errors on the current stable branch.

I would submit a pull request for this myself but I'm knee deep in other work at the moment.

**Comment by mikemcquaid** [comment]
> The current homebrew formula for emscripten installs 1.35.9. However, 1.35.9 is a development release -- the latest stable is 1.35.0 from the master branch, and the latest development release is 1.35.14 in the incoming branch. This is important because the latest development version has some changes that cause compiler errors on the current stable branch.

Can you suggest a comment we can add to the formula file to indicate whether it's a stable or development version just by looking at the verson number?

**Comment by statico** [comment]
@mikemcquaid: To my knowledge there's no way know if a given Emscripten version is in the development or stable track.

**Comment by mikemcquaid** [comment]
> @mikemcquaid: To my knowledge there's no way know if a given Emscripten version is in the development or stable track.

Then I guess we'll probably keep messing this up :sob:

**Comment by UniqMartin** [comment]
`emscripten` since has been updated—hopefully to a stable version. I guess this can be closed.
