### ISSUE TITLE
filter .pyc messages out of sandbox log

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/legacy-homebrew#47640]
Messages of the form `.*Python(\d+) deny file-write-create.*pyc` are just noise and aren't fatal; it would be nice to hide them from the sandbox log summary.

**Comment by mikemcquaid** [comment]
:+1:

**Comment by DomT4** [comment]
No objections.

**Comment by bfontaine** [comment]
We could maybe set `ENV["PYTHONDONTWRITEBYTECODE"] = "1"` to avoid that?

**Comment by tdsmith** [comment]
Either way; filtering has a small risk of filtering out messages we actually care about and setting `PYTHONDONTWRITEBYTECODE` doesn't. Morally, filtering feels a little better because it doesn't change the behavior of the interpreter for the test, but that seems like an unlikely source of bugs.

**Comment by mikemcquaid** [comment]
> We could maybe set ENV["PYTHONDONTWRITEBYTECODE"] = "1" to avoid that?

:+1:

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/brew#683
