### ISSUE TITLE
Erlang linked to wrong OpenSSL on OSX 10.6.8

### ISSUE THREAD

**Issue by jasonholloway** [Homebrew/legacy-homebrew#47681]
Just spent two days (and one night) pulling my hair out with the Erlang package, trying to get it so that its crypto library would load without erroring. Running ```crypto:start().``` would immediately fail, as similarly documented [here](https://trac.macports.org/ticket/45114).

The problem was/is that the Homebrew formula states a dependency on OpenSSL 1.0.2, while Erlang itself indirectly links to OpenSSL 0.9.8 via the ApplicationService and PasswordServer frameworks. My fix was to hack the formula, removing the stated dependency, and changing the ```--with-ssl``` configure argument to look in ```/usr```. Sounds simple, but took me a long time to get there, as Homebrew seemed to be overriding the ```--with-ssl``` argument somehow, and only stopped when the dependency was commented out. 

Now, all is working nicely, with the crypto library linked to the old, system-provided OpenSSL.

Admittedly, Snow Leopard is a bit out of date, but my understanding is that later versions of OSX are also stuck on the old version of OpenSSL, and wouldn't their frameworks also rely on this? In which case Homebrew shouldn't be linking it to the new OpenSSL at all, surely?

**Comment by jasonholloway** [comment]
Worth noting that the MacPorts ticket linked to above reports this affecting 10.7.5 too...

**Comment by mistydemeo** [comment]
I think the issue here is a difference between older and newer versions of OS X; newer versions of OS X are using Apple's own security framework instead of OpenSSL for those libraries. For example, libsasl doesn't link against OpenSSL on OS X 10.11.

**Comment by DomT4** [comment]
Last release of OS X with a link to OpenSSL in `libsasl` was 10.9, FWIW. Everything since is against the Security Framework.

**Comment by UniqMartin** [comment]
Sorry, but 10.6 is fairly old and not officially supported by Homebrew (as indicated by the output that `brew doctor` provides). If you can come up with a solution, feel free to submit as a PR and we'll happily accept, but currently there's nothing we can help you with directly.

**Comment by jasonholloway** [comment]
@UniqMartin If you read the rest of the thread, you'll notice that the same issue affects up to 10.9 (still old, but whatever)

**Comment by jasonholloway** [comment]
(I'm not really suggesting this be reopened btw)

**Comment by UniqMartin** [comment]
@jasonholloway Thanks for pointing that out! I was only skimming the issue and mostly judging by what it was tagged with.

**Comment by jasonholloway** [comment]
and that's fair enough!
