### ISSUE TITLE
httpie - Feature - Include Bash Autocomplete script

### ISSUE THREAD

**Issue by postalservice14** [Homebrew/legacy-homebrew#47690]
It would be cool if the brew install command would give instructions on adding the `httpie-completion.bash` file to your `.bash_profile`.  The completion script is on the root of the repository: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/httpie.rb

**Comment by mikemcquaid** [comment]
It should just be a matter of adding `bash_completion.install "httpie-completion.bash" or similar. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by UniqMartin** [comment]
Has been added to the formula in #50031 about a month ago. Enjoy!
