### ISSUE TITLE
LLVM and libc++abi

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/legacy-homebrew#47858]
Related to #47149.

I've tried contacting the LLVM devs through their mailing list, but haven't gotten [any](http://lists.llvm.org/pipermail/llvm-dev/2015-December/093533.html) [response](http://lists.llvm.org/pipermail/llvm-dev/2016-January/093612.html).

There is a workaround that allows both libc++abi and libc++ to be built without issues, which is mentioned in the comments, but it requires patching the main LLVM CMakeLists.txt.

I'm trying another email, but in the meantime should libc++abi be added back in with the patch?

**Comment by aw1621107** [comment]
Actually, I just realized that they probably have a point; LLVM could be built anywhere, so I'm guessing that the INSTALL_NAME_DIR is set as it is because the programmer is expected to pass `-rpath` arguments to `ld` when compiling.

I think I'll just ask for the ability to set that path through CMake, which would solve our issue without making any assumptions about where LLVM was built.

**Comment by gaming-hacker** [comment]
rpath can be problematic

**Comment by mikemcquaid** [comment]
@gaming-hacker It's not clear what you mean: please elaborate.

**Comment by gaming-hacker** [comment]
depending on the library, who built it or ported it, how well or if maintained, it get problematic with dynamic libs.  if dynamic lib was built with gnu gcc on osx but didn't include rpath or -flat_namespace -undefined suppress or  -undefined,dynamic_lookup and just used dynamic flag, there are flakey issues finding the lib.

**Comment by aw1621107** [comment]
@gaming-hacker libc++abi is part of LLVM, so I'd assume it's pretty well maintained. The rpath issue does have a solution in this particular case, but I'm trying to talk to a LLVM dev to see if there is something I can do upstream.

And would libstdc++ be an issue on OS X? I'd imagine that everything is set to use libc++ by default.

**Comment by mistydemeo** [comment]
Looks like pod2man installs into the wrong location on 10.6:

```
$ brew ls pod2man -v
/usr/local/Cellar/pod2man/4.04/Changes
/usr/local/Cellar/pod2man/4.04/INSTALL_RECEIPT.json
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/darwin-thread-multi-2level/auto/Pod/.packlist
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/darwin-thread-multi-2level/perllocal.pod
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Man.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/ParseLink.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/perlpodstyle
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text/Color.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text/Overstrike.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text/Termcap.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.10.0/Pod/Text.pm
/usr/local/Cellar/pod2man/4.04/LICENSE
/usr/local/Cellar/pod2man/4.04/NOTES
/usr/local/Cellar/pod2man/4.04/README
/usr/local/Cellar/pod2man/4.04/TODO
/usr/local/Cellar/pod2man/4.04/usr/bin/pod2man
/usr/local/Cellar/pod2man/4.04/usr/bin/pod2text
```

vs

```
$ brew ls pod2man -v
/usr/local/Cellar/pod2man/4.04/bin/pod2man
/usr/local/Cellar/pod2man/4.04/bin/pod2text
/usr/local/Cellar/pod2man/4.04/Changes
/usr/local/Cellar/pod2man/4.04/INSTALL_RECEIPT.json
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/5.18.2/darwin-thread-multi-2level/auto/Pod/.packlist
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Man.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/ParseLink.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/perlpodstyle
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text/Color.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text/Overstrike.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text/Termcap.pm
/usr/local/Cellar/pod2man/4.04/lib/perl5/site_perl/Pod/Text.pm
/usr/local/Cellar/pod2man/4.04/Library/Perl/Updates/5.18.2/darwin-thread-multi-2level/perllocal.pod
/usr/local/Cellar/pod2man/4.04/LICENSE
/usr/local/Cellar/pod2man/4.04/NOTES
/usr/local/Cellar/pod2man/4.04/README
/usr/local/Cellar/pod2man/4.04/share/man/man1/perlpodstyle.1
/usr/local/Cellar/pod2man/4.04/share/man/man1/pod2man.1
/usr/local/Cellar/pod2man/4.04/share/man/man1/pod2text.1
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Man.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::ParseLink.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text::Color.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text::Overstrike.3pm
/usr/local/Cellar/pod2man/4.04/share/man/man3/Pod::Text::Termcap.3pm
/usr/local/Cellar/pod2man/4.04/TODO
```

**Comment by mistydemeo** [comment]
(Sorry, wrong issue.)

**Comment by gaming-hacker** [comment]
@aw1621107 yes it can be on osx, it used to be libc++ but the current version of Xcode 7.2 is to old c++ 4.2.1 ancient, i could be wrong but maybe 10.6??? uses libc++??? don't know
*${$OSX_SDK}/usr/include/c++/4.2.1*

**Comment by aw1621107** [comment]
Still no response from devs... Going to go ahead and make the patch

**Comment by aw1621107** [comment]
Just making sure, would it be reasonable to assume that the libraries built by Homebrew are not going anywhere? If those libraries can be moved then there really isn't a solution beyond telling the user to set the rpath correctly

**Comment by aw1621107** [comment]
If anything, I think the LLVM devs might be correct, and it's up to us to customize the install for Homebrew...

CMake is configured to set INSTALL_NAME_DIR to "@rpath", and to set the default RPATH to "@executable_path/../lib". This would be the correct settings for the executables built for LLVM, which are placed into the bin folder.

For anything outside of the LLVM install, you would have to add the path to the LLVM lib directory to the RPATH to allow dyld to correctly link the library.

Does that make sense? libc++abi might not have to have been removed after all, if the LLVM devs are expecting the correct RPATH to be set by the person linking their libraries, not by CMake when the libraries are built.

**Comment by manphiz** [comment]
@aw1621107 Using their bugzilla may be preferred over mailing list, though I'd expect the treatment may be the same. Anyway, I'm not against adding libc++abi back so that people know what's going on can play with it. However it should not be enabled with libc++. Just give it a separate option and mark it experimental or expert only.

**Comment by aw1621107** [comment]
@manphiz Sounds good to me

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
