### ISSUE TITLE
git-annex failed to build on 10.6.8

### ISSUE THREAD

**Issue by imrook** [Homebrew/legacy-homebrew#47905]
Installation of the Hakell Platform is currently blocked by https://github.com/Homebrew/homebrew/issues/47244 for me, so I installed via the OS X binary packages and linked using `brew link` `brew info git-annex` reports that all dependencies are satisfied, however the install fails because cabal can't find the ghc binary: https://gist.github.com/633d362da5c90158faf2.

**Comment by imrook** [comment]
Clearly the problem has to do with `ghc` not being in the `PATH`. I'm not that great with homebrew yet, so I'm attempting to add `/usr/local/bin` to the path during building with the following patch: https://gist.github.com/imrook/945fc807703ca0deff23. I'll follow-up after the build completes.

**Comment by imrook** [comment]
After modifying my path as in the above comment the build gets farther, but cabal fails to install some dependencies which results in the build failing. The logs are here: https://gist.github.com/6595a8cbdbf3294a422e

**Comment by mistydemeo** [comment]
Looks like it failed here:

```
<command line>: can't load .so/.DLL for: /Library/Haskell/ghc-7.10.3-x86_64/lib/hashable-1.2.3.3/libHShashable-1.2.3.3-4jaFnfhI31RDC6zNCVPxTQ-ghc7.10.3.dylib (dlopen(/Library/Haskell/ghc-7.10.3-x86_64/lib/hashable-1.2.3.3/libHShashable-1.2.3.3-4jaFnfhI31RDC6zNCVPxTQ-ghc7.10.3.dylib, 5): Library not loaded: @rpath/libHStext-1.2.1.3-JOyZu3Wo29WBp8mKbmtC1o-ghc7.10.3.dylib
  Referenced from: /Library/Haskell/ghc-7.10.3-x86_64/lib/hashable-1.2.3.3/libHShashable-1.2.3.3-4jaFnfhI31RDC6zNCVPxTQ-ghc7.10.3.dylib
  Reason: image not found)
```

This is definitely being caused by the non-Homebrew ghc you're using, which isn't something we provide support for unfortunately.

**Comment by imrook** [comment]
My intent isn't to run a non-homebrew ghc, it was an attempt at a workaround for https://github.com/Homebrew/homebrew/issues/47244 I'd like to be able to `brew install git-annex` but 47244 needs to be resolved before that can work. I'm happy to try any patches or manual steps that the community suggests as I'm new to the world of haskell.

**Comment by UniqMartin** [comment]
Sorry, but 10.6 is fairly old and not officially supported by Homebrew (as indicated by the output that `brew doctor` provides). If you can come up with a solution, feel free to submit as a PR and we'll happily accept, but currently there's nothing we can help you with directly.
