### ISSUE TITLE
wine failed to build on 10.6.8

### ISSUE THREAD

**Issue by Shytor** [Homebrew/legacy-homebrew#48053]
https://gist.github.com/eae50297008045d170a8

A little lost on this, I must admit I'm not quite sure what the error is. Any help would be appreciated.

I had to clear out some lib items to get this far, but i've left the jack files there, since i do use that. Not sure if that is the problem or if i just need to update... well everything.

**Comment by Shytor** [comment]
Last 15 lines from /Users/Shytor/Library/Logs/Homebrew/wine/02.make:
  ../../libs/port/libwine_port.a -lXext -lX11 -L/usr/local/opt/openssl/lib -L/usr/local/opt/fontconfig/lib -L/usr/local/opt/libtool/lib -L/usr/local/opt/freetype/lib -L/usr/local/opt/libpng/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -L/opt/X11/lib -arch i386
../../tools/winegcc/winegcc -o windowscodecs.dll.so -B../../tools/winebuild -m32 -shared windowscodecs.spec bitmap.o \
  bmpdecode.o bmpencode.o clipper.o clsfactory.o colorcontext.o colortransform.o converter.o \
  fliprotate.o gifformat.o icnsformat.o icoformat.o imgfactory.o info.o jpegformat.o main.o \
  metadatahandler.o palette.o pngformat.o propertybag.o proxy.o regsvr.o scaler.o stream.o \
  tgaformat.o tiffformat.o ungif.o dlldata.o windowscodecs_wincodec_p.o version.res \
  windowscodecs_wincodec_r.res -luuid -lole32 -loleaut32 -lrpcrt4 -lshlwapi -luser32 -lgdi32 \
  -ladvapi32 -lwine ../../libs/port/libwine_port.a -framework ApplicationServices -L/usr/local/opt/openssl/lib -L/usr/local/opt/fontconfig/lib -L/usr/local/opt/libtool/lib -L/usr/local/opt/freetype/lib -L/usr/local/opt/libpng/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -L/opt/X11/lib -arch i386
../../tools/winegcc/winegcc -o windowscodecs.dll.fake -B../../tools/winebuild -m32 -shared windowscodecs.spec bitmap.o \
  bmpdecode.o bmpencode.o clipper.o clsfactory.o colorcontext.o colortransform.o converter.o \
  fliprotate.o gifformat.o icnsformat.o icoformat.o imgfactory.o info.o jpegformat.o main.o \
  metadatahandler.o palette.o pngformat.o propertybag.o proxy.o regsvr.o scaler.o stream.o \
  tgaformat.o tiffformat.o ungif.o dlldata.o windowscodecs_wincodec_p.o version.res \
  windowscodecs_wincodec_r.res -luuid -lole32 -loleaut32 -lrpcrt4 -lshlwapi -luser32 -lgdi32 \
  -ladvapi32 -lwine ../../libs/port/libwine_port.a -framework ApplicationServices -L/usr/local/opt/openssl/lib -L/usr/local/opt/fontconfig/lib -L/usr/local/opt/libtool/lib -L/usr/local/opt/freetype/lib -L/usr/local/opt/libpng/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -L/opt/X11/lib -arch i386
clang version 1.0 (http://llvm.org/svn/llvm-project/cfe/tags/Apple/clang-23 exported)
Target: x86_64-apple-darwin10

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
allow 'with-win64' option for 64 bit wine builds https://github.com/Homebrew/homebrew/issues/47428
failed to install wine when configuring gd https://github.com/Homebrew/homebrew/issues/35831

**Comment by mistydemeo** [comment]
```
/usr/bin/gcc-4.2 -m32 -c -o url.o url.c -I. -I../../include -D__WINESRC__ -D_REENTRANT -fPIC -Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wstrict-prototypes \
  -Wwrite-strings -Wpointer-arith -fno-omit-frame-pointer -I/usr/local/opt/openssl/include \
  -I/usr/local/opt/fontconfig/include -I/usr/local/opt/libtool/include \
  -I/usr/local/opt/freetype/include -I/usr/local/opt/libpng/include -I/opt/X11/include \
  -I/opt/X11/include/freetype2 -I/usr/include/libxml2 -Os -w -pipe -march=core2 -msse4.1 -mmacosx-version-min=10.6 -m32 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
cocoa_opengl.m: In function ‘-[WineOpenGLContext clearToBlackIfNeeded]’:
cocoa_opengl.m:102: error: ‘GL_DRAW_FRAMEBUFFER_BINDING’ undeclared (first use in this function)
cocoa_opengl.m:102: error: (Each undeclared identifier is reported only once
cocoa_opengl.m:102: error: for each function it appears in.)
cocoa_opengl.m:103: error: ‘GL_DRAW_FRAMEBUFFER’ undeclared (first use in this function)
```

Reads like an issue with the version of OpenGL in OS X 10.6.8.

**Comment by UniqMartin** [comment]
Sorry, but 10.6 is fairly old and not officially supported by Homebrew (as indicated by the output that `brew doctor` provides). If you can come up with a solution, feel free to submit as a PR and we'll happily accept, but currently there's nothing we can help you with directly.
