### ISSUE TITLE
'You haven't updated Homebrew in a while.' seconds after running brew update

### ISSUE THREAD

**Issue by mikemaccana** [Homebrew/legacy-homebrew#48438]
On Homebrew 0.9.5 (git revision f5978; last commit 2016-01-25):

    $ date; brew update; date; brew install etherpeg

    Mon 25 Jan 2016 14:15:57 GMT

    Already up-to-date.

    Mon 25 Jan 2016 14:16:01 GMT

    Error: No available formula with the name "etherpeg"
    ==> Searching for similarly named formulae...
    Error: No similarly named formulae found.
    ==> Searching taps...
    Error: No formulae found in taps.
    ==> You haven't updated Homebrew in a while.
    A formula for etherpeg might have been added recently.
    Run `brew update` to get the latest Homebrew updates!

Clearly `You haven't updated Homebrew in a while.` is incorrect.

**Comment by bfontaine** [comment]
What does `stat $(brew --prefix)/.git/refs/heads/master` say?

**Comment by mikemaccana** [comment]
$ stat $(brew --prefix)/.git/refs/heads/master
16777218 52814285 -rw-r--r-- 1 mike admin 0 41 "Jan 25 14:16:00 2016" "Aug  9 21:39:12 2015" "Oct  1 11:53:59 2015" "Aug  9 21:39:12 2015" 4096 8 0 /usr/local/.git/refs/heads/master

**Comment by bfontaine** [comment]
cc @xu-cheng.

**Comment by UniqMartin** [comment]
Just out of curiosity and because it might (or might not) give a hint at what's wrong: What's the output of `stat $(brew --repo)/.git/packed-refs` and `cat $(brew --repo)/.git/packed-refs`?

**Comment by xu-cheng** [comment]
Sorry for late reply. Could you run `brew config` and `brew doctor` and paste the output? Thanks.

**Comment by mikemaccana** [comment]
Sure @xu-cheng:

    $ brew config; echo; brew doctor
    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew.git
    HEAD: f5978a8a7e0de55fe437c534c260b7fa282dc6b6
    Last commit: 2 days ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: quad-core 64-bit haswell
    OS X: 10.11.2-x86_64
    Xcode: 7.2
    CLT: N/A
    Clang: 7.0 build 700
    X11: N/A
    System Ruby: 2.0.0-p645
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: 1.8.0_25

    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected dylibs:
        /usr/local/lib/libfdb_c.dylib

    Warning: Unbrewed header files were found in /usr/local/include.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected header files:
        /usr/local/include/foundationdb/fdb_c.h
        /usr/local/include/foundationdb/fdb_c_options.g.h
        /usr/local/include/node/android-ifaddrs.h
        /usr/local/include/node/ares.h
        /usr/local/include/node/ares_version.h
        /usr/local/include/node/libplatform/libplatform.h
        /usr/local/include/node/nameser.h
        /usr/local/include/node/node.h
        /usr/local/include/node/node_buffer.h
        /usr/local/include/node/node_internals.h
        /usr/local/include/node/node_object_wrap.h
        /usr/local/include/node/node_version.h
        /usr/local/include/node/openssl/aes.h
        /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
        /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
        /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
        /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
        /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
        /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
        /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
        /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
        /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
        /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
        /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
        /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
        /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
        /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
        /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
        /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
        /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
        /usr/local/include/node/openssl/asn1.h
        /usr/local/include/node/openssl/asn1_mac.h
        /usr/local/include/node/openssl/asn1t.h
        /usr/local/include/node/openssl/bio.h
        /usr/local/include/node/openssl/blowfish.h
        /usr/local/include/node/openssl/bn.h
        /usr/local/include/node/openssl/buffer.h
        /usr/local/include/node/openssl/camellia.h
        /usr/local/include/node/openssl/cast.h
        /usr/local/include/node/openssl/cmac.h
        /usr/local/include/node/openssl/cms.h
        /usr/local/include/node/openssl/comp.h
        /usr/local/include/node/openssl/conf.h
        /usr/local/include/node/openssl/conf_api.h
        /usr/local/include/node/openssl/crypto.h
        /usr/local/include/node/openssl/des.h
        /usr/local/include/node/openssl/des_old.h
        /usr/local/include/node/openssl/dh.h
        /usr/local/include/node/openssl/dsa.h
        /usr/local/include/node/openssl/dso.h
        /usr/local/include/node/openssl/dtls1.h
        /usr/local/include/node/openssl/e_os2.h
        /usr/local/include/node/openssl/ebcdic.h
        /usr/local/include/node/openssl/ec.h
        /usr/local/include/node/openssl/ecdh.h
        /usr/local/include/node/openssl/ecdsa.h
        /usr/local/include/node/openssl/engine.h
        /usr/local/include/node/openssl/err.h
        /usr/local/include/node/openssl/evp.h
        /usr/local/include/node/openssl/hmac.h
        /usr/local/include/node/openssl/idea.h
        /usr/local/include/node/openssl/krb5_asn.h
        /usr/local/include/node/openssl/kssl.h
        /usr/local/include/node/openssl/lhash.h
        /usr/local/include/node/openssl/md4.h
        /usr/local/include/node/openssl/md5.h
        /usr/local/include/node/openssl/mdc2.h
        /usr/local/include/node/openssl/modes.h
        /usr/local/include/node/openssl/obj_mac.h
        /usr/local/include/node/openssl/objects.h
        /usr/local/include/node/openssl/ocsp.h
        /usr/local/include/node/openssl/opensslconf.h
        /usr/local/include/node/openssl/opensslv.h
        /usr/local/include/node/openssl/ossl_typ.h
        /usr/local/include/node/openssl/pem.h
        /usr/local/include/node/openssl/pem2.h
        /usr/local/include/node/openssl/pkcs12.h
        /usr/local/include/node/openssl/pkcs7.h
        /usr/local/include/node/openssl/pqueue.h
        /usr/local/include/node/openssl/rand.h
        /usr/local/include/node/openssl/rc2.h
        /usr/local/include/node/openssl/rc4.h
        /usr/local/include/node/openssl/ripemd.h
        /usr/local/include/node/openssl/rsa.h
        /usr/local/include/node/openssl/safestack.h
        /usr/local/include/node/openssl/seed.h
        /usr/local/include/node/openssl/sha.h
        /usr/local/include/node/openssl/srp.h
        /usr/local/include/node/openssl/srtp.h
        /usr/local/include/node/openssl/ssl.h
        /usr/local/include/node/openssl/ssl2.h
        /usr/local/include/node/openssl/ssl23.h
        /usr/local/include/node/openssl/ssl3.h
        /usr/local/include/node/openssl/stack.h
        /usr/local/include/node/openssl/symhacks.h
        /usr/local/include/node/openssl/tls1.h
        /usr/local/include/node/openssl/ts.h
        /usr/local/include/node/openssl/txt_db.h
        /usr/local/include/node/openssl/ui.h
        /usr/local/include/node/openssl/ui_compat.h
        /usr/local/include/node/openssl/whrlpool.h
        /usr/local/include/node/openssl/x509.h
        /usr/local/include/node/openssl/x509_vfy.h
        /usr/local/include/node/openssl/x509v3.h
        /usr/local/include/node/pthread-fixes.h
        /usr/local/include/node/smalloc.h
        /usr/local/include/node/stdint-msvc2008.h
        /usr/local/include/node/tree.h
        /usr/local/include/node/uv-aix.h
        /usr/local/include/node/uv-bsd.h
        /usr/local/include/node/uv-darwin.h
        /usr/local/include/node/uv-errno.h
        /usr/local/include/node/uv-linux.h
        /usr/local/include/node/uv-sunos.h
        /usr/local/include/node/uv-threadpool.h
        /usr/local/include/node/uv-unix.h
        /usr/local/include/node/uv-version.h
        /usr/local/include/node/uv-win.h
        /usr/local/include/node/uv.h
        /usr/local/include/node/v8-debug.h
        /usr/local/include/node/v8-platform.h
        /usr/local/include/node/v8-profiler.h
        /usr/local/include/node/v8-testing.h
        /usr/local/include/node/v8-util.h
        /usr/local/include/node/v8-version.h
        /usr/local/include/node/v8.h
        /usr/local/include/node/v8config.h
        /usr/local/include/node/v8stdint.h
        /usr/local/include/node/zconf.h
        /usr/local/include/node/zlib.h

    Warning: Broken symlinks were found. Remove them with `brew prune`:
        /usr/local/bin/apm
        /usr/local/bin/atom
        /usr/local/bin/azure
        /usr/local/bin/bower
        /usr/local/bin/cson2json
        /usr/local/bin/derby
        /usr/local/bin/json2cson
        /usr/local/bin/jsonlint
        /usr/local/bin/pjv
        /usr/local/lib/node_modules/node-inspector/node_modules/.bin/wscat

    Warning: Some installed formula are missing dependencies.
    You should `brew install` the missing dependencies:

        brew install gettext

    Run `brew missing` for more details.

    Warning: Your Homebrew is outdated.
    You haven't updated for at least 24 hours. This is a long time in brewland!
    To update Homebrew, run `brew update`.

**Comment by mikemaccana** [comment]
Sure @UniqMartin: 

    $ stat $(brew --repo)/.git/packed-refs; echo; cat $(brew --repo)/.git/packed-refs
    stat: /usr/local/.git/packed-refs: stat: No such file or directory

    cat: /usr/local/.git/packed-refs: No such file or directory

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by daryl-williams** [comment]
This happening on my system. After trying to install Electron using brew I got the following output:

Error: No available formula with the name "electron"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
These formulae were found in taps:
Caskroom/cask/electron-api-demos                                    Caskroom/cask/electron                                              Caskroom/cask/electronic-wechat                                     Caskroom/versions/beaker-electron
To install one of them, run (for example):
  brew install Caskroom/cask/electron-api-demos
==> You haven't updated Homebrew in a while.
A formula for electron might have been added recently.
Run `brew update` to get the latest Homebrew updates!

I then ran brew update with the following output:

$ brew update
Fetching /usr/local...
Fetching /usr/local/Library/Taps/homebrew/homebrew-core...
remote: Counting objects: 20, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 20 (delta 15), reused 16 (delta 11), pack-reused 0
Unpacking objects: 100% (20/20), done.
From https://github.com/Homebrew/homebrew-core
   a3da2d1..4588a12  master     -> origin/master
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 2), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/Homebrew/brew
   8b04d43..db2e9b8  master     -> origin/master

Already up-to-date.

I am including the output from stat $(brew --prefix)/.git/refs/heads/master:

$ stat $(brew --prefix)/.git/refs/heads/master
16777220 43862654 -rw-r--r-- 1 daryl staff 0 41 "Aug 17 13:29:35 2016" "Aug 10 08:23:46 2016" "Aug 10 08:23:46 2016" "Aug 10 08:23:46 2016" 4096 8 0 /usr/local/.git/refs/heads/master

and stat $(brew --repo)/.git/packed-refs:

$ stat $(brew --repo)/.git/packed-refs
16777220 34814563 -rw-r--r-- 1 daryl staff 0 352 "Aug 17 13:29:35 2016" "Mar 31 10:58:34 2016" "May 25 10:26:34 2016" "Mar 31 10:58:34 2016" 4096 8 0 /usr/local/.git/packed-refs

and cat $(brew --repo)/.git/packed-refs:

$ cat $(brew --repo)/.git/packed-refs
# pack-refs with: peeled fully-peeled
40bde0c20e46906524ccf0e7534e03cf5e6a4d0e refs/heads/master
6305d2dbb88ee17edfe7b841b9267bf1bbba0f0a refs/remotes/origin/gh-pages
e4e1507e810fcb81d187b1d33fc9225725d6c306 refs/remotes/origin/go
40bde0c20e46906524ccf0e7534e03cf5e6a4d0e refs/remotes/origin/master
c1ecd6308d94e26c008887554e810b1eccb696e6 refs/stash

and brew config:

$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0c6e307eef57c48d03e1213112d3edd597ce5a7b
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bcb5cf680ae83de77e0ab35657f6d7fd014b28a0
Core tap last commit: 7 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45
OS X: 10.11.6-x86_64
Xcode: 7.3.1 => /Users/daryl/Projects/Development/cmake-2.8.11.1/Tests/BundleGeneratorTest/_CPack_Packages/Darwin/Bundle/BundleGeneratorTest-0.1-Darwin/Applications/Xcode.app/Contents/Developer
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11

and brew doctor:

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default OS X filesystem is case-insensitive. Please report any apparent problems.

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
    openssl


Any help would be much appreciated.

Daryl Williams

**Comment by UniqMartin** [comment]
@daryl-williams Unfortunately, you've been bitten by a major update bug we had introduced a few days ago. To quote from [our README](https://github.com/Homebrew/brew#update-bug) over at the [Homebrew/brew](https://github.com/Homebrew/brew) repository:

> If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run:
>
> ```
> cd $(brew --repo); git fetch; git reset --hard origin/master; brew update
> ```

Note that this repository is no longer actively used, thus in the future you'll be usually better off looking for solutions at [Homebrew/brew](https://github.com/Homebrew/brew) rather than commenting in closed issues like this one.
