### ISSUE TITLE
rtorrent builds on 10.11.3 but exits with segfault

### ISSUE THREAD

**Issue by 2600box** [Homebrew/legacy-homebrew#48675]
I am getting a segfault from rtorrent installed on fresh 10.11.3. It is inconsistent and will crash with a segfault at load when checking files and connecting to trackers. Usually a reboot will allow it to start again.

i am building with xmlrpc.

```
$rtorrent
Caught Illegal instruction, dumping stack:
0   rtorrent                            0x00000001081771b8 _Z8do_panici + 128
Abort trap: 6
```

https://gist.github.com/2600box/c99b8597edb0eeed7435

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by 2600box** [comment]
Hi, I updated the issue with the required information in a gist as requested. Please let me know if you require anything further.

**Comment by MikeMcQuaid** [comment]
We've boneyarded `rtorrent` now so we don't support it any longer.
