### ISSUE TITLE
$(brew --prefix)/var/postgres owned by root if postgres launchctl is still running

### ISSUE THREAD

**Issue by kevinburkeshyp** [Homebrew/legacy-homebrew#48766]
From #48558, if I load the `homebrew.mxcl.postgresql.plist` file, and then attempt to install/upgrade Postgres, `$(brew --prefix)/var/postgres` is owned by the root user.

I verified this by running the following - `Shyp/packages/postgresql` is an exact copy of the formula here: https://github.com/Homebrew/homebrew/blob/f8509e6/Library/Formula/postgresql.rb

```
$ launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist; \
    brew uninstall postgresql; \
    sudo rm -rf /opt/boxen/homebrew/var/postgres; \
    brew install --verbose Shyp/packages/postgresql > /tmp/install-postgresql.log 2>&1 ;
```

This creates the directory with the correct permission:

```
$ ll /opt/boxen/homebrew/var | grep postgres
drwx------  23 burke  staff   782B Feb  2 14:54 postgres
```

If I instead load Postgres, then uninstall/reinstall, the directory is owned by root:

```
$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist; \
    brew uninstall postgresql; \
    sudo rm -rf /opt/boxen/homebrew/var/postgres; \
    brew install --verbose Shyp/packages/postgresql > /tmp/install-postgresql.log 2>&1 ;
```

```
$ ll /opt/boxen/homebrew/var | grep postgres
drwxr--r--   2 root   staff    68B Feb  2 14:57 postgres
```

I tested this workflow several times to verify it that the command above causes the permission difference. Here's a Gist of a verbose install, for what it's worth - this one had the permission error. https://gist.github.com/kevinburkeshyp/2b3602178969e665018e

**Comment by mikemcquaid** [comment]
Can you try to add `var.mkpath` into `postgresql.rb` and then reinstall? I think that'll fix it. If it does: could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by aviflax** [comment]
I just encountered this today.

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/brew/issues/445.
