### ISSUE TITLE
Building bottles on Travis CI and uploading bottles to AWS S3 for Linuxbrew

### ISSUE THREAD

**Issue by sjackman** [Homebrew/legacy-homebrew#48832]
What are the thoughts/plans for building bottles on Travis CI?

I've set up Linuxbrew to upload artifacts (bottles) from Travis CI to AWS S3. Travis CI unfortunately does not currently support uploading bottles from pull requests ([SO](http://stackoverflow.com/a/19849051/423153)). The bottles will have to be built and uploaded when the pull request is merged into `master`.

Is there a command-line option for `brew test-bot` to enable building bottles for even for `master` branch builds? From reading the source code, it looks as though I need to disable adding the `--ci-master` and `--fast` options that are added to the command line when the `TRAVIS` environment variable is defined and `TRAVIS_PULL_REQUEST` is not defined. See https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/test-bot.rb#L840

**Comment by mikemcquaid** [comment]
> What are the thoughts/plans for building bottles on Travis CI?

The documentation was unclear so I hoped that artifact/bottle upload could be coaxed to work for pull requests (as deployments explicitly say that cannot be). I think we'll need to try and work something out with Travis so that it's possible but managing the credentials is the tricky bit (they need to only be passed as environment variables in an image/build where there has been no user configuration).

> Is there a command-line option for brew test-bot to enable building bottles for even for master branch builds?

There is not but we'd review a PR to allow adding e.g. `--bottle` to do so.

**Comment by xu-cheng** [comment]
If Travis doesn't support to pass token only for artifacts upload phase, I would strongly suggest for different approach then Travis to build bottle.

Fundamentally, we need to make sure token never being exposed during compiling formulae(this includes build job for master branch). Otherwise, we will lose integrity for our entire bottle  infrastructure.

**Comment by sjackman** [comment]
1. The token environment variables need to be set only for the artifact upload stage.
2. The `addons.artifacts.paths` configuration variable must be unmodified from upstream, because it can contain shell commands that could expose the key. One way to enforce this restriction is to disable artifacts upload if the submitter has modified `.travis.yml` at all in the pull request.

I feel that these two restrictions should be fairly easy to implement. I'll submit a feature request upstream to Travis and see if it generates any interest.

**Comment by sjackman** [comment]
I've posted a feature request on Travis CI: https://github.com/travis-ci/travis-ci/issues/5579

**Comment by sjackman** [comment]
Circle CI permits uploading artifacts from pull requests after enabling "Permissive building of fork pull requests". It doesn't say so in the documentation, but I asked support. The artifacts are uploaded to Amazon S3. There is not yet any size limits on the files uploaded. Credentials are set in environment variables. I'm not yet sure how security is handled to avoid exposing the credentials.

Would you be interested in trying out Circle?
https://circleci.com/docs/build-artifacts
https://circleci.com/docs/environment-variables for credentials

**Comment by sjackman** [comment]
Quoth the e-mails:

Hi. Is it possible to upload artifacts from a contributing user’s pull request?

> Yes, it's possible but that requires you enable "Permissive building of fork pull requests" setting that allows PR to run a build. If you enable that, your project runs a build from PR and therefore you should be able to upload artifacts just like usual.

Are the bottle artifacts stored on the CircleCI server? If so, what are the limits on the size of these artifacts? Is there a method of securely storing credentials to upload these artifacts to another service, such as Bintray or Amazon S3?

> The artifacts are stored on S3 already, there are no size limits at this time. You can feel free to upload them wherever you would like the best way to store sensitive credentials are in ENVARS. https://circleci.com/docs/environment-variables

**Comment by xu-cheng** [comment]
@sjackman I suggest we create a test repository(not necessary whole Homebrew, any upload job should do it) to test such feature on Circle CI. Especially we can test against its security by sending malicious PR.

**Comment by mikemcquaid** [comment]
> Would you be interested in trying out Circle?

@sjackman I'm also talking to them currently :grinning:

**Comment by sjackman** [comment]
=) Great minds…
