### ISSUE TITLE
Missing smbclient extension...

### ISSUE THREAD

**Issue by alfista-sk** [Homebrew/legacy-homebrew#48866]
Please is possible to add smbclien extension, while I miss it for installing under OS X El Capitan

**Comment by mikemcquaid** [comment]
Is this installed by `brew install samba`?

**Comment by alfista-sk** [comment]
no, you have there this option to install complete smbclient extension with all libraries?

**Comment by UniqMartin** [comment]
I'm not entirely sure what you are missing. Can you clarify? In any case, `brew install samba` does provide the `smbclient` binary if that's what you are looking for.
