### ISSUE TITLE
libstfl fails to build on OS X 10.11.2

### ISSUE THREAD

**Issue by sjmarshy** [Homebrew/legacy-homebrew#48930]
logs are [here](https://gist.github.com/sjmarshy/49abd1c7481d7412b963). Looks like it's trying to build for a 32 bit machine, but I don't know why that would be?

**Comment by ilovezfs** [comment]
The mention of 64-bit is normal. It doesn't imply it's doing 32-bit. The problem is caused by the presence of the ruby installed from brew. You can uninstall Homebrew ruby, install libstfl, and then reinstall Homebrew ruby.

This diff also fixes it:

```
diff --git a/Library/Formula/libstfl.rb b/Library/Formula/libstfl.rb
index f704687..d8e98ab 100644
--- a/Library/Formula/libstfl.rb
+++ b/Library/Formula/libstfl.rb
@@ -18,7 +18,7 @@ class Libstfl < Formula
   patch :DATA
 
   def install
-    args = ["CC=#{ENV.cc} -pthread", "prefix=#{prefix}"]
+    args = ["RUBY=/usr/bin/ruby CC=#{ENV.cc} -pthread", "prefix=#{prefix}"]
 
     args << "FOUND_RUBY = 0" unless MacOS::CLT.installed? || MacOS.version >= :mavericks
 

```

Hopefully, someone can come up with a more general solution. @xu-cheng

**Comment by DomT4** [comment]
Just for fun, adding `depends_on :ruby => ["1.8", :build]` to the formula also seems to resolve the problem.

**Comment by DomT4** [comment]
This may have something to do with our environment. If you build the package outside Homebrew using the same patch and build options it builds fine.

**Comment by ilovezfs** [comment]
@DomT4 Good call on the environment being the issue. Voilà:
```
diff --git a/Library/Formula/libstfl.rb b/Library/Formula/libstfl.rb
index f704687..a3f9baa 100644
--- a/Library/Formula/libstfl.rb
+++ b/Library/Formula/libstfl.rb
@@ -18,6 +18,10 @@ class Libstfl < Formula
   patch :DATA
 
   def install
+    if Formula["ruby"].installed?
+      ENV.prepend_path "PATH", Formula["ruby"].opt_bin
+    end
+
     args = ["CC=#{ENV.cc} -pthread", "prefix=#{prefix}"]
 
     args << "FOUND_RUBY = 0" unless MacOS::CLT.installed? || MacOS.version >= :mavericks

```

and it works.

**Comment by ilovezfs** [comment]
@DomT4 @sjmarshy #49110
