### ISSUE TITLE
Sources for sbcl

### ISSUE THREAD

**Issue by iced** [Homebrew/legacy-homebrew#48968]
Right now if you try jump-to-source using sbcl (e.g. for min), you are getting:

/private/tmp/sbcl20160208-95173-txqf3x/sbcl-1.3.2/src/code/numbers.lisp
  (DEFUN MIN)
/private/tmp/sbcl20160208-95173-txqf3x/sbcl-1.3.2/src/pcl/ctypes.lisp
  (DEFINE-METHOD-COMBINATION MIN GENERIC-FUNCTION (EQL MIN) T)
/private/tmp/sbcl20160208-95173-txqf3x/sbcl-1.3.2/src/compiler/srctran.lisp
  (:DEFINE-SOURCE-TRANSFORM MIN)
/private/tmp/sbcl20160208-95173-txqf3x/sbcl-1.3.2/src/compiler/fndb.lisp
  (DECLAIM MIN SB-C:DEFKNOWN)

This renders brew-ed sbcl really hard to use.

**Comment by bfontaine** [comment]
Is it an issue with `sbcl` itself or the way Homebrew installs it?

**Comment by iced** [comment]
the way homebrew builds it - as you see it refers to build directory. most likely you'll need something like this: https://github.com/gentoo/gentoo/blob/master/dev-lisp/sbcl/sbcl-1.3.1.ebuild#L230-L237 - add --with-sources, install sources and inject this SBCL_SOURCE_ROOT.

**Comment by dunn** [comment]
We'd be happy to take a PR!  Have a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by iced** [comment]
I'm too lazy and too busy, but ok. Will try @ weekend (only in case you don't have SJW CoC).

**Comment by mikemcquaid** [comment]
> I'm too lazy and too busy, but ok. Will try @ weekend (only in case you don't have SJW CoC).

We do have a CoC, have done for a while and multiple Homebrew maintainers would consider "SJW" to be pejorative. Please read our Code of Conduct (https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md) and follow it if you want to communicate with our team or community. Thanks!

**Comment by iced** [comment]
Already did. Looks like nice one. Wait for pull request :)

**Comment by mikemcquaid** [comment]
@iced Great, thanks.

**Comment by iced** [comment]
https://github.com/Homebrew/homebrew/pull/48999

At least I can continue my work with this. Please merge ;)

**Comment by iced** [comment]
Just noticed CI warnings. Will you fix it yourself?

**Comment by dunn** [comment]
Oh, forgot BrewTestBot gets excited and closes issues.
