### ISSUE TITLE
Fetch all source packages before installing

### ISSUE THREAD

**Issue by rgov** [Homebrew/legacy-homebrew#48986]
One can do `brew fetch --deps xyzzy && brew install xyzzy` but it seems sensible that this would be the default behavior. That way you don't waste a lot of time building dependencies when you ultimately won't be able to install the target formula. Also, this allows you to resume a build in progress (after downloads have completed) even if you don't have network connectivity, which is nice for flaky public Wi-Fi on planes and such.

**Comment by dunn** [comment]
> That way you don't waste a lot of time building dependencies when you ultimately won't be able to install the target formula.

Do you just mean when a later dependency fails to download?  I'm not sure if that happens enough to be something to explicitly work around.

**Comment by rgov** [comment]
> Do you just mean when a later dependency fails to download?

Yes, that's what I meant.

> I'm not sure if that happens enough to be something to explicitly work around.

I agree it is not the common case, but reordering to download first has no impact on users with stable connectivity. There could be other benefits to doing so, for example, entering a more restrictive sandbox after downloads complete.

**Comment by DomT4** [comment]
> There could be other benefits to doing so, for example, entering a more restrictive sandbox after downloads complete.

Eh. We had this discussion a while back. It's difficult for builds that use Maven, `npm`, etc because they want to download things during compile and there's really no feasible way to prevent that. In an ideal world we'd be able to tightly sandbox that element but it's not particularly practical.

**Comment by mikemcquaid** [comment]
Does running `brew fetch --deps; brew fetch` beforehand not basically do this? Regardless, this is something we'd review a pull request for but aren't actively implementing at this time.

**Comment by alexchandel** [comment]
@mikemcquaid I don't think it works with `brew upgrade`.

**Comment by ilovezfs** [comment]
Did you actually try?
```
Josephs-MacBook-Pro:local joe$ brew outdated
go (1.6, 1.6.1 < 1.6.2)
homebrew/dupes/grep (2.23 < 2.25)
Josephs-MacBook-Pro:local joe$ brew fetch --deps go
==> Downloading https://storage.googleapis.com/golang/go1.6.2.src.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/go-1.6.2.tar.gz
SHA256: 787b0b750d037016a30c6ed05a8a70a91b2e9db4bd9b1a2453aa502a63f1bccc
Resource: gobootstrap
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
######################################################################## 100.0%
Downloaded to: /Users/joe/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
SHA256: c2f53983fc8fe5159d811081022ebc401b8111759ce008f91193abdae82cdbc9
Resource: gotools
==> Cloning https://go.googlesource.com/tools.git
Updating /Users/joe/Library/Caches/Homebrew/go--gotools--git
==> Checking out branch release-branch.go1.6
Josephs-MacBook-Pro:local joe$
```

**Comment by alexchandel** [comment]
@ilovezfs I updated a 2-year old homebrew system's wine a week ago to `wine --devel --with-samba` and `brew fetch --deps` missed both the flags.

**Comment by tduehr** [comment]
This would also help to better support fetching resources concurrent with upgrading/installing.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.
