### ISSUE TITLE
Gdal with jp2 support

### ISSUE THREAD

**Issue by ramotswa** [Homebrew/legacy-homebrew#49010]
Hello All,

What is the simplest way of getting gdal with jp2 (read only for now) support on OSX? I have followed instructions from people like kynchaos (http://www.kyngchaos.com/software/frameworks) with no success. My gdalinfo --formats still has no mention of any ECW / jpeg2000 / jp2 support. 
I have also tried installing gdal 2 via brew but unless there is an argument I have missed it doesn't come with the format supported.

Any pointers would be gladly received.

**Comment by UniqMartin** [comment]
JPEG2000 support depends on an external library that is not currently used by the `gdal` formula provided by Homebrew. As far as I can see from the GDAL documentation, the easiest route should be to add support for `jasper` (that is already part of Homebrew) to the `gdal` formula. Can you try and create a pull request for that? [This guide on creating Homebrew PRs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md) should get you started and I'm happy to help get this merged once you come up with something.

**Comment by UniqMartin** [comment]
Feel free to get in touch if we can assist further, but for now I'm closing this issue as it is not going to magically resolve itself (someone needs to step up and put in the work). Thanks for understanding!

**Comment by mankoff** [comment]
Can this get re-opened and tagged as a feature request, even if nobody is volunteering to do it right now?

**Comment by UniqMartin** [comment]
Sorry, but we don't do feature requests and don't keep issues open that are not actionable and don't constitute a bug on our end. This just doesn't scale given the size of our team compared to the size of our project. So far nobody has volunteered to do the work (this includes maintainers, if they happen to be interested), but maybe you could be the one if you are passionate about this.
