### ISSUE TITLE
Option to require https, ssh, or otherwise secure method of fetching source

### ISSUE THREAD

**Issue by zadr** [Homebrew/legacy-homebrew#49218]
I think an option to never fetch sources for a package over an insecure connection could be useful.

In my mind, this would result in an error that forces the installation to stop (unless a flag like `   --allow-insecure-fetch` flag is used).

The reason I bring up this up is: I installed `openssl` through homebrew, and while `openssl` was fetched over a secure `https` connection, one of its dependencies (creatively named `makedepend`) was fetched over a plain `http` connection (that can easily be MITM'd).

I'm reasonably sure that the package that brought this request up is safe (it contains a `sha256` sum that matches what `brew` knows, and the checksum that `brew` knows was fetched through an `https` clone by `brew update`), I had to manually check that the package included a `sha256` checksum (and not an older `sha1` sum that shouldn't be considered secure).

I could go and audit every other package I have installed to make sure they all have `sha256` sums and/or came over a secure connection (`https`, `ssh` git clone, whatever), but, it would be great if the failure case could be made a hard error right away, so my software handle being secure for me.

**Comment by zadr** [comment]
I took a brief look at `fetch` in `Library/Homebrew/download_strategy.rb` and saw that `HOMEBREW_NO_INSECURE_REDIRECT` exists to prevent possibly downgrading from `https` to `http` when fetching sources, but there's nothing like `HOMEBREW_NO_INSECURE_DOWNLOAD` to outright prevent `http` from ever taking place.

This doesn't seem like it would be too hard to add*, but, I didn't see anything about contributing to `brew` itself in `CONTRIBUTING.md` (tests required? etc).


* the actual implementation might look like this:
```
        if ENV["HOMEBREW_NO_INSECURE_DOWNLOAD"].nil? && @url.start_with?("http://") &&
           urls.any? { |u| !u.start_with? "https://" }
          puts "No HTTPS download found & HOMEBREW_NO_INSECURE_DOWNLOAD is set."
          raise CurlDownloadStrategyError.new(@url)
        end
```

although, I don't know what the documentation process for this should be.

**Comment by mikemcquaid** [comment]
This seems reasonable. Feel free to create a PR for this and thanks for the issue first.

**Comment by DomT4** [comment]
> (and not an older sha1 sum that shouldn't be considered secure).

Nothing (AFAIK) in the core or any Homebrew org tap is using SHA1 at this point. It'll be officially killed this year and we're about to become a lot more shouty about that when people install SHA1 formulae.

> one of its dependencies (creatively named makedepend) was fetched over a plain http connection

This is actually an upstream bug of sorts IMO. Freedesktop recently moved to SSL/TLS across the site, but in the process left the x.org stuff behind. They may do something about if it someone gives them a gentle nudge.

> but there's nothing like HOMEBREW_NO_INSECURE_DOWNLOAD to outright prevent http from ever taking place.

The end game of `HOMEBREW_NO_INSECURE_REDIRECT` is for everything to have a secure mirror and for it to fallback when that variable is set.

I'm happy to take some sharper workarounds until that becomes possible, but I would prefer us to note somewhere the behaviour of the mechanism isn't guaranteed to stay the same forever. In hindsight I should have slapped a firmer warning on the existing ENV.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.

**Comment by MikeMcQuaid** [comment]
@zadr I'm sorry that it's disappointing but that's better than leaving an issue open that no-one is implementing. We have a small, time-limited team of volunteers and unless one of us feels passionate enough about an issue to implement it in the short term after it is filed it'll just sit here indefinitely and make it harder to find the issues that need urgent attention.

**Comment by zadr** [comment]
@MikeMcQuaid as discussed on Twitter: this leaves a bad taste in my mouth, so I thought I'd say something quickly, with a 👎 and a tweet.

it really does feel a lot like discouraging people from submitting issues or requests unless they're willing to implement things themselves (in other words: the "pull request or gtfo" mentality that's so pervasive in open source projects -- and harmful to people trying to get off the ground).

but hey, far be it for me to tell you how to run your oss project. i clearly don't have the time/desire to contribute here (too busy to even work on my own oss things -- which do have a decently large backlog of totally valid feature requests and bugs to fix 😅).
