### ISSUE TITLE
Build python bindings for Boost.MPI

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/legacy-homebrew#49382]
After installing boost-python, I can't import the boost python module. Is this part of the intended functionality of `brew install boost-python`?

    $ python -c "import boost"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named boost

    $ brew gist-logs boost-python
    https://gist.github.com/3afe8c09aacd7206adf0

**Comment by tdsmith** [comment]
No; I don't think Boost.Python generates an importable Python module. It's a library that makes writing C bindings for Python easier. Please let me know if I'm confused.

**Comment by kilojoules** [comment]
@tdsmith look into the [boost python bindings](http://www.boost.org/doc/libs/1_55_0/doc/html/mpi/python.html)

**Comment by tdsmith** [comment]
That's from Boost.MPI, not Boost.Python; it is not provided by boost-python.

**Comment by kilojoules** [comment]
Is it provided by homebrew? Can I make this a feature request?

**Comment by tdsmith** [comment]
Dunno! What happens if you `brew install boost --with-mpi --without-single`?

**Comment by kilojoules** [comment]
Here are the results of installing with `["--with-mpi","--without-single","--c++11"]`

    $ brew gist-logs boost
    https://gist.github.com/e1ec75fc058d27f83d00

**Comment by tdsmith** [comment]
Did it work? (Also, --c++11 is a no-op on 10.9+.)

**Comment by kilojoules** [comment]
Hmm ok I remember this option solving a problem I had in the past but maybe it was something else. I'm on 10.9. No I still can't import boost/boost.mpi. 

    $ python -c "import boost.mpi"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named boost.mpi

**Comment by tdsmith** [comment]
And `brew ls -v boost | grep site-packages` doesn't turn up anything, right?

**Comment by tdsmith** [comment]
I'll reopen but a pull request would be the best way to land this. :)

**Comment by kilojoules** [comment]
Correct. OK I'll give it a shot. Is there a guide to creating homebrew recipes? In the past it has been hard for me to create brew formulas even when I know how to build from source. [For example, see this SO question](http://stackoverflow.com/questions/31360101/confusion-creating-brew-formula-cmake-cache-specifications-depends-on-layout)

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
