### ISSUE TITLE
gst-plugins-ugly does not include optional plugins

### ISSUE THREAD

**Issue by schwa** [Homebrew/legacy-homebrew#49434]
(Relates to https://github.com/Homebrew/homebrew/issues/6213)

The `ffenc_mpeg4` plugin for gstreamer is not included (as it should be) by `gst-plugins-ugly` 

```
$ brew install x264
(success!)
$ brew install gstreamer
(success!)
$ brew install gst-plugins-ugly
(success!)
$ gst-inspect-1.0 ffenc_mpeg4
No such element or plugin 'ffenc_mpeg4'
```

The `ffenc_mpeg4` gstreamer plugin should be included in the `gst-plugins-ugly` formula if the `x264` formula is installed. This doesn't seem to be working. I've also tried `brew install gst-plugins-ugly --build-from-source` - again that doesn't work.

**Comment by mikemcquaid** [comment]
Did you use `--with-x264`?

**Comment by schwa** [comment]
Yup. Have tried that too. Still not working:

```
Last login: Tue Feb 23 10:07:42 on ttys001
schwa@ungoliant ~> brew install x264
Warning: x264-r2601 already installed
schwa@ungoliant ~> brew install gstreamer
Warning: gstreamer-1.6.3 already installed
schwa@ungoliant ~> brew install gst-plugins-base
==> Downloading https://homebrew.bintray.com/bottles/gst-plugins-base-1.6.3.el_c
######################################################################## 100.0%
==> Pouring gst-plugins-base-1.6.3.el_capitan.bottle.tar.gz
/usr/local/Cellar/gst-plugins-base/1.6.3: 412 files, 15.8M
schwa@ungoliant ~> brew install gst-plugins-ugly --with-x264
==> Downloading https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.6.3.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/gst-plugins-ugly/1.6.3 --mandir=/usr/local/Cellar/gst-plugins-ugly/1.6.3/share/man --disable-amrnb --disable-amrwb
==> make
==> make install
/usr/local/Cellar/gst-plugins-ugly/1.6.3: 99 files, 1.6M, built in 30 seconds
schwa@ungoliant ~ [1]> gst-inspect-1.0 ffenc_mpeg4
No such element or plugin 'ffenc_mpeg4'
```

**Comment by UniqMartin** [comment]
I'm not very familiar with with GStreamer, but judging from https://gstreamer.freedesktop.org/data/doc/gstreamer/1.8/gst-plugins-ugly-plugins/html/ I can't see a trace of `ffenc_mpeg4`, so I wouldn't expect it to be provided by `gst-plugins-ugly`. What makes you think it should be provided by that formula? Thanks!

**Comment by aleb** [comment]
Try to install also ffmpeg (ff in ffenc suggests ffmpeg)

**Comment by UniqMartin** [comment]
> Try to install also ffmpeg (ff in ffenc suggests ffmpeg)

I'm not sure this is going to change anything. At least `gst-plugins-ugly` doesn't declare a dependency on `ffmpeg`, thus it's not going to magically link against it. And I still don't see a hint of `ffenc_mpeg4` in the documentation or any other indication that it is part of `gst-plugins-ugly` (or any other part of GStreamer). I'd be grateful if someone could link me to the relevant code/documentation for this.

**Comment by UniqMartin** [comment]
Closing for a lack of feedback, assuming the issue is resolved or not an actual issue; happy to reopen if I'm wrong and once there's some activity here.
