### ISSUE TITLE
brew test-bot parses formula git history and throws error not present in current formula

### ISSUE THREAD

**Issue by javian** [Homebrew/legacy-homebrew#49604]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

After submiting Homebrew/homebrew-php#2901 the travis script spits out an error saying

Error: 64-bit machines cannot use phpmyadmin without mcrypt

I run the following on my own machine and this occurs

➜  ~  brew bottle --verbose --rb phpmyadmin
==> Determining homebrew/php/phpmyadmin bottle revision...
Error: 64-bit machines cannot use phpmyadmin without mcrypt

This error is raised but the only reference I can find to it is in an old commit located here

https://github.com/Homebrew/homebrew-php/commit/8540023a199c78df746946c419d41d0c9d853025

where the code was removed. There's a recent Travis log to be found here

https://travis-ci.org/Homebrew/homebrew-php/jobs/112199134

I posted the question on IRC and @tdsmith suggested that 
```
tdsmith: ohhhh, this is because brew-test-bot looks through git history and parses formulas to learn versions
tdsmith: that's bad
```

Assuming this is correct - can it be fixed ?

**Comment by tdsmith** [comment]
I think this is an argument for adding `RuntimeError` to IGNORED_EXCEPTIONS here? https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula_versions.rb#L4-L8

**Comment by mikemcquaid** [comment]
@tdsmith A more specific exception would be ideal but: yep.

**Comment by marioletta** [comment]
Same problem. Wanted to commit an update for phpMyAdmin version 4.5.5.1 and the build failed. 

Commit:
https://github.com/Homebrew/homebrew-php/commit/bc8cd81216b56bf71cade5144c34a22a29c268fb

Travis log:
https://travis-ci.org/Homebrew/homebrew-php/jobs/113963647

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by javian** [comment]
Thanks Mike, I can no longer reproduce it following the steps outlined in the first post so it seems that it has been resolved in some other way.
