### ISSUE TITLE
sickrage has a broken build

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/legacy-homebrew#49709]
OpenSSL changed a function signature in a security release. :tada:

https://github.com/pyca/cryptography/issues/2750

```
tim@rocketman:Library (master)$ grep -Re 'url.*cryptography.*' Formula Taps
Formula/ansible.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
Formula/duplicity.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.2.1.tar.gz"
Formula/letsencrypt.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.2.3.tar.gz"
Formula/mitmproxy.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
Formula/ooniprobe.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.0.1.tar.gz"
Formula/sickrage.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.tar.gz"
Formula/svtplay-dl.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
Taps/homebrew/homebrew-versions/ansible19.rb:    url "https://pypi.python.org/packages/source/c/cryptography/cryptography-1.1.2.tar.gz"
```

**Comment by DomT4** [comment]
`letsencrypt` should be alright, I bumped that last night. Colour me wildly unsurprised at OpenSSL doing this :smile:.

**Comment by UniqMartin** [comment]
What is the status of this? Is this still an issue?

**Comment by tdsmith** [comment]
sickrage is probably still broken.

**Comment by UniqMartin** [comment]
Though it has seen a ton of updates since it was last updated in Homebrew (we're at 4.0.76.2, upstream at 7.0.22), making it likely that the issue can be resolved? Seems like it needs to be boneyarded (for a lack of community support) or updated …

**Comment by DomT4** [comment]
There's some weird upstream drama/politics ongoing:

> Currently there have been several reports of attempts to trick our members into switching to a new sickrage repo being told that the current one is no longer operational, DO NOT BE FOOLED this is a poor attempt by several EX-team members to decieve you into switching to their UNOFFICIAL CLONED SickRage application/site/repo. Please note that if SiCKRAGE ever needed to move to a new site or change its address there is already code in place to do this automatically and securely by me, if you do manually change this information SiCKRAGE accepts no liability or consequences of anything afterwards. If you receive any such attempts/requests please please email www.sickrage.tv@gmail.com promptly so that we can deal with it accordingly!

And the homepage has moved. Not really sure what's going on or whether we should bail.

**Comment by UniqMartin** [comment]
Oh my …

**Comment by DomT4** [comment]
Given that and the low number of bottled downloads I'd be tempted to just :skull:.

**Comment by UniqMartin** [comment]
Added, shortly after bumped by Baptiste, and not touched ever since (for more than 6 months). Sounds like the perfect :skull: candidate for complete lack of interest from the community …

**Comment by tdsmith** [comment]
iirc the new version didn't build cleanly and i ran out of interest in fixing it; killing it is fine by me

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/129
