### ISSUE TITLE
mono F# fails to build on 10.11 with a systemwide mono installation present

### ISSUE THREAD

**Issue by Rotonen** [Homebrew/legacy-homebrew#49746]
https://gist.github.com/Rotonen/94a6271daeb59e933acc

The F# build is failing while trying to use NuGet.exe from somewhere within /private/tmp/ - ref. 05.make from the gist.

**Comment by dunn** [comment]
If I'm reading this right it's expecting to find `mono` in `/Library`:
```
		/var/folders/x4/7q6487553jd29w71f88t9ktw0000gn/T/tmp47b75ea6.tmp: line 1: /Library/Frameworks/Mono.framework/Commands/mono: No such file or directory
/private/tmp/mono--fsharp20160303-32276-ec6ogk/src/FSharpSource.targets: error : Command '/Library/Frameworks/Mono.framework/Commands/mono --runtime=v4.0.30319 /private/tmp/mono--fsharp20160303-32276-ec6ogk/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages -ConfigFile /private/tmp/mono--fsharp20160303-32276-ec6ogk/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.Config' exited with code: 127.
	Task "Exec" execution -- FAILED
```

**Comment by Rotonen** [comment]
Thank you, it was indeed an old ghost of a MonoDevelop installation left behind getting in the way there.

The build of mono did not fail, with the same system conditions, with the older versions of mono, as they do now, so this is limited to building F# with a systemwide mono installation being present.

I'm editing the topic to reflect this.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
