### ISSUE TITLE
planck failed to install on 10.11 (maven Java build dep)

### ISSUE THREAD

**Issue by mfikes** [Homebrew/legacy-homebrew#49751]
If you attempt to install `planck` on a fresh install of 10.11 with a freshly-installed Homebrew installation:

```
$ brew install planck
maven: Java is required to install this formula.
...
```

The formula for `planck` indicates a `:build` dependency on `maven`:

```
  depends_on "maven" => :build
```

This build dependency was added with the latest revision of the `planck` formula (for Planck 1.10), and it truly only is a _build_ dependency.

If you `brew edit planck` and delete this line, then you can install from the bottle.

This appears to be a bug in Homebrew.

**Comment by eggsyntax** [comment]
Likely related, I hit "Java is required to install this formula" today while installing maven. 10.10.5, Homebrew 0.9.5 (rev 245a8). I have Java 1.8 installed. As with @mfikes' experience with planck, doing `brew edit maven` and deleting `depends_on :java` caused the install to proceed successfully.

**Comment by dunn** [comment]
@eggsyntax that sounds like an issue with Homebrew failing to find your Java installation. Could you open a separate issue? Thanks!

**Comment by eggsyntax** [comment]
NP, filed as [issue 50035](https://github.com/Homebrew/homebrew/issues/50035).

**Comment by mikemcquaid** [comment]
@mfikes Smells like a dependency resolution issue here.

**Comment by mfikes** [comment]
@mikemcquaid Do you think the issue is with the Planck formula or with Homebrew?

Previously, Planck has had a dependency on [Leiningen](http://leiningen.org), which depends on Java, _etc._, via this line in the Planck formula, and that caused no issues with installing Planck from a bottle (_i.e._, without trying to build it on a client box):

```
  depends_on "leiningen" => :build
```

I figured the the Maven dependency (in fact, all _build_ dependencies, as Planck also depends on Xcode for build), would be ignored when simply installing from a bottle.

Perhaps it is not an actual bug in Homebrew but somehow a bug in the Maven formula?

**Comment by mikemcquaid** [comment]
@mfikes With Homebrew, I suspect. Not sure, though,

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by mfikes** [comment]
@MikeMcQuaid Yes, the problem still exists. To work around it, the released version of Planck has been revised to completely avoid Maven as a build dependency (and to to instead depend on published JARs) and, importantly, the Homebrew formula has been revised to not specify this build dependency.

But, Planck master exhibits the issue (Planck master is currently set up to build things instead of using published JARs), and if you attempt `brew install --HEAD planck` you will see the same unless you first `brew edit planck`. My plan is to revert back to published JARs prior to the next release of Planck as a workaround.

**Comment by MikeMcQuaid** [comment]
> My plan is to revert back to published JARs prior to the next release of Planck as a workaround.

Sounds like a plan 👍
