### ISSUE TITLE
SDCC HEAD install failing

### ISSUE THREAD

**Issue by lieuwex** [Homebrew/legacy-homebrew#49823]
[The patch](https://github.com/Homebrew/homebrew/blob/4f21816b439098452e2d3f5e27d490efd2efc4fb/Library/Formula/sdcc.rb#L25-L30) that is applied when installing SDCC from HEAD seems broken:

```
$ brew install sdcc --HEAD
==> Cloning https://sdcc.svn.sourceforge.net/svnroot/sdcc/trunk/sdcc/
Updating /Library/Caches/Homebrew/sdcc--svn-HEAD
==> Downloading https://gist.githubusercontent.com/anonymous/5042275/raw/a2e084f29cd4ad9cd95e38683209991b7ac038d3/sdcc-huge-stack-auto.diff
Already downloaded: /Library/Caches/Homebrew/sdcc--patch-4fa5bf4d3f8f57682246918a06eb780e163b7207dc2cad4133d4017ae892bf6a.diff
==> Patching
==> Applying sdcc-huge-stack-auto.diff
patching file device/lib/Makefile.in
Hunk #1 FAILED at 182.
1 out of 1 hunk FAILED -- saving rejects to file device/lib/Makefile.in.rej
patching file device/lib/incl.mk
Hunk #1 succeeded at 102 (offset 7 lines).
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/sdcc--patch20160306-78503-4w21iw/sdcc-huge-stack-auto.diff
```

`brew gist-logs` tells me there are no logs.
```
$ brew gist-logs sdcc
Error: No logs.

$ brew gist-logs sdcc --HEAD
Error: No logs.
```

SDCC installs fine when I remove [the patch](https://github.com/Homebrew/homebrew/blob/4f21816b439098452e2d3f5e27d490efd2efc4fb/Library/Formula/sdcc.rb#L25-L30)

**Comment by dunn** [comment]
Can you check if the patch has been accepted upstream?  If so, we can restrict it to stable builds.

**Comment by lieuwex** [comment]
Looking at the [Makefile.in](https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/Makefile.in) the patch doesn't seem to be accepted upstream, but the code has been changed. I have no idea if the patch is still needed since I don't have a mcs51, but it looks like the patch has to be updated.

**Comment by UniqMartin** [comment]
Not sure if this is still an issue, but if it is and you are eager to continue to run the HEAD version, please consider researching whether this patch is still needed, if it is, update it, and finally contribute it back to [`homebrew/core`](https://github.com/Homebrew/homebrew-core). We rely on contributions from the community and cannot provide this level of support for HEAD versions that are a moving target. Thanks! Closing as there's nothing actionable here.
