### ISSUE TITLE
`CompilerSelectionError` gives bad advice

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/legacy-homebrew#49873]
```
bash-3.2$ brew install devil
Error: devil cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
bash-3.2$ brew install gcc
Warning: gcc-5.3.0 already installed
bash-3.2$
```
Of course, this is because the formula contains `fails_with :gcc => "5"` but currently
```
bash-3.2$ brew info gcc|head -1
gcc: stable 5.3.0 (bottled), HEAD
```

**Comment by mikemcquaid** [comment]
Looks like we should boneyard this. Would be good to have a smarter `to install this formula` message here too.

**Comment by ilovezfs** [comment]
@mikemcquaid Just a heads up that that also implies boneyarding `hqx`, which is probably fine to do as well based on a brief inspection of the homepage: https://code.google.com/p/hqx/

**Comment by mikemcquaid** [comment]
Yeh, also seems fine, thanks.

**Comment by DomT4** [comment]
Note that `dwarf` and `yap` are in the same boat on needing GCC 4.9 or earlier.

**Comment by MikeMcQuaid** [comment]
Closing old usability issues in favour of pull requests.
