### ISSUE TITLE
Prevent clang linker args from being refurbished

### ISSUE THREAD

**Issue by jasonmp85** [Homebrew/legacy-homebrew#49948]
I've been working on a standard formula for [Citus](https://citusdata.com/), which is in the middle of a transition to becoming an open-source PostgreSQL extension.

Our build procedure is a mixture of a `configure` script and the standard [PGXS makefile](https://github.com/postgres/postgres/blob/REL9_5_1/src/makefiles/pgxs.mk). A straightforward Homebrew formula failed because `refurbish_args` was removing an `-L/usr/local/lib` linker argument that _must_ occur before a subsequent `-lpq` argument. Though `refurbish_args` did preserve this argument, it moved it to later in the argument list, resulting in `clang` complaining during linking.

After poking around a bit, I found that Homebrew decides `/usr/local/lib` is a system library path, so it scrubs it from any initial arguments and moves it to the end, with other standard paths (system libraries and keg-only dependencies).

The odd part is that this only occurs during the linker phase, and it appears that Homebrew is aware that reordering linker arguments might not be the best idea. [Here](https://github.com/Homebrew/homebrew/blob/0643933ef6ae4f12855b72a248f3a106ff912f42/Library/ENV/4.3/cc#L80-L84) it explicitly skips refurbishing if the tool name is `ld`.

Well, under clang builds, `clang` is both the compiler and linker name. Is there a reason this piece of code checks only the tool name, and not the `mode`? If `ld` gets special refurbishment treatment, I think the `ccld` mode of `clang` might warrant the same treatment.

**Comment by jasonmp85** [comment]
For anyone else looking to build a PostgreSQL extension against the Homebrew-provided PostgreSQL, know that PGXS adds some linker arguments looking like `-L/usr/local/lib -lpq`. Homebrew shifts the `-L/usr/local/lib` to later, which is the root of the problem.

Turns out that PostgreSQL generates this section from the [`libpq` Make variable](https://github.com/postgres/postgres/blob/REL9_5_1/src/Makefile.global.in#L478), which enables a workaround… invoke `make` like so:

```ruby
    make_args = [ "libpq=-L#{Formula["postgresql"].opt_lib} -lpq" ]

    system "./configure", *config_args
    system "make", *make_args
```

Since `/usr/local/opt/postgresql/lib` is not one of the specially-treated library directories, it is skipped over during refurbishement and the required order is preserved.

**Comment by tdsmith** [comment]
Dumb question:

> a -L/usr/local/lib linker argument that must occur before a subsequent -lpq argument.

I assume this is because /usr/lib/libpq.dylib exists?

**Comment by jasonmp85** [comment]
That's related, yes.

```
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/private/tmp/citus20160314-19451-188tvt6/citusdata-citus-c018fbd73a0e8ac070a03c9ff0b8134ddbce3631/src/include' -I. -I./ -I/usr/local/Cellar/postgresql/9.5.1/include/server -I/usr/local/Cellar/postgresql/9.5.1/include/internal -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2  -I/usr/local/Cellar/postgresql/9.5.1/include  -c -o utils/multi_resowner.o utils/multi_resowner.c
Undefined symbols for architecture x86_64:
  "_PQsslAttribute", referenced from:
      _printSSLInfo in command.o
  "_PQsslInUse", referenced from:
      _printSSLInfo in command.o
ld: symbol(s) not found for architecture x86_64
```

Since the `/usr/local/lib` was moved to the end of the invocation, you're right that linking finds `/usr/lib/libpq.dylib` instead. And:

```bash
nm libpq.dylib | grep PQssl
# no results

nm libpq.a | grep PQssl
# 0000000000001628 T _PQsslAttribute
# 0000000000002810 b _PQsslAttribute.sslbits_str
# 000000000000161b T _PQsslAttributeNames
# 0000000000002230 s _PQsslAttributeNames.result
# 00000000000015bb T _PQsslInUse
# 00000000000015e3 T _PQsslStruct
```

This file is included because `pg_config --libdir` returns `/usr/local/lib`.

But my original question remains: if `ld` is treated specially wrt argument refurbishment, why not `clang` when used as a linker?

If this is intentional, I suppose it's important that `pg_config` not return anything so generic that it would be refurbished, so maybe I should look into whether the Homebrew PostgreSQL recipe needs tuning?

**Comment by tdsmith** [comment]
It's intentional that libdir is relative to HOMEBREW_PREFIX (here, /usr/local) so that postgres plugins don't need to be installed to postgres's private prefix to be recognized. It's possible that we could force pg_config to give a different answer after postgres is installed. Setting libpq explicitly seems like a good workaround.

I'm not sure I understand the clang invocation and message you gave in your last comment; it looks like that shouldn't have invoked a linker? FWIW, the .cc logs show the effect of refurbishment and the commands as they were actually executed; those could help illustrate the issue.

We don't call refurbish_args for ld because refurbish_args generates compiler arguments, not linker arguments, dating back to 7aa496efed02bb7cd59866c1d7954799128832a5; we do detect using the C compiler as a linker (https://github.com/Homebrew/homebrew/blob/0643933ef6ae4f12855b72a248f3a106ff912f42/Library/ENV/4.3/cc#L47) and argument refurbishment is intentional for that case. We probably ought to perform the same path manipulations for ld.

**Comment by jasonmp85** [comment]
> I'm not sure I understand the clang invocation and message you gave in your last comment; it looks like that shouldn't have invoked a linker?

Oops. Forgot that `brew` does `make -j` and just blindly copy-pasted the line before the error. I've found the actual offending invocation and updated my above comment.

Copying here for completeness:

```bash
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes command.o common.o help.o input.o stringutils.o mainloop.o copy.o copy_options.o stage.o startup.o prompt.o variables.o large_obj.o print.o describe.o tab-complete.o mbprint.o dumputils.o keywords.o kwlookup.o sql_help.o  -L/usr/local/lib -lpq -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib  -Wl,-dead_strip_dylibs    -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lm  -o csql
```

**Comment by jasonmp85** [comment]
So it sounds like the refurbishing of clang-as-linker args is intentional. Then, to sum up the cause of this:

  * Brew-supplied PostgreSQL uses `/usr/local/lib` as `libdir`
  * This causes PGXS extensions which use libpq to add `-L /usr/local/lib -lpq` during linking
  * Arg refurbishing (in super env) moves `-L /usr/local/lib` to the _end_ of the invocation
  * If another `libpq` exists in e.g. `/usr/lib`, the extension will try to link to that instead

My workaround is above. To fix so this works automatically, either (a) reburbishing needs to move `-lpq` to the end of invocations, or (b) PGXS needs to generate another directory to find `libpq` (similarly to the directory paths added by brew for other keg-only dependencies, I believe).

Is there anything to actually be done here? If not, feel free to close, figured I'd just have this conversation out in case another person gets sucked down this rabbit hole.

**Comment by tdsmith** [comment]
Or we fix up pg_config to report postgres's opt_lib, which seems like it could be fine.

**Comment by jasonmp85** [comment]
OK, so I just talked this over with a coworker (hi @anarazel) and he was concerned that using `-L /usr/local/opt/postgres/lib` would be problematic because that path is likely not on the `rpath` used by the dynamic linker (he's coming from a strong Linux background).

He said (of `pg_config --libdir`):

> There's two classes of libraries: Stuff that the OS and external users itself will need (libpq primarily).
> The second class is stuff that postgres loads itself. That's primarily extension libraries.
>
> --libdir is the former. It often is beneficial to have it in the dynamic linker's path.
>
> linked libraries will only be found if they use whatever the rpath equivalent on osx is.
> if you call psql/csql/whatever, it needs to find libpq. It normally will look in a fixed number of paths (in linux configured in /etc/ld.so.conf[.d]).

I _believe_ on OS X, it appears that `rpath`'s importance is somewhat diminished. Using the above workaround, the binary I built (called `csql`) looks like this:

```bash
otool -L `which csql`
# /usr/local/bin/csql:
# 	/usr/local/opt/postgresql/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.8.0)
# 	/usr/local/opt/readline/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
# 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

otool -l `which csql` | grep -A3 'LC_LOAD'
#           cmd LC_LOAD_DYLINKER
#       cmdsize 32
#          name /usr/lib/dyld (offset 12)
# Load command 8
# --
#           cmd LC_LOAD_DYLIB
#       cmdsize 72
#          name /usr/local/opt/postgresql/lib/libpq.5.dylib (offset 24)
#    time stamp 2 Wed Dec 31 17:00:02 1969
# --
#           cmd LC_LOAD_DYLIB
#       cmdsize 72
#          name /usr/local/opt/readline/lib/libreadline.6.dylib (offset 24)
#    time stamp 2 Wed Dec 31 17:00:02 1969
# --
#           cmd LC_LOAD_DYLIB
#       cmdsize 56
#          name /usr/lib/libSystem.B.dylib (offset 24)
#    time stamp 2 Wed Dec 31 17:00:02 1969
```

So it appears the dynamic linker is loading the libraries from full paths, not using `rpath`. In addition, these are `LC_LOAD_DYLIB` commands and not `LC_RPATH` ones, which is [what would appear](http://stackoverflow.com/q/12521802/179878) if this binary used `rpath`-resolved libraries.

So… my initial worry was that changing the `pg_config`-reported `libdir` would result in binaries just saying "hey I need `libpq`" and then the loader just picking up the one it finds in `/usr/lib` (which would just be moving my problem from link-time to runtime). But it appears the linker is actually noting the full library path to the Homebrew-provided PostgreSQL `dylib`s, so changing `libdir` as you propose shouldn't—if we're lucky :four_leaf_clover:—break anything whatsoever.

Want me to open a pull request to do that?

**Comment by tdsmith** [comment]
Your analysis sounds right. On OS X, the -L arguments influence where the linker searches at link time. Once a library is found, the library's install_name is remembered. Nearly all Homebrew-installed libraries should have absolute install_names, so the absolute path is remembered, so we don't run a hazard of confusing the dynamic linker.

A PR would be great!

**Comment by jasonmp85** [comment]
Ok, about to submit a pull request. It doesn't change `libdir` or `pg_config`'s output, though… there's a lot of Homebrew calcification/bad practices for PostgreSQL extensions that make doing that a non-starter.

Ugh… hopefully what I came up with will be acceptable (at minimum, it will let other PostgreSQL extensions not have problems when they link against `libpq`. At the moment, I believe the refurbishing combined with the values for `libdir` and `includedir` mean you'll get the Homebrew headers, but the OS X `libpq`, which don't match).

**Comment by jasonmp85** [comment]
OK, just opened a PR. Tell me if that looks acceptable.

**Comment by jasonmp85** [comment]
Any thoughts?

**Comment by UniqMartin** [comment]
Thanks for the discussion and for following up with a pull request! Closing in favor of #50332.
