### ISSUE TITLE
Cross-tap dependencies of untapped taps break `brew deps`

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/legacy-homebrew#50066]
```
bash-3.2$ ls /usr/local
ls: /usr/local: No such file or directory
bash-3.2$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /usr/local
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local
==> /usr/bin/sudo /usr/sbin/chown joe:admin /usr/local
==> Downloading and installing Homebrew...
remote: Counting objects: 4069, done.
remote: Compressing objects: 100% (3917/3917), done.
remote: Total 4069 (delta 35), reused 1837 (delta 19), pack-reused 0
Receiving objects: 100% (4069/4069), 3.34 MiB | 5.93 MiB/s, done.
Resolving deltas: 100% (35/35), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at 4b30df2 superenv: fix make_jobs regular expression
==> Installation successful!
==> Next steps
Run `brew help` to get started
bash-3.2$ brew deps python
Error: No available formula with the name "homebrew/dupes/tcl-tk" 
Please tap it and then try again: brew tap homebrew/dupes
bash-3.2$ brew cat python|grep 'homebrew/dupes/'
  depends_on "homebrew/dupes/tcl-tk" => :optional
  depends_on :x11 if build.with?("tcl-tk") && Tab.for_name("homebrew/dupes/tcl-tk").with?("x11")
      tcl_tk = Formula["homebrew/dupes/tcl-tk"].opt_prefix
      include_dirs << Formula["homebrew/dupes/tcl-tk"].opt_include
      library_dirs << Formula["homebrew/dupes/tcl-tk"].opt_lib
bash-3.2$ brew tap homebrew/dupes
==> Tapping homebrew/dupes
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Tapped 38 formulae (103 files, 105.4K)
bash-3.2$ brew deps python
berkeley-db4
gdbm
homebrew/dupes/tcl-tk
icu4c
makedepend
openssl
pkg-config
readline
sqlite
bash-3.2$
```

**Comment by mikemcquaid** [comment]
Pretty sure this used to work. Can you check out some old revisions and see if you can pin down when it broke?

**Comment by ilovezfs** [comment]
@mikemcquaid Yup, good call. `git bisect` to the rescue. It's a regression caused by 4f061c97677a00a6a65755eeaa094bb4a71fda04

**Comment by xu-cheng** [comment]
Personally, I don't see this a bug but an expect behavior.

**Comment by ilovezfs** [comment]
Except that before https://github.com/Homebrew/homebrew/commit/4f061c97677a00a6a65755eeaa094bb4a71fda04 it was more user friendly.

**Comment by xu-cheng** [comment]
Before that commit, it's not user friendly but an incorrect result.

**Comment by ilovezfs** [comment]
@xu-cheng As you can see above, a clean, brand-new, empty brew installation is incapable of successfully running 
```
bash-3.2$ brew deps python
Error: No available formula with the name "homebrew/dupes/tcl-tk" 
Please tap it and then try again: brew tap homebrew/dupes
```
without telling me to start tapping something else, which should already be tapped for me if it's going to act that way. You really think `brew deps python` should given an error until you add a non-core tap?

**Comment by xu-cheng** [comment]
The thing is without tapping the necessary tap it will only return an incomplete hence incorrect list.  But at the same time, I don't think `deps` should change any local files, such as auto tapping. Notice this is different in `install` command.

**Comment by xu-cheng** [comment]
As the current policy is disallowing mandatory cross tap deps for core, and running `brew deps --skip-optional python` will be just fine. I think the behavior is consistent.

**Comment by ilovezfs** [comment]
And yet even with incomplete output, because of the auto-tapping behavior you mentioned, <code>brew install \`brew deps python\`</code>, would do the right were it not for this bug.

**Comment by xu-cheng** [comment]
As I said, `brew deps` should return the correct result and should NOT do the auto tapping.  So I think the current behavior is correct.  

But of course, we could improve it by replacing `--skip-optional` flag with `--include-optional`. This would cause behavior change but it seems to be more sense.

**Comment by ilovezfs** [comment]
It seems to me that `brew deps foo` for every `foo` in core should work without erroring, without requiring additional taps, and without requiring additional options.

>But of course, we could improve it by replacing --skip-optional flag with --include-optional. This would cause behavior change but it seems to be more sense.

That sounds like an appropriate bug fix, or always tapping any taps mentioned in core.

**Comment by mikemcquaid** [comment]
> But of course, we could improve it by replacing --skip-optional flag with --include-optional. This would cause behavior change but it seems to be more sense.

Yeh, I agree. It feels weird to have optional dependencies displayed by default.

**Comment by sjackman** [comment]
I agree that `--skip-optional` should be the default behaviour. `brew deps foo` should show the packages that would be installed by `brew install foo`, including ignoring `:build` dependencies if it would be installed by bottle. `brew deps` should take the same arguments as `brew install`, so that `brew install -s foo` includes `:build` dependencies, and `brew deps --with-tcl-tk python` when `homebrew/dupes` is not tapped either gives the above error message, or auto-taps `homebrew/dupes`.

**Comment by sjackman** [comment]
Thanks, Xu!
