### ISSUE TITLE
Nested requirements: allow Requirement class to invoke other requirements based on tags in initialize

### ISSUE THREAD

**Issue by davydden** [Homebrew/legacy-homebrew#50165]
While working on Blas-Lapack `Requirement` wrapper here https://github.com/Homebrew/homebrew-science/pull/2889 , I came across the following issue. Depending on the tags provided to my requirement class, i would like to compile a Fortran test code inside `satisfy :build_env => true do`. But `ENV.fortran` is not defined there and to my understanding of Homebrew, it becomes available only inside the `def install` of a formula.

I wonder if it is somehow possible to either: i) request other retirements inside `initialize` method depending on tags? ii) or somehow make available the result of one requrement (`depends_on :fortran`) inside another (`depends_on MyRequirementClass`) based on their order in a particular formula?

Perhaps, a similar issue already appeared in a different context.

**Comment by mikemcquaid** [comment]
This isn't something we currently support but I guess we could accept a PR to improve it. @xu-cheng, any thoughts?
