### ISSUE TITLE
'error: SDK "macosx10.10" cannot be located' trying install macvim

### ISSUE THREAD

**Issue by digoot** [Homebrew/legacy-homebrew#50180]
# Please follow the general troubleshooting steps first:

- [ YES] Ran `brew update` and retried your prior step?
- [ YES] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Trying install macvim I got this error:
```
xcodebuild -project MacVim/MacVim.xcodeproj -sdk macosx10.10 MACOSX_DEPLOYMENT_TARGET=10.10
xcodebuild: error: SDK "macosx10.10" cannot be located.
make[1]: *** [macvim] Error 64
make: *** [first] Error 2
```

And also I got this logs:

```
Error: undefined method 'strip' for ["Commanche2", "***************"]:Array
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/header.rb:17:in 'block in initialize_http_header'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/header.rb:15:in 'each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/header.rb:15:in 'initialize_http_header'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:44:in 'initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/request.rb:14:in 'initialize'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:121:in 'new'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:121:in 'make_request'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:130:in 'post'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:96:in 'create_gist'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:35:in 'gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:157:in 'gist_logs'
/usr/local/Library/brew.rb:83:in '<main>'
```

Brew config:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 9eba9e7455f37b660a403eb31b587d59036a9db2
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: N/A
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
Java: 1.7.0_05, 1.6.0_65-b14-466.1, 1.6.0_37-b06-434
```

**Comment by apjanke** [comment]
Looks like two things going on here: `brew gist-logs` is breaking, and there's an issue with the macvim build. Let's fix the `gist-logs` thing first; then we can get full build logs and figure out what's going on with the macvim formula here.

The `gist-logs` breakage looks like it might be related to #49846, which changed how credential-related headers are set up, adding support for username/password from Git.

**Comment by ilovezfs** [comment]
This happens if you have Xcode.app (which the macvim formula requires) but don't also have the command line tools. So a workaround is to just install the CLT, too.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew/blob/21e839ebe2c5ad1fb0041d5168b31f11a25711cd/Library/Formula/macvim.rb#L95-L98
```
    unless MacOS::CLT.installed?
      args << "--with-developer-dir=#{MacOS::Xcode.prefix}/Platforms/MacOSX.platform/Developer"
      args << "--with-macsdk=#{MacOS.version}"
    end
```
is incorrect for Xcode 7.0 (7A220) and above. The only SDK installed now is 10.11, and you just have to set MACOSX_DEPLOYMENT_TARGET as desired.

**Comment by ilovezfs** [comment]
@apjanke @digoot FYI: #50191

**Comment by apjanke** [comment]
Sounds like a fix to me, but I don't have a 10.10 box to test it on. @digoot, can you test it? We'll still fix the `gist-logs` issue but no need to wait on it.

**Comment by ilovezfs** [comment]
@apjanke My main machine is 10.8 and I tested it in 10.10 VM, which is how I was able to reproduce the original issue.

**Comment by ilovezfs** [comment]
With `--with-python3` on 10.8 at least I get this:
```
Josephs-MacBook-Pro:~ joe$ brew test -v macvim
Testing macvim
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160317-67460-1481bz1.sb /usr/local/Cellar/ruby/2.3.0/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/macvim.rb -v
Error: macvim: failed
<"/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7"> expected but was
<"/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5">.

diff:
- /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7
?                          ^ ^ -                                       ^ ^
+ /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5
?                         + ^ ^                                        ^ ^
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by ilovezfs** [comment]
On 10.10, also with `--with-python3`
```
vm1010:~ joe$ brew test -v macvim
Testing macvim
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160317-49753-xvknif.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/macvim.rb -v
==> Sandbox log
Mar 17 02:55:06 sandboxd[342]: Python(49765) deny file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/errors.pyc
Mar 17 02:55:06 sandboxd[342]: Python(49765) deny file-write-unlink /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/errors.pyc
Error: macvim: failed
<"/System/Library/Frameworks/Python.framework/Versions/2.7"> expected but was
<"/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5">.
vm1010:~ joe$
```

**Comment by apjanke** [comment]
> @apjanke My main machine is 10.8 and I tested it in a 10.10 VM, which is how I was able to reproduce the original issue.

Great. Sorry, I assume most folks on non-tigerbrew Homebrew are running El Capitan, and I'm one of the lonely 10.9 holdouts.

> With `--with-python3` on 10.8 at least I get this ...

That failure looks like a deficiency in the test definition, not this change. The test isn't aware of how `--with-python3` changes the linkage, and it (AFAIK) doesn't remember what options `macvim` was built with. I get the same test failure on 10.9 under both this PR and the current formula in `master`. The test should be updated to also check `build.with?("python3")`, like `caveats` does.

**Comment by digoot** [comment]
The problem `xcodebuild: error: SDK "macosx10.10" cannot be located` was solve.

But right now drops the #47026 problem.

**Comment by digoot** [comment]
#47026

**Comment by ilovezfs** [comment]
@digoot OK, figured out what was causing #47026 : https://github.com/Homebrew/homebrew/issues/47026#issuecomment-197925412

**Comment by ilovezfs** [comment]
@digoot For the python you're using can you check
```
$ python -c "import distutils.sysconfig as c; print(c.get_config_var('PYTHONFRAMEWORK'))"
Python
```
and
```
$ python -c "import distutils.sysconfig as c; print(c.get_config_var('PYTHONFRAMEWORKPREFIX'))"
/System/Library/Frameworks
```
I'm wondering if `PYTHONFRAMEWORK` *is* defined and `PYTHONFRAMEWORKPREFIX` isn't.
