### ISSUE TITLE
macvim fails to build on 10.11 with pyenv

### ISSUE THREAD

**Issue by rtgibbons** [Homebrew/legacy-homebrew#50206]
Macvim seems to be failing to install with pyenv, removing all references to the shims allowed it to install - brew gist-logs wasn't working so here is the relevant info I believe. I'm sure this is obvious to some, but not sure if it's worth/possible to fix the formula to either build against the default python of pyenv or ignore it and use the system.

I have no issue building against the ruby rbenv.

## Failure installs

**PATH**

```
/Users/rtgibbons/bin:/usr/local/opt/go/bin:node_modules/.bin:/Users/rtgibbons/.nodenv/shims:/Users/rtgibbons/.nodenv/bin:/Users/rtgibbons/.rbenv/shims:/Users/rtgibbons/.pyenv/bin:/usr/local/Cellar/pyenv-virtualenv/20160202/shims:/usr/local/Cellar/pyenv/20160310/libexec:/Users/rtgibbons/.pyenv/shims:/usr/local/opt/php56/bin:/Users/rtgibbons/.dotfiles/scripts:bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```

**brew upgrade macvim**

```
==> Upgrading 1 outdated package, with result:
macvim 7.4-99
==> Upgrading macvim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-99.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-99.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --with-tlib=ncurses --with-comp
Last 15 lines from /Users/rtgibbons/Library/Logs/Homebrew/macvim/01.configure:
--enable-rubyinterp
--enable-tclinterp
--with-tlib=ncurses
--with-compiledby=Homebrew
--with-local-dir=/usr/local
--enable-cscope
--enable-pythoninterp

configure: creating cache auto/config.cache
checking whether make sets $(MAKE)... yes
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/macvim20160317-72140-1fzbj4d/macvim-snapshot-99/src':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**brew doctor**

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Users/rtgibbons/.pyenv/shims/python-config
    /Users/rtgibbons/.pyenv/shims/python2-config
    /Users/rtgibbons/.pyenv/shims/python2.7-config
    /Users/rtgibbons/.pyenv/shims/python3-config
    /Users/rtgibbons/.pyenv/shims/python3.5-config
    /Users/rtgibbons/.pyenv/shims/python3.5m-config

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: /Library/Frameworks/libcurl.framework detected
This can be picked up by CMake's build system and likely cause the build to
fail. You may need to move this file out of the way to compile CMake.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    mono

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com
```

## Working builds

**PATH**

```
/Users/rtgibbons/bin:/usr/local/opt/go/bin:node_modules/.bin:/Users/rtgibbons/.nodenv/shims:/Users/rtgibbons/.nodenv/bin:/Users/rtgibbons/.rbenv/shims:/usr/local/opt/php56/bin:/Users/rtgibbons/.dotfiles/scripts:bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```

**brew install macvim --with-override-system-vim**

```
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-99.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-99.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --with-tlib=ncurses --with-comp
==> make
==> Caveats
.app bundles were installed.
Run `brew linkapps macvim` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/macvim/7.4-99: 2,068 files, 32.7M, built in 44 seconds
```

**brew doctor**

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: /Library/Frameworks/libcurl.framework detected
This can be picked up by CMake's build system and likely cause the build to
fail. You may need to move this file out of the way to compile CMake.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    mono

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com
```

**Comment by ilovezfs** [comment]
Mind trying https://github.com/macvim-dev/macvim ?

**Comment by rtgibbons** [comment]
Not sure what you want me to try. I see that this formula pulls the snapshots from this repo. I've tried building against HEAD and it failed with the same error message. I check-out out the git repo and ran `make && make test` and every looks to have passed.

**brew install --HEAD macvim --with-override-system-vim**

```
==> Cloning https://github.com/macvim-dev/macvim.git
Updating /Library/Caches/Homebrew/macvim--git
==> Checking out branch master
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --with-tlib=ncurses --with-
Last 15 lines from /Users/rtgibbons/Library/Logs/Homebrew/macvim/01.configure:
--enable-rubyinterp
--enable-tclinterp
--with-tlib=ncurses
--with-compiledby=Homebrew
--with-local-dir=/usr/local
--enable-cscope
--enable-pythoninterp

configure: creating cache auto/config.cache
checking whether make sets $(MAKE)... yes
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/macvim20160320-5918-rj9tww/src':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by ilovezfs** [comment]
My apologies. I meant https://github.com/macvim-dev/homebrew-macvim

brew tap macvim-dev/macvim
brew install macvim-dev/macvim/macvim

**Comment by rtgibbons** [comment]
Just gave it a shot, and the install succeeded, but it installed python3 from home-brew, and didn't use the version installed via pyenv. It also looked like the home-brew python3 some how overwrote some of the pyenv environment for python3. Not sure what it did, when using 2.7.1 version, `python3` still works even when called from `~/.shims/python3` and loads the home-brew python. When `pyenv shell 3.5.1` `python3` loads the pyenv environment as expected.

So less then ideal, but it the build did succeed.

**Comment by ilovezfs** [comment]
Interesting. What if you `brew unlink python3`? Still seems to have "overwritten some of the environment" at that point or not?

**Comment by rtgibbons** [comment]
No, that seems to of reverted to the default pyenv functionality i was expecting.

**Comment by dunn** [comment]
> but it installed python3 from home-brew, and didn't use the version installed via pyenv

That'd be because the macvim-dev formula uses `depends_on "python3"` instead of `depends_on :python3`; I'll submit a PR to them.

**Comment by rtgibbons** [comment]
Got `brew gist-logs` to work, here is the output when trying to install macvim, not sure if it'll help or not but thought i'd provide it.

https://gist.github.com/rtgibbons/e1f3010a78108f9a0379fc5e9eb55b01

**Comment by mikemcquaid** [comment]
I'm 99% sure this is an upstream MacVim issue and not a Homebrew one.

**Comment by rtgibbons** [comment]
I'm new to debugging build issues with Homebrew, is it possible to have the temporary build directory to stay after the builds fails to inspect the environment and such?

I did a fresh checkout from macvim-dev/macvim and was able to succesfully build off snapshot-100 with 
```
./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --with-tlib=ncurses --with-compiledby=Homebrew --with-local-dir=/usr/local --enable-cscope --enable-pythoninterp
```

**Comment by mikemcquaid** [comment]
@rtgibbons It is not but you could use `brew install --debug` with a `raise` in the formula or `brew install --interactive` to accomplish that.

**Comment by rtgibbons** [comment]
So tracking this down a bit more, it's due to a failure to properly define the LDFLAGS framework. From the gist above, you can see LDFLAGS getting set to 

    LDFLAGS: -F -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error

The `-F` empty, which is getting defined in https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/macvim.rb#L80-L88

That python script being generated , creates a null string - 

```❯ python
Python 2.7.11 (default, Jan 24 2016, 09:37:40)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils.syconfig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named syconfig
>>> import distutils.sysconfig
>>> print distutils.sysconfig.get_config_var("PYTHONFRAMEWORKPREFIX")

>>>
```

Changing line 85 to below will cause the built to succeed. 

    if !framework_prefix.empty? && framework_prefix != "/System/Library/Frameworks"

I don't this will have negative side affects, but I'm unsure.

**Comment by ilovezfs** [comment]
You're right that it doesn't make sense to do it if it's empty, but why is it coming out empty in the first place?

**Comment by rtgibbons** [comment]
Wasn't sure, after a bit of searching I found https://github.com/yyuu/pyenv/issues/99

By default `pyenv` doesn't build with `--enable-framework`

**Comment by mikemcquaid** [comment]
It may be worth trying to build this from source outside Homebrew to see if it's our or their bug.

**Comment by rtgibbons** [comment]
Build macvin? If so it works outside of Homebrew with and without CFLAGS and LDFLAGS (when set properly)

It's failing it's adding an empty `-F` in LDFLAGS, which my python environment doesn't have `PYTHONFRAMEWORKPREFIX` defined

**Comment by rtgibbons** [comment]
I was on vaca, but just wanted to say things are looking good!. Thanks
