### ISSUE TITLE
PYTHONPATH problems

### ISSUE THREAD

**Issue by tschoonj** [Homebrew/legacy-homebrew#50349]
Hi,

I am running into problems with `PYTHONPATH` in a formula that needs python3 but at the same time also uses `itstool`. The latter sets `PYTHONPATH` at runtime which makes python3 complain as the variable is pointing to a python2.7 folder...

Basically my question is:

Is `bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"])` evil? :smile: 

Can't this be resolved by relying on .pth files in site-packages instead of using `PYTHONPATH`?

**Comment by DomT4** [comment]
This is one I'll have to gently ping @tdsmith into. As far as I'm aware there's a reason why `.pth` files being used widely is problematic but `¯\_(ツ)_/¯`.

**Comment by tdsmith** [comment]
It's reasonably evil but .pth files don't help; we don't want vendored packages to be visible to the system. Maybe I misunderstand? It's a shame CPython [won't support](https://bugs.python.org/issue2375) PYTHONXYPATH.

It's possible we could do something clever with virtualenvs instead, a la pipsi, but I haven't explored that idea in detail.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
