### ISSUE TITLE
Problem Compiling SLEPc program after upgraded to clang 7.3.0 

### ISSUE THREAD

**Issue by ntuloser** [Homebrew/legacy-homebrew#50372]
### Bug reports:

After recent Apple update (Xcode 7.3) , the SLEPc package doesn't work out due to the the linking fail over the wrong dir, e.g.

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin`
instead of the current folder 
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/lib/darwin/`

However, I can not do the reconfigure process to link to the right library, since after brew installation the configure file is removed. I would like to know how to fix that.

**Comment by DomT4** [comment]
Which formula in which tap is this?

**Comment by ntuloser** [comment]
The formula is slepc 
[https://github.com/Homebrew/homebrew-science/blob/master/slepc.rb](url)

**Comment by DomT4** [comment]
Oh, interesting. @dpo may have more thoughts about this. Are you trying to built it from source or pour it from the bottle? Sadly I'm blocked on testing this by [this Issue](https://github.com/Homebrew/homebrew-science/issues/3461).

**Comment by dpo** [comment]
@ntuloser Could you gist the full logs? I'm guessing some dependency was installed from a bottle and built against the wrong sdk. Unfortunately, I don't have 10.11 to experiment.

**Comment by ntuloser** [comment]
Sorry I didn't quite understand what do you mean by "built from source" and "pour from bottle".

Here is some detail about the problem. For example, in my case, I have a cpp file that use the library petsc and library slepc. I use the typical slepc makefile, which leads to compiling like

`/usr/local/bin/mpicxx -o main.o -c -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -O   -fPIC     -I/usr/local/Cellar/slepc/3.6.2_1/real/include -I/usr/local/Cellar/slepc/3.6.2_1/real/include  -I/usr/local/Cellar/petsc/3.6.3_3/real/include -I/usr/local/Cellar/petsc/3.6.3_3/real/include -I/usr/local/opt/hypre/include -I/usr/local/opt/mumps/libexec/include -I/usr/local/opt/suite-sparse/include -I/usr/local/opt/sundials/include -I/usr/local/Cellar/superlu43/4.3_1/include/superlu -I/usr/local/opt/superlu_dist/include/superlu_dist -I/usr/local/opt/parmetis/include -I/usr/local/opt/metis/include -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/fftw/include -I/usr/local/opt/hwloc/include -I/usr/local/Cellar/open-mpi/1.10.2/include    `pwd`/main.cpp
`
and then
`/usr/local/bin/mpicc -Wl,-multiply_defined,suppress -Wl,-multiply_defined -Wl,suppress -Wl,-commons,use_dylibs -Wl,-search_paths_first  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -O -O0  -o ED main.o  -Wl,-rpath,/usr/local/Cellar/slepc/3.6.2_1/real/lib -L/usr/local/Cellar/slepc/3.6.2_1/real/lib -lslepc -Wl,-rpath,/usr/local/opt/arpack/lib -L/usr/local/opt/arpack/lib -lparpack -larpack      -Wl,-rpath,/usr/local/Cellar/petsc/3.6.3_3/real/lib -L/usr/local/Cellar/petsc/3.6.3_3/real/lib  -lpetsc -Wl,-rpath,/usr/local/opt/hypre/lib -L/usr/local/opt/hypre/lib -lHYPRE -Wl,-rpath,/usr/local/opt/libevent/lib -L/usr/local/opt/libevent/lib -Wl,-rpath,/usr/local/Cellar/open-mpi/1.10.2/lib -L/usr/local/Cellar/open-mpi/1.10.2/lib -Wl,-rpath,/usr/local/opt/superlu43/lib -L/usr/local/opt/superlu43/lib -Wl,-rpath,/usr/local/lib -L/usr/local/lib -Wl,-rpath,/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin -lclang_rt.osx -lmpi_cxx -lc++ -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -lclang_rt.osx -Wl,-rpath,/usr/local/opt/mumps/libexec/lib -L/usr/local/opt/mumps/libexec/lib -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -Wl,-rpath,/usr/local/opt/scalapack/lib -L/usr/local/opt/scalapack/lib -lscalapack -Wl,-rpath,/usr/local/opt/suite-sparse/lib -L/usr/local/opt/suite-sparse/lib -lumfpack -lklu -lcholmod -lbtf -lccolamd -lcolamd -lcamd -lamd -lsuitesparseconfig -Wl,-rpath,/usr/local/opt/sundials/lib -L/usr/local/opt/sundials/lib -lsundials_cvode -lsundials_nvecserial -lsundials_nvecparallel -L/usr/local/Cellar/superlu43/4.3_1/lib -lsuperlu -L/usr/local/opt/superlu_dist/lib -lsuperlu_dist -llapack -lblas -Wl,-rpath,/usr/local/opt/parmetis/lib -L/usr/local/opt/parmetis/lib -lparmetis -Wl,-rpath,/usr/local/opt/metis/lib -L/usr/local/opt/metis/lib -lmetis -Wl,-rpath,/usr/local/opt/netcdf/lib -L/usr/local/opt/netcdf/lib -lnetcdf -Wl,-rpath,/usr/local/opt/hdf5/lib -L/usr/local/opt/hdf5/lib -lhdf5_hl -lhdf5 -Wl,-rpath,/usr/local/opt/fftw/lib -L/usr/local/opt/fftw/lib -lfftw3_mpi -lfftw3 -Wl,-rpath,/usr/local/opt/hwloc/lib -L/usr/local/opt/hwloc/lib -lhwloc -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lgfortran -Wl,-rpath,/usr/local/Cellar/gcc/5.3.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.3.0 -L/usr/local/Cellar/gcc/5.3.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.3.0 -Wl,-rpath,/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 -L/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 -lgfortran -lgcc_ext.10.5 -lquadmath -lm -lclang_rt.osx -lmpi_cxx -lc++ -lclang_rt.osx -Wl,-rpath,/usr/local/opt/libevent/lib -L/usr/local/opt/libevent/lib -Wl,-rpath,/usr/local/Cellar/open-mpi/1.10.2/lib -L/usr/local/Cellar/open-mpi/1.10.2/lib -Wl,-rpath,/usr/local/opt/superlu43/lib -L/usr/local/opt/superlu43/lib -Wl,-rpath,/usr/local/lib -L/usr/local/lib -Wl,-rpath,/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -ldl -lmpi -lSystem -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -lclang_rt.osx -ldl 
`

My problem is in the second part, the linking process, where the correct directory should be
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin`
and
`/usr/local/Cellar/gcc/5.3.0/lib/gcc/5/gcc/x86_64-apple-darwin15.3.0/5.3.0`

**Comment by ntuloser** [comment]
Sorry I think I miss the most important thing. The main point of the problem reside in the makefile, which looks like

```

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
ex: ex.o chkopts
        -${CLINKER} -o ex ex.o ${SLEPC_EPS_LIB}
        ${RM} ex.o

```

And the variable `${SLEPC_EPS_LIB}` is the problem (if I didn't get it wrong)

**Comment by cpraveen** [comment]
When can we get new bottles that work with XCode 7.3 ? I am not able to compile any code with petsc due to same problem.

**Comment by dpo** [comment]
Have you tried building from source? It would be great if you could submit a pr to bump petsc and slepc.

**Comment by cpraveen** [comment]
I was trying to compile some test code included in petsc which was failing. But this is because the petsc makefile is using hardcoded paths, see this

```
$ make ex1
/usr/local/bin/mpicc -o ex1.o -c -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -O   -I/usr/local/Cellar/petsc/3.6.3_3/real/include -I/usr/local/Cellar/petsc/3.6.3_3/real/include -I/usr/local/opt/hypre/include -I/usr/local/opt/mumps/libexec/include -I/usr/local/opt/suite-sparse/include -I/usr/local/opt/sundials/include -I/usr/local/Cellar/superlu43/4.3_1/include/superlu -I/usr/local/opt/superlu_dist/include/superlu_dist -I/usr/local/opt/parmetis/include -I/usr/local/opt/metis/include -I/usr/local/opt/netcdf/include -I/usr/local/opt/hdf5/include -I/usr/local/opt/fftw/include -I/usr/local/opt/hwloc/include -I/usr/local/Cellar/open-mpi/1.10.2/include    `pwd`/ex1.c
/usr/local/bin/mpicc -Wl,-multiply_defined,suppress -Wl,-multiply_defined -Wl,suppress -Wl,-commons,use_dylibs -Wl,-search_paths_first  -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -O  -o ex1 ex1.o  -Wl,-rpath,/usr/local/Cellar/petsc/3.6.3_3/real/lib -L/usr/local/Cellar/petsc/3.6.3_3/real/lib  -lpetsc -Wl,-rpath,/usr/local/opt/hypre/lib -L/usr/local/opt/hypre/lib -lHYPRE -Wl,-rpath,/usr/local/opt/libevent/lib -L/usr/local/opt/libevent/lib -Wl,-rpath,/usr/local/Cellar/open-mpi/1.10.2/lib -L/usr/local/Cellar/open-mpi/1.10.2/lib -Wl,-rpath,/usr/local/opt/superlu43/lib -L/usr/local/opt/superlu43/lib -Wl,-rpath,/usr/local/lib -L/usr/local/lib -Wl,-rpath,/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin -lclang_rt.osx -lmpi_cxx -lc++ -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -lclang_rt.osx -Wl,-rpath,/usr/local/opt/mumps/libexec/lib -L/usr/local/opt/mumps/libexec/lib -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -Wl,-rpath,/usr/local/opt/scalapack/lib -L/usr/local/opt/scalapack/lib -lscalapack -Wl,-rpath,/usr/local/opt/suite-sparse/lib -L/usr/local/opt/suite-sparse/lib -lumfpack -lklu -lcholmod -lbtf -lccolamd -lcolamd -lcamd -lamd -lsuitesparseconfig -Wl,-rpath,/usr/local/opt/sundials/lib -L/usr/local/opt/sundials/lib -lsundials_cvode -lsundials_nvecserial -lsundials_nvecparallel -L/usr/local/Cellar/superlu43/4.3_1/lib -lsuperlu -L/usr/local/opt/superlu_dist/lib -lsuperlu_dist -llapack -lblas -Wl,-rpath,/usr/local/opt/parmetis/lib -L/usr/local/opt/parmetis/lib -lparmetis -Wl,-rpath,/usr/local/opt/metis/lib -L/usr/local/opt/metis/lib -lmetis -Wl,-rpath,/usr/local/opt/netcdf/lib -L/usr/local/opt/netcdf/lib -lnetcdf -Wl,-rpath,/usr/local/opt/hdf5/lib -L/usr/local/opt/hdf5/lib -lhdf5_hl -lhdf5 -Wl,-rpath,/usr/local/opt/fftw/lib -L/usr/local/opt/fftw/lib -lfftw3_mpi -lfftw3 -Wl,-rpath,/usr/local/opt/hwloc/lib -L/usr/local/opt/hwloc/lib -lhwloc -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lgfortran -Wl,-rpath,/usr/local/Cellar/gcc/5.3.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.3.0 -L/usr/local/Cellar/gcc/5.3.0/lib/gcc/5/gcc/x86_64-apple-darwin15.0.0/5.3.0 -Wl,-rpath,/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 -L/usr/local/Cellar/gcc/5.3.0/lib/gcc/5 -lgfortran -lgcc_ext.10.5 -lquadmath -lm -lclang_rt.osx -lmpi_cxx -lc++ -lclang_rt.osx -Wl,-rpath,/usr/local/opt/libevent/lib -L/usr/local/opt/libevent/lib -Wl,-rpath,/usr/local/Cellar/open-mpi/1.10.2/lib -L/usr/local/Cellar/open-mpi/1.10.2/lib -Wl,-rpath,/usr/local/opt/superlu43/lib -L/usr/local/opt/superlu43/lib -Wl,-rpath,/usr/local/lib -L/usr/local/lib -Wl,-rpath,/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -ldl -lmpi -lSystem -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin -lclang_rt.osx -ldl 
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/lib/darwin'
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin'
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin'
ld: library not found for -lclang_rt.osx
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: [ex1] Error 1 (ignored)
/bin/rm -f ex1.o
```

But this compiles fine with the latest homebrew petsc if I use something like

```
CC       = mpicc

%.o: %.c
   $(CC) -I$(PETSC_DIR)/include -c $*.c

ex1: ex1.o
   $(CC) -o ex1 ex1.o -L$(PETSC_DIR)/lib -lpetsc
```

I am happy with this so I dont want to change anything for now.

I also ran a slepc example from deal (step-36) and it worked fine for me.

**Comment by UniqMartin** [comment]
Closing as the solution is to either build from source (PETSc is notorious for hard-coding all kinds of build information into their binaries and Makefiles) or submitting PRs to [`homebrew/science`](https://github.com/Homebrew/homebrew-science) that will bump the bottles for rebuilding with the current Xcode (if that hasn't happened yet). In any case, the discussion is going on in the wrong repository. :wink: Thanks for understanding!
