### ISSUE TITLE
ganglia installed but gmetad is not working

### ISSUE THREAD

**Issue by aluenkinglee** [Homebrew/legacy-homebrew#50486]
I installed ganglia on OS X EI Capitan like this

```code
brew install ganglia
```

and it went well for me.

Started gmond like this `sudo gmond` and worked fined, but when I ran gmetad `sudo gmetad` , I find it was not working.

Is there something wrong?

**Comment by mikemcquaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by UniqMartin** [comment]
Closing for a lack of response/information; happy to reopen once there's some activity here.
