### ISSUE TITLE
Jenkins (bot.brew.sh) sporadically fails

### ISSUE THREAD

**Issue by heinemml** [Homebrew/legacy-homebrew#50546]
I'm not sure if this also happens on core builds. But the jenkins build for homebrew-science pulls sporadically fails on `brew doctor` while working fine on the next try with identical data. Is this a known issue?

See homebrew/homebrew-science#3476 for further details.

**Comment by mikemcquaid** [comment]
It is a somewhat known issue. I'll keep an eye on it but if you are able to fix `test-bot.rb` so that it works that'd be appreciated.

**Comment by apjanke** [comment]
I think this was the same issue as #50651, and I think we've got it fixed now.
