### ISSUE TITLE
libassuan bottle issue

### ISSUE THREAD

**Issue by dylanetaft** [Homebrew/legacy-homebrew#50636]
### Bug reports:
I'm on El Capitan
The binary build for libassuan seems to be broken

dylanetaft-imac:gpgme-1.6.0 dylanetaft$ libassuan-config --libs
-L/usr/local/Cellar/libassuan/2.4.2/lib -lassuan -L/usr/local/Cellar/libgpg-error/1.20_1/lib -lgpg-error
dylanetaft-imac:gpgme-1.6.0 dylanetaft$ ls usr/local/Cellar/libgpg-error/1.20_1/lib
ls: usr/local/Cellar/libgpg-error/1.20_1/lib: No such file or directory
dylanetaft-imac:gpgme-1.6.0 dylanetaft$ ls usr/local/Cellar/libgpg-error/1.20_1
ls: usr/local/Cellar/libgpg-error/1.20_1: No such file or directory

brew install --build-from-source libassuan fixes the issue
dylanetaft-imac:libassuan-2.4.2 dylanetaft$ libassuan-config --libs
-L/usr/local/Cellar/libassuan/2.4.2/lib -lassuan -L/usr/local/Cellar/libgpg-error/1.21/lib -lgpg-error

The binary version installs to a 1.21 folder, but the build seems to be 1.20.

**Comment by dunn** [comment]
It looks like you're missing a `/` before `usr` here:
```
ls usr/local/Cellar/libgpg-error/1.20_1
```

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by dylanetaft** [comment]
Bad paste on the ls command, still, libassuan-config --libs if not installed from source shows a directory that doesn't exist on El Capitain.

I ended up forgoing brew for gpgme, gpg2, libgpg-err, and libassuan and for now because I want to develop against 2.1.11

If you can't reproduce it, I'll just close this.

**Comment by dylanetaft** [comment]
Compiled GPGME and related packages of homebrew due to unrelated issues\version, can't easily test further because that will conflict with homebrew links in /usr/local, closing, thanks!
