### ISSUE TITLE
segmentation faults with git 2.8.0 on el capitan

### ISSUE THREAD

**Issue by msridhar** [Homebrew/legacy-homebrew#50640]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

When I install the homebrew version of git 2.8.0 on El Capitan, I get a segmentation fault even for a simple clone operation.  E.g.:

```
> git clone https://github.com/msridhar/rewriting-proxy
Cloning into 'rewriting-proxy'...
remote: Counting objects: 210, done.
remote: Total 210 (delta 0), reused 0 (delta 0), pack-reused 210
Receiving objects: 100% (210/210), 38.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (113/113), done.
Checking connectivity... done.
Segmentation fault: 11
```

The segmentation fault does not occur for the built-in version of git on El Capitan (2.6.4).  git was installed by running `brew install git` and was installed from a bottle.  Many built-in brew operations like `brew update` also fail with this git version installed, again due to segmentation faults.

Let me know if I can provide more information or run further diagnostic steps.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by msridhar** [comment]
Thanks for the quick response!  Sorry about not following the steps.  I believe I have followed all the steps now (including checking CLI tools, permissions, etc.), and I still have the problem.  The output of `brew config` and `brew doctor` is here:

https://gist.github.com/msridhar/cb47fb3b3672692dc65190d59e8437ad

Also, I did note the issue of `Segmentation fault: 11` with Python on the Common Issues page.  I don't think `git` has any dependence on python or installs any modules, but nevertheless, I followed the steps there, and it did not fix the problem.

**Comment by msridhar** [comment]
As a quick follow-up, installing with `--build-from-source` does not fix this problem.

**Comment by ilovezfs** [comment]
Can you try
```
mkdir ~/Documents/brew-20160402
sudo mv /usr/local ~/Documents/brew-20160402
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install git
/usr/local/bin/git clone https://github.com/msridhar/rewriting-proxy /tmp/rp
```

**Comment by msridhar** [comment]
@ilovezfs thanks for the help!  Unfortunately, that did not fix the problem.  I put the shell results here:

https://gist.github.com/msridhar/1359a2b1463d7ded35b16e4d7cd637c1

**Comment by msridhar** [comment]
I have the XCode Command Line Utilities installed, but not XCode itself.  Could that be an issue?

**Comment by msridhar** [comment]
This seems to have fixed itself.  I did not install XCode.  I have no idea what fixed it; oh well.
