### ISSUE TITLE
fastd tests are not working

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#50652]
Testing `fastd` is not working for me locally or on the test bot. Caused test failures for libsodium in homebrew/homebrew-core#10, and will probably do the same for its other dependencies.

The test is to just run `fastd`. When I install and `brew test` it locally on 10.9.5, `fastd` just segfaults. Maybe because `tuntap` requires manual intervention as root to install, [as described in its caveats](https://github.com/Homebrew/homebrew/blob/235d819edf77fb3fe08714c3cf3489d5de08fc96/Library/Formula/tuntap.rb#L37-L61), and I didn't do that. And I don't think we'd do that on the test bots.

When I do a `make install` on 10.11, it complains about not having a secret key configured.

```
$ fastd
2016-04-03 02:33:34 -0400 --- Error: no secret key configured
```

It would be nice if this test ran. If it doesn't, maybe we should just remove the test so it doesn't bork tests for its dependents.

We could probably make this work by just having `tuntap` be `:optional` instead of `:recommended`, and doing `fastd --version` as the test.

**Comment by xu-cheng** [comment]
You probably want to submit formulae related issues to core tap next time.

**Comment by MoritzFago** [comment]
First of all, tuntap is mission critical for fastd, fastd is a (fast and secure) tunneling daemon and needs tuntap absolutely. 
For the problem with the test: it worked on my machine ;), but i improved the test with the last [formula update](https://github.com/Homebrew/homebrew-core/pull/23). Now it at least tests a little bit of the real functionality of fastd, similar to the test in the [openvpn](https://github.com/Homebrew/homebrew-core/blob/fb81645562f7e495a49561065912788af2d1f14f/Formula/openvpn.rb) formula.

**Comment by apjanke** [comment]
Okay, I can see the test passing on that formula update. I'll pull that in and see how things work out.

**Comment by apjanke** [comment]
New test fixed it. Thanks.
