### ISSUE TITLE
Mpv - Not installable on Lion 10.7.5

### ISSUE THREAD

**Issue by mrkapqa** [Homebrew/legacy-homebrew#50656]
Hello ,

could you please enable MPV for 10.7.5?

Thanks 

Rich

**Comment by Eitot** [comment]
MPV itself seems to require Mountain Lion (10.8). You should contact the developer to see whether you can work something out.

https://github.com/mpv-player/mpv

**Comment by mrkapqa** [comment]
i was able to install it via macports but i prefer homebrew over it.

no i have installed mpv with macports and rest of other with homebrew . 
not so ideal, though.

thanks alot for your support

Am 4/3/16 um 4:09 PM schrieb Eitot:
