### ISSUE TITLE
[Question] Linux system support

### ISSUE THREAD

**Issue by Arinerron** [Homebrew/legacy-homebrew#50669]
Hello, 

I noticed in the tagline it said brew was only for Mac. I'm curious, can it be installed on a Linux machine (say Ubuntu for example) and still function properly? 

Thank you for your help!

**Comment by DomT4** [comment]
[Linuxbrew](https://github.com/Linuxbrew/brew) supports Homebrew on Linux. Eventually some of that code will be folded back into here and we'll achieve cross-platform stability of the core code, but for now the fork exists to serve Linux users who are interested :).

**Comment by Arinerron** [comment]
@DomT4 Yay, thanks! :)
