### ISSUE TITLE
Unclear message on ReadMe.md of this repo

### ISSUE THREAD

**Issue by JMoVS** [Homebrew/legacy-homebrew#50663]
A lot of people will hit this repo for quite some time. But the specification of where what moved is hard to quickly grasp. Both bullet points contain "i.e. without the former contents of Library/Formula"

I therefore propose to change it in a way eg:

- All **formula's and formula issues/submissions** moved to **homebrew/core**
- All **homebrew system** related things (issues as well as PRs) moved to **homebrew/brew**

The current ReadMe.md forces me to literally read the full 2 bullet points at least twice to know where I want to head...

**Comment by raindev** [comment]
I agree, the readme is a little bit confusing. Go ahead and open a PR.

**Comment by UniqMartin** [comment]
Would making the bullet points shorter (omitting the technical information) be an improvement?

Suggestion:

- Homebrew/brew: the Homebrew package manager
- Homebrew/homebrew-core: the formulae/packages

**Comment by JMoVS** [comment]
@UniqMartin's suggestion sounds great to me! Would probably help. I still think that there should be bolding, eg:

- Homebrew/**brew**: the Homebrew **package manager**
- Homebrew/**homebrew-core**: the **formulae/packages**


Although to be honest, in my mind it makes sense the reverse way. I imagined the "core" to be the "kernel", so to speak of the package manager and the brew part the formula but it's the other way round.

Has there been a public post about the reasons and so on behind the split? I heard that question in a community chat some days ago.

**Comment by JMoVS** [comment]
maybe even the other way-round for the bullet points?

- for **formulae/packages** -> Homebrew/**homebrew-core**
- for the Homebrew **package manager** itself -> Homebrew/**brew**

**Comment by UniqMartin** [comment]
I'd be fine with the suggested highlighting and the reversed order.

> Has there been a public post about the reasons and so on behind the split? I heard that question in a community chat some days ago.

It has been announced (and briefly explained) on the [mailing list](https://groups.google.com/forum/#!topic/homebrew-discuss/D_weS6pZesg) and via [Twitter](https://twitter.com/MacHomebrew). Maybe it would make sense to link to the mailing list thread from the README, too?

**Comment by mikemcquaid** [comment]
Please make a pull request for this, thanks.

**Comment by JMoVS** [comment]
I'm on the road on the weekend but I will do when I come back

**Comment by mikemcquaid** [comment]
Thanks!
