### ISSUE TITLE
ghost database spiritual blog

### ISSUE THREAD

**Issue by gracecur123** [Homebrew/legacy-homebrew#50673]
DO NOT CREATE NEW ISSUES ON THIS REPOSITORY!

Please create all issues found when running `brew install` at https://github.com/Homebrew/homebrew-core/issues/new

Please create all issues found when running any other `brew` command at https://github.com/Homebrew/brew/issues/new

**Comment by UniqMartin** [comment]
> DO NOT CREATE NEW ISSUES ON THIS REPOSITORY!

Closed because of this and because there's no content aside from the template text.
