### ISSUE TITLE
Change build tbb with gcc in mac OSx

### ISSUE THREAD

**Issue by flima21** [Homebrew/legacy-homebrew#50687]
Hello everyone
tbb compile with gcc more formula in brew run clang compiler Created ./build/macos_intel64_clang_cc has some way to change ./build/gcc Paraa option by editing the formula tbb?

I tried to change the formula to select gcc 6, but was not able to compile with gcc TBB.

make compiler=gcc-6 tbb_build_prefix=BUILDPREFIX
Created ./build/macos_intel64_clang_ccConfigured with: ../configure --build=x86_64-apple-darwin11.4.2 --prefix=/usr/local/Cellar/gcc/6.2.0 --libdir=/usr/local/Cellar/gcc/6.2.0/lib/gcc/6 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-6 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion=Homebrew gcc 6.2.0 --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --with-dwarf2 --disable-nls --enable-multilib 6.2.0_os10.7.5_release and ..._debug directories
/usr/bin/make -C "./build/macos_intel64_clang_ccConfigured with: ../configure --build=x86_64-apple-darwin11.4.2 --prefix=/usr/local/Cellar/gcc/6.2.0 --libdir=/usr/local/Cellar/gcc/6.2.0/lib/gcc/6 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-6 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 6.2.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --with-dwarf2 --disable-nls --enable-multilib 6.2.0_os10.7.5_debug"  -r -f ../../build/Makefile.tbb cfg=debug
make[1]: ../../build/Makefile.tbb: No such file or directory
make[1]: *** No rule to make target `../../build/Makefile.tbb'.  Stop.
make: *** [tbb] Error 2
==> Formula
Path: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/tbb.rb
==> Configuration
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9586390418dbcb8655bf7c62bb315c2a2090722e
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8fba6904e803e7766af6d38c1726c92db895496c
Core tap last commit: 85 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
GCC-4.2: build 5666
Clang: 4.2 build 425
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/fabiolima/.rvm/rubies/ruby-2.3.0/bin/ruby
Java: 1.8.0_102, 1.8.0_92, 1.8.0_66, 1.6.0_65-b14-462
OS X: 10.7.5-i386
Xcode: 4.6.3
CLT: 4.6.0.0.1.1365549073
X11: 2.7.9 => /opt/X11
==> ENV
HOMEBREW_CC: gcc-6
HOMEBREW_CXX: g++-6
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/Homebrew/os/mac/pkgconfig/10.7
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/Homebrew/shims/super:/usr/local/opt/swig/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gcc/bin

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-core#4802
