### ISSUE TITLE
Homebrew website has invalid SSL cert

### ISSUE THREAD

**Issue by sammcj** [Homebrew/legacy-homebrew#50684]
Looks like you're using a SSL cert for www.github.com rather than for http://brew.sh

![screen shot 2016-07-11 at 2 25 27 pm](https://cloud.githubusercontent.com/assets/862951/16719904/7c437096-4773-11e6-8ffc-eedc3d05c42f.jpg)

![screen shot 2016-07-11 at 2 25 33 pm](https://cloud.githubusercontent.com/assets/862951/16719905/7f4a58f4-4773-11e6-9717-102bce152554.jpg)

**Comment by ilovezfs** [comment]
Closing in favor of Homebrew/brew#490

**Comment by sammcj** [comment]
Note that this was not fixed on Homebrew/brew#490
