### ISSUE TITLE
Still Impossible uninstall brew

### ISSUE THREAD

**Issue by adasongliang** [Homebrew/legacy-homebrew#50689]
I met the same issue which is marked as resolved and closed.  Please refer to the link below for the detail of the previous issue. 
https://github.com/Homebrew/legacy-homebrew/issues/45905

Following the detail of the resolution, I still have the same error. Could u help me resolve?

**Comment by DomT4** [comment]
Might be fixed by https://github.com/Homebrew/install/pull/63, potentially. Please file this Issue over @ https://github.com/Homebrew/install though; this repo is deprecated.
