### ISSUE TITLE
Looks like there is a bug.

### ISSUE THREAD

**Issue by longminghong** [Homebrew/legacy-homebrew#50682]
when I use this command line 
"brew install nginx-full --with-rtmp-module"

it fails. And I got these things.

/usr/local/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb:2:in `<class:NginxFull>'
/usr/local/Library/Taps/homebrew/homebrew-nginx/Formula/nginx-full.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:136:in `<main>'

**Comment by MikeMcQuaid** [comment]
Please don't create issues on this repository. Also, this should be reported to homebrew/homebrew-nginx and not homebrew/homebrew-core when you refile it. Also, you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting).
