### ISSUE TITLE
 pip3 not installed

### ISSUE THREAD

**Issue by isbaseby** [Homebrew/legacy-homebrew#50688]
I run brew install python3 installed python3, but not installed pip3

<img width="855" alt="2016-09-10 11 10 34" src="https://cloud.githubusercontent.com/assets/9151309/18407590/9da0ce38-7747-11e6-8fd1-16b53f2eaff8.png">

**Comment by ilovezfs** [comment]
Please reopen this issue in https://github.com/Homebrew/homebrew-core/

Also, you need to follow the requested steps on the Troubleshooting page

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information on https://github.com/Homebrew/homebrew-core/ so we can help you with your problem.

Thanks!
