### ISSUE TITLE
problem installing homebrew/boneyard/clang-omp

### ISSUE THREAD

**Issue by kirk86** [Homebrew/legacy-homebrew#50686]
Hi everyone, sorry for the disturbance I've been having some problems lately with the installation of homebrew/boneyard/clang-omp

I had it previously installed on my system OS X 10.11. I uninstalled it to clean up my system along with gcc-6 and now that I've need it to compile some libraries when I install it, it installs fine but when I run it to compile a minimal omg example it fails complaining about -liomp5 that wasn't able to be found.

I have -liomp5 installed on my system since I've also have the intel compilers. When I compile the simple openmp example with the intel compilers it works fine.

I've also linked the libiomp5.dylib and libiomp5.a from the intel compilers folder to /usr/local/lib but still when I install clang-omp it does't detect it and somehow I always end up in the same place.

**Comment by ilovezfs** [comment]
Have you tried using the `llvm` formula instead? `clang-omp` was boneyarded because the latest `llvm` formula has omp support always enabled, and clang is built as part of the default configuration, so omp and clang are both available in the prebuilt binary bottles out of the box.

**Comment by kirk86** [comment]
@ilovezfs is that from a particular tap. or just `brew install llvm` will do the job. My fear is that the library I want to compile won't compile because they only support clang

**Comment by ilovezfs** [comment]
@kirk86 that's from the main core tap. So yes, just `brew install llvm`. As I mentioned above, it comes with its own clang now (that used to be available as a non-default option in the formula, but now it's always included).

**Comment by ilovezfs** [comment]
@kirk86 you can see it in action here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb#L291-L312

**Comment by kirk86** [comment]
@ilovezfs thanks...

**Comment by tdsmith** [comment]
Let us know if we can help with anything else.
