### ISSUE TITLE
Where is rtorrent?

### ISSUE THREAD

**Issue by marshaul** [Homebrew/legacy-homebrew#50683]
Who exactly is the person responsible for the recent "maintenance" of rtorrent? Despite the fact that rtorrent is working fine, that it is not abandonware, and that the homebrew builds work with minor modification on El Capitan, rtorrent has first been moved to the "legacy" branch, and now as far as I can tell it's missing entirely. No amount of "brew tap"ping or google searching has changed this conclusion. rtorrent is gone from the homebrew world. What gives?

Frankly, I cannot understand either decision. I can understand not wanting to spend the effort to fix someone else's formula, but the simple fact is functionality has been lost, not thanks to anyone's laziness, but due to an active and poorly-considered decision.

**Comment by UniqMartin** [comment]
This legacy repository is the wrong place to raise such an issue. Nevertheless, Homebrew/homebrew-core#369 and the issues/PRs linked from it might help you understand the decision. It's not like we remove formulae to annoy people. We tend to have good reasons. That said, if all the existing issues can be resolved, we'll gladly accept a pull request that re-introduces this formula in Homebrew.

> Who exactly is the person responsible for the recent "maintenance" of rtorrent?

I don't know who is responsible for maintaining `rtorrent` itself (what we call upstream), but in Homebrew there's no fixed maintainer. The formula is maintained by interested users who wish to contribute to the project and occasionally by the Homebrew maintainers themselves.

**Comment by marshaul** [comment]
Martin,

Where, then, is the place to raise such an issue? Evidently, it's entirely unimportant that I know where exactly is proper, but it’s supremely important that I know the legacy repository is the "wrong place". Is pedantry the primary object of projects such as these? It would seem so. 

Tell me, Martin, where would be the proper place to opine that homebrew’s obfuscation of “boneyarded” formulae is one of the worst UI design “features” I’ve encountered in months?

-Marshall Eubanks

**Comment by UniqMartin** [comment]
Please reconsider your tone and have a look at our [Code of Conduct](https://github.com/Homebrew/brew/blob/master/CODEOFCONDUCT.md)! I appreciate that you're affected by this, but the way you're approaching this isn't constructive and doesn't motivate others to help you.

> Where, then, is the place to raise such an issue?

If you open a new issue at https://github.com/Homebrew/legacy-homebrew/issues/new, as you just did with this one, you should have been presented with an [issue template](https://github.com/Homebrew/legacy-homebrew/blob/master/.github/ISSUE_TEMPLATE.md) that answers this. It's not pedantry; after all you have an issue that you would like to see resolved, thus it should be in your best interest to post the question to the right forum. (Still, you got a complete and timely answer from me.)

> Tell me, Martin, where would be the proper place to opine that homebrew’s obfuscation of “boneyarded” formulae is one of the worst UI design “features” I’ve encountered in months?

That's an opinion and not constructive. Feel free to vent off your anger on Twitter, Facebook, your blog, or any other (social) medium available to you. If you feel like contributing or discussing constructively, you can do so here or in other Homebrew-related repositories on GitHub.

**Comment by marshaul** [comment]
The "template" in question does nothing more than instruct folks NOT to open issues. The cases were it allows for opening issues involve the use of "brew" commands, which quite simply does not apply here (and that's _not_ being pedantic). Sorry, but that isn't helpful to people who aren't already in the clique. 

Think about this: it is self-evident that the function of Homebrew is not to make the lives of formulae maintainers easier. Its _function_ is ensure the repeatability of their work, so that future users can benefit from the effort they've already expended building others' code. OK.

And yet we have an instance where completely functional code, which Homebrew is perfectly capable of building in an entirely algorithmic fashion with a simple modification of the install command, is "boneyarded" and essentially completely obfuscated from the casual user (and any obvious Google searching he might do). Does the average Homebrew user care about the difference between "boneyarded" and actively maintained formulae? Of course he doesn't. He merely wants (for instance) rtorrent installed. And yet, a stock Homebrew install will refuse to install rtorrent. It will give no indication of rtorrent's status, or the reasons for its being "boneyarded."

Much more sensible would be to simply build rtorrent with gcc 4.9 by default. If this is really too far out of line with homebrew's recent ready-built philosophy, it could ask the user for permission first, or instruct him in forcing the install via brew commands. If none of this is good enough, it should _at the very least_ inform the user that the formula is available, but only in the "boneyard".

As is stands, the decision regarding rtorrent has no conceivable benefit to anybody but formulae maintainers. But if that's the justification for a decision, what's the point of Homebrew in the first place? 

This isn't to say maintainers are irrelevant, merely that there's a better way to deal with this type of case (for the end user's sake) than what is presently being done.

Now, assuming that this _opinion_ is sufficiently "constructive", where should I post it?

Incidentally, when you tell me to go on social media, that is exactly in line with the "tone" you used in your original response: false civility, a veneer over condescension and pedantry. (Did you honestly believe I needed the difference between formula and actual code maintenance explained? Did you honestly not realize that I was asking about the maintenance of the rtorrent *formula*? Was the context really ambiguous? Of course not. That was pure smugness and condescension on your part.) My tone is merely falling in line with the one you set – albeit passive-aggressively in your case, and openly in mine.

**Comment by bfontaine** [comment]
> It will give no indication of rtorrent's status, or the reasons for its being "boneyarded."

If you run `brew search rtorrent` it’ll give you a link to the PR that boneyarded it, which itself has links that explain why it was done.

```
$ brew search rtorrent
No formula found for "rtorrent".
==> Searching pull requests...
Closed pull requests:
boneyard libtorrent/rtorrent (https://github.com/Homebrew/homebrew-core/pull/369)
```

> Much more sensible would be to simply build rtorrent with gcc 4.9 by default. If this is really too far out of line with homebrew's recent ready-built philosophy, it could ask the user for permission first, or instruct him in forcing the install via brew commands. If none of this is good enough, it should at the very least inform the user that the formula is available, but only in the "boneyard".

We encourage you to make a pull-request for that. Note you can also maintain formulae [in your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md).

**Comment by marshaul** [comment]
Thanks for the useful response! I'll do that. 

It occurs to me that I never even bothered to use "brew search" before – I web search as a matter of habit, which failed me in this case. Perhaps Homebrew should automatically perform a `brew search` if a `brew install` fails all three checks (name search, similar name search, tap search).

**Comment by DomT4** [comment]
> Does the average Homebrew user care about the difference between "boneyarded" and actively maintained formulae? Of course he doesn't. He merely wants (for instance) rtorrent installed.

> it could ask the user for permission first, or instruct him in forcing the install via brew commands.

It's entirely possible the average Homebrew user may not actually be a "He", FYI.

Your tone with Martin is unhelpful. Long, winding rants at people who run projects don't actually help you get your own way, here or in any other FOSS project. You asked why it was removed, you were given an answer. When it comes to moaning Homebrew is awful, either put up PRs to improve the situation or stop yelling at the people who do free work for you, Cheers.

**Comment by MikeMcQuaid** [comment]
> Think about this: it is self-evident that the function of Homebrew is not to make the lives of formulae maintainers easier.

That is a function, actually: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Maintainers-Avoiding-Burnout.md#3-prioritise-maintainers-over-users

> And yet we have an instance where completely functional code, which Homebrew is perfectly capable of building in an entirely algorithmic fashion with a simple modification of the install command, is "boneyarded" and essentially completely obfuscated from the casual user (and any obvious Google searching he might do).

The reason it was boneyarded was because it cannot be built with Clang, OS X's default compiler for many versions at this point. As it cannot be built with Clang we cannot build a binary package and it's arguably not ported to OS X. If/when it builds with Clang without patches: we'll consider re-adding it to Homebrew.

> When it comes to moaning Homebrew is awful, either put up PRs to improve the situation or stop yelling at the people who do free work for you, Cheers.

Agreed.

**Comment by ilovezfs** [comment]
@marshaul If you'd like to yell at someone, you're probably looking for me: https://github.com/Homebrew/homebrew-core/issues/157#issuecomment-207563760

For what it's worth, tapping homebrew/versions and installing gcc49, then tapping homebrew/boneyard and installing rtorrent is not a huge deal. Since gcc4* has been moved out of core, you'd have to tap homebrew/versions even if we hadn't boneyarded rtorrent. Also needing to tap homebrew/boneyard isn't asking that much more.

We have some rules about which compilers are required for core. Rules are always going to cause people to bristle under various circumstances, but they provide some structure and expectations, and make what we support and don't support clear.

If you really do want to fix this situation with rtorrent, encourage the upstream developer to iron out the clang and gcc5 issues. I'm certain those issues can eventually be resolved if the developer chooses to take them up.
