### ISSUE TITLE
configure: error: cannot run C compiled programs.

### ISSUE THREAD

**Issue by sahil912** [Homebrew/legacy-homebrew#50697]
I am following this issue after upgrading to MacOS Seirra
brew config gives me the following details:

> HOMEBREW_VERSION: 1.0.9-20-gf14a3a1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: f14a3a17decdcfd26fc9f2dc0958ee642241ea5a
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d689da84064b9ef99f766858a87fd22c8305488
Core tap last commit: 86 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/jsahil/.rvm/rubies/ruby-2.2.0/bin/ruby
Java: 1.8.0_25
macOS: 10.12-x86_64
Xcode: 8.1
CLT: 8.0.0.0.1.1472435881
X11: N/A
MacPorts/Fink: /opt/local/bin/port

Could please help? How do I resolve this issue,

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/brew#1423
