### ISSUE TITLE
brew install pyqt5 (only...)

### ISSUE THREAD

**Issue by fabioca** [Homebrew/legacy-homebrew#50699]
Due to a messy organization of my MAC (yosemite), I was cleaning up and reinstall from scratch homebrew and  a bit of packages . I noticed that the 'brew install pyqt' is not anymore active and only pyqt5 is there. that would be OK, but since I need also pyqt4, I was wondering how to load from homebrew. 
(I am only a computer user, please, give me infos like for a grandma!). Thank you.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-core#7418
