### ISSUE TITLE
gfortran compilation error

### ISSUE THREAD

**Issue by rishikeshprl** [Homebrew/legacy-homebrew#50691]
hello Sir/madam,

I m using f2py interface for a fortran code.but it is showing some compilation error as follows. And 
i m using gnu95 as compiler ('f2py -c --fcompiler=gnu95'). i m having GNU Fortran (Homebrew gcc 6.2.0) 6.2.0 version in my machine. 

please help me to solve the issue.

many thanks in advance!!

gfortran:f77: CCF.f
gfortran: internal compiler error: Killed: 9 (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
gfortran: internal compiler error: Killed: 9 (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.

error: Command "/usr/local/bin/gfortran -ffixed-line-length-none -fPIC -O3 -funroll-loops -I/var/folders/lg/yyvpnn3104l_h61wy23cz1nm0000gr/T/tmpBEOTHh/src.macosx-10.11-x86_64-2.7 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c -c CCF.f -o /var/folders/lg/yyvpnn3104l_h61wy23cz1nm0000gr/T/tmpBEOTHh/CCF.o" failed with exit status 4

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-core#6414
