### ISSUE TITLE
pip ImportError

### ISSUE THREAD

**Issue by saritekin** [Homebrew/legacy-homebrew#50701]
How can i fix it ?
Thank you for your helps.
```
MacBook-Air:github synsx$ pip
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: cannot import name 'load_entry_point'
```

**Comment by MikeMcQuaid** [comment]
> DO NOT CREATE NEW ISSUES ON THIS REPOSITORY!
> 
> Please create all issues found when running brew install at https://github.com/Homebrew/homebrew-core/issues/new
> 
> Please create all issues found when running any other brew command at https://github.com/Homebrew/brew/issues/new

https://github.com/Homebrew/legacy-homebrew/blob/master/.github/ISSUE_TEMPLATE.md
