### ISSUE TITLE
install error of control package on Macintosh

### ISSUE THREAD

**Issue by rinusboone** [Homebrew/legacy-homebrew#50702]
I get an installation error when I want to install the control package:

>> pkg install -forge control
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: argument unused during compilation: '-L/Applications/Octave.app/Contents/Resources/usr/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/Applications/Octave.app/Contents/Resources/usr/opt/metis/lib'
<built-in>: internal compiler error: Illegal instruction: 4

<built-in>: internal compiler error: Abort trap: 6
gfortran: internal compiler error: Abort trap: 6 (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
make: *** [slicotlibrary.a] Error 4
make: *** Waiting for unfinished jobs....
clang: warning: argument unused during compilation: '-pthread'
tar -xzf slicot.tar.gz
/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/bin/mkoctfile-4.0.3 __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
cp TG04BX.fortran ./sltmp/TG04BX.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cd sltmp; /Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/bin/mkoctfile-4.0.3 -c *.f

pkg: error running `make' for the control package.
error: called from 'configure_make' in file /Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/share/octave/4.0.3/m/pkg/private/configure_make.m near line 96, column 9

**Comment by MikeMcQuaid** [comment]
Please read the issue template which will have told you not to file issues on this repository.
